var BANK = [
{"text":"阿Sir", "jp":"aa3 soe4", "eng":"Sir"},
{"text":"歡迎", "jp":"fun1 jing4", "eng":"to welcome"},
{"text":"歡迎光臨", "jp":"fun1 jing4 gwong1 lam4", "eng":"welcome for coming"},
{"text":"噉", "jp":"gam2", "eng":"so, well..."},
{"text":"嘅", "jp":"ge3", "eng":"'s"},
{"text":"叫", "jp":"giu3", "eng":"to be called; to call"},
{"text":"香港", "jp":"Hoeng1 Gong2", "eng":"Hong Kong"},
{"text":"香港大學", "jp":"Hoeng1 Gong2 Daai6 Hok6", "eng":"HKU"},
{"text":"港大", "jp":"Gong2 Daai6", "eng":"short for HKU"},
{"text":"係", "jp":"hai6", "eng":"is, am, are, was, were"},
{"text":"學校", "jp":"hok6 haau6", "eng":"school"},
{"text":"學生", "jp":"hok6 saang1", "eng":"student"},
{"text":"佢哋", "jp":"keoi5 dei6", "eng":"they, them"},
{"text":"佢嘅", "jp":"keoi5 ge3", "eng":"his, her, hers"},
{"text":"啦", "jp":"laa1", "eng":"particle - request"},
{"text":"你哋", "jp":"nei5 dei6", "eng":"you - plural"},
{"text":"你嘅", "jp":"nei5 ge3", "eng":"your, yours"},
{"text":"你好", "jp":"nei5 hou2", "eng":"(formal) Hello"},
{"text":"我嘅", "jp":"ngo5 ge3", "eng":"my; mine"},
{"text":"先生", "jp":"sin1 saang1", "eng":"Mr.; sir; husband"},
{"text":"小姐", "jp":"siu2 ze2", "eng":"Miss, young lady"},
{"text":"太太", "jp":"taai3 taai2", "eng":"Mrs.; wife"},
{"text":"呀", "jp":"aa3", "eng":"particle - question / soften"},
{"text":"亞洲", "jp":"Aa3 Zau1", "eng":"Asia"},
{"text":"歐洲", "jp":"Au1 Zau1", "eng":"Europe"},
{"text":"北美洲", "jp":"Bak1 Mei5 Zau1", "eng":"North America"},
{"text":"邊度", "jp":"bin1 dou6", "eng":"where"},
{"text":"出口", "jp":"ceot1 hau2", "eng":"exit"},
{"text":"大陸", "jp":"daai6 luk6", "eng":"Mainland China"},
{"text":"地圖", "jp":"dei6 tou4", "eng":"map"},
{"text":"的士", "jp":"dik1 si2", "eng":"taxi"},
{"text":"電話", "jp":"din6 waa2", "eng":"telephone"},
{"text":"快餐店", "jp":"faai3 caan1 dim3", "eng":"fast food shop"},
{"text":"非洲", "jp":"Fei1 Zau1", "eng":"Africa"},
{"text":"九龍", "jp":"Gau2 Lung4", "eng":"Kowloon"},
{"text":"機場", "jp":"gei1 coeng4", "eng":"airport"},
{"text":"嗰度", "jp":"go2 dou6", "eng":"there; over there"},
{"text":"國家", "jp":"gwok3 gaa1", "eng":"country"},
{"text":"國際", "jp":"gwok3 zai3", "eng":"international"},
{"text":"喺", "jp":"hai2", "eng":"at; in; on"},
{"text":"去", "jp":"heoi3", "eng":"go"},
{"text":"香港島", "jp":"Hoeng1 Gong2 Dou2", "eng":"Hong Kong Island"},
{"text":"入口", "jp":"jap6 hau2", "eng":"entrance"},
{"text":"而家", "jp":"ji4 gaa1", "eng":"now"},
{"text":"老師", "jp":"lou5 si1", "eng":"teacher"},
{"text":"唔該", "jp":"m4 goi1", "eng":"please; excuse me"},
{"text":"南美洲", "jp":"Naam4 Mei5 Zau1", "eng":"South America"},
{"text":"銀行", "jp":"ngan4 hong4", "eng":"bank"},
{"text":"我哋", "jp":"ngo5 dei6", "eng":"we, us"},
{"text":"呢度", "jp":"ni1 dou6", "eng":"here"},
{"text":"澳洲", "jp":"Ou3 Zau1", "eng":"Australia"},
{"text":"洗手間", "jp":"sai2 sau2 gaan1", "eng":"toilet; washroom"},
{"text":"中東", "jp":"Zung1 Dung1", "eng":"Middle East"},
{"text":"中國", "jp":"Zung1 Gwok3", "eng":"China"},
{"text":"中美洲", "jp":"Zung1 Mei5 Zau1", "eng":"Middle America"},
{"text":"中環", "jp":"Zung1 Waan4", "eng":"Central"},
{"text":"停車場", "jp":"ting4 ce1 coeng4", "eng":"carpark"},
{"text":"辦公室", "jp":"baan6 gung1 sat1", "eng":"office"},
{"text":"啤酒", "jp":"be1 zau2", "eng":"beer"},
{"text":"叉", "jp":"caa1", "eng":"fork"},
{"text":"厠所", "jp":"ci3 so2", "eng":"washroom; toilet"},
{"text":"簽名", "jp":"cim1 meng2", "eng":"to sign"},
{"text":"前面", "jp":"cin4 min6", "eng":"in front; ahead"},
{"text":"前門", "jp":"cin4 mun2", "eng":"front door"},
{"text":"坐", "jp":"co5", "eng":"sit"},
{"text":"沖涼房", "jp":"cung1 loeng4 fong2", "eng":"bathroom"},
{"text":"廚房", "jp":"cyu4 fong2", "eng":"kitchen"},
{"text":"大", "jp":"daai6", "eng":"big"},
{"text":"大學", "jp":"daai6 hok6", "eng":"university"},
{"text":"電梯", "jp":"din6 tai1", "eng":"escalator;elevator"},
{"text":"電話號碼", "jp":"din6 waa2 hou6 maa5", "eng":"telephone number"},
{"text":"飯廳", "jp":"faan6 teng1", "eng":"dining room"},
{"text":"房", "jp":"fong2", "eng":"room"},
{"text":"舊", "jp":"gau6", "eng":"old (not new)"},
{"text":"幾多", "jp":"gei2 do1", "eng":"how many; how much"},
{"text":"幾多號", "jp":"gei2 do1 hou6", "eng":"what number"},
{"text":"客廳", "jp":"haak3 teng1", "eng":"living room"},
{"text":"後門", "jp":"hau6 mun2", "eng":"back door"},
{"text":"好呃", "jp":"hou2 aak3", "eng":"fine, okay"},
{"text":"號", "jp":"hou6", "eng":"number; days of month"},
{"text":"飲茶", "jp":"jam2 caa4", "eng":"to have tea / dim-sum"},
{"text":"入嚟", "jp":"jap6 lei4", "eng":"come in"},
{"text":"要", "jp":"jiu3", "eng":"want; need; have to"},
{"text":"喇", "jp":"laa3", "eng":"particle - already"},
{"text":"嚟", "jp":"lai4", "eng":"to come"},
{"text":"留學生", "jp":"lau4 hok6 saang1", "eng":"foreign student"},
{"text":"樓梯", "jp":"lau4 tai1", "eng":"staircase"},
{"text":"𨋢", "jp":"lip1", "eng":"lift, elevator"},
{"text":"新嚟嘅", "jp":"san1 lei4 ge3", "eng":"just arrived; newcomer"},
{"text":"睡房", "jp":"seoi6 fong2", "eng":"bedroom"},
{"text":"司機", "jp":"si1 gei1", "eng":"driver"},
{"text":"鎖匙", "jp":"so2 si4", "eng":"key"},
{"text":"想", "jp":"soeng2", "eng":"to want to"},
{"text":"想要", "jp":"soeng2 jiu3", "eng":"to want (something)"},
{"text":"宿舍", "jp":"suk1 se3", "eng":"hostel; dormitory"},
{"text":"書房", "jp":"syu1 fong2", "eng":"study room"},
{"text":"停車", "jp":"ting4 ce1", "eng":"to stop the car"},
{"text":"圖書館", "jp":"tou4 syu1 gun2", "eng":"library"},
{"text":"屋企人", "jp":"uk1 kei2 jan4", "eng":"family members"},
{"text":"酒店", "jp":"zau2 dim3", "eng":"hotel"},
{"text":"中學", "jp":"zung1 hok6", "eng":"secondary school"},
{"text":"住", "jp":"zyu6", "eng":"live"},
{"text":"朋友", "jp":"pang4 jau5", "eng":"friend"},
{"text":"好", "jp":"hou2", "eng":"good; fine; very"},
{"text":"細", "jp":"sai3", "eng":"small"},
{"text":"新", "jp":"san1", "eng":"new"},
{"text":"靚", "jp":"leng3", "eng":"good-looking; good quality"},
{"text":"爸爸", "jp":"baa4 baa1", "eng":"father"},
{"text":"八達通咭", "jp":"baat3 daat6 tung1 kaat1", "eng":"Octopus card"},
{"text":"簽證", "jp":"cim1 zing3", "eng":"visa"},
{"text":"錢", "jp":"cin2", "eng":"money"},
{"text":"幾錢", "jp":"gei2 cin2", "eng":"how much"},
{"text":"幾多錢", "jp":"gei2 do1 cin2", "eng":"howmuch (money)"},
{"text":"幾多歲", "jp":"gei2 do1 seoi3", "eng":"how old"},
{"text":"幾多人", "jp":"gei2 do1 jan4", "eng":"How many people"},
{"text":"港幣", "jp":"Gong2 Bai6", "eng":"HK$"},
{"text":"身份證", "jp":"san1 fan2 zing3", "eng":"ID card"},
{"text":"一百蚊", "jp":"jat1 baak3 man1", "eng":"one hundred dollars"},
{"text":"一千蚊", "jp":"jat1 cin1 man1", "eng":"one thousand dollars"},
{"text":"一啲", "jp":"jat1 di1", "eng":"some"},
{"text":"一毫", "jp":"jat1 hou4", "eng":"ten cents"},
{"text":"一蚊", "jp":"jat1 man1", "eng":"one dollar"},
{"text":"有", "jp":"jau5", "eng":"have; possess"},
{"text":"二十蚊", "jp":"ji6 sap6 man1", "eng":"twenty dollars"},
{"text":"兩毫", "jp":"loeng5 hou4", "eng":"twenty cents"},
{"text":"兩蚊", "jp":"loeng5 man1", "eng":"two dollars"},
{"text":"媽媽", "jp":"maa4 maa1", "eng":"mother"},
{"text":"蚊", "jp":"man1", "eng":"dollars"},
{"text":"問題", "jp":"man6 tai4", "eng":"question; problem"},
{"text":"美金", "jp":"Mei5 Gam1", "eng":"U.S.Dollars"},
{"text":"冇", "jp":"mou5", "eng":"have not, not to have"},
{"text":"冇問題", "jp":"mou5 man6 tai4", "eng":"no problem"},
{"text":"嗱", "jp":"naa4", "eng":"Here it is!"},
{"text":"女朋友", "jp":"neoi5 pang4 jau5", "eng":"girlfriend"},
{"text":"五百蚊", "jp":"ng5 baak3 man1", "eng":"five hundred dollars"},
{"text":"五毫", "jp":"ng5 hou4", "eng":"fifty cents"},
{"text":"五蚊", "jp":"ng5 man1", "eng":"five dollars"},
{"text":"五十蚊", "jp":"ng5 sap6 man1", "eng":"fifty dollars"},
{"text":"硬幣", "jp":"ngaang6 bai6", "eng":"coin"},
{"text":"散銀", "jp":"saan2 ngan2", "eng":"coins"},
{"text":"十蚊", "jp":"sap6 man1", "eng":"ten dollars"},
{"text":"手提電話", "jp":"sau2 tai4 din6 waa2", "eng":"mobile phone"},
{"text":"信用咭", "jp":"seon3 jung6 kaat1", "eng":"credit card"},
{"text":"同", "jp":"tung4", "eng":"and; with"},
{"text":"護照", "jp":"wu6 ziu3", "eng":"passport"},
{"text":"換", "jp":"wun6", "eng":"change; exchange"},
{"text":"紙幣", "jp":"zi2 bai6", "eng":"banknotes"},
{"text":"淨係", "jp":"zing6 hai6", "eng":"only"},
{"text":"巴黎", "jp":"Baa1 Lai4", "eng":"Paris"},
{"text":"唱歌", "jp":"coeng3 go1", "eng":"sing"},
{"text":"唱K", "jp":"coeng3 kei1", "eng":"sing karaoke"},
{"text":"打麻雀", "jp":"daa2 maa4 zoek3", "eng":"play mahjong"},
{"text":"大家", "jp":"daai6 gaa1", "eng":"all, everybody"},
{"text":"弟弟", "jp":"dai4 dai2", "eng":"younger brother"},
{"text":"多謝", "jp":"do1 ze6", "eng":"thank you, many thanks"},
{"text":"讀", "jp":"duk6", "eng":"go to school; study"},
{"text":"讀書", "jp":"duk6 syu1", "eng":"study; read books"},
{"text":"翻譯", "jp":"faan1 jik6", "eng":"translation"},
{"text":"交換", "jp":"gaau1 wun6", "eng":"exchange"},
{"text":"教育", "jp":"gaau3 juk6", "eng":"education"},
{"text":"今年", "jp":"gam1 nin4", "eng":"this year"},
{"text":"哥哥", "jp":"go4 go1", "eng":"elder brother"},
{"text":"行街", "jp":"haang4 gaai1", "eng":"shopping; walking around"},
{"text":"行山", "jp":"haang4 saan1", "eng":"hiking"},
{"text":"兄弟姊妹", "jp":"hing1 dai6 zi2 mui6", "eng":"brothers and sisters"},
{"text":"興趣", "jp":"hing3 ceoi3", "eng":"a hobby; an interest"},
{"text":"音樂", "jp":"jam1 ngok6", "eng":"music"},
{"text":"人", "jp":"jan4", "eng":"people; person"},
//{"text":"英文", "jp":"Jing1 Man4", "eng":"English language"},
{"text":"影相", "jp":"jing2 soeng2", "eng":"take photographs"},
{"text":"旅行", "jp":"leoi5 hang4", "eng":"travel; traveling"},
{"text":"老闆", "jp":"lou5 baan2", "eng":"boss"},
{"text":"乜嘢科", "jp":"mat1 je5 fo1", "eng":"what subject?"},
{"text":"乜嘢人", "jp":"mat1 je5 jan4", "eng":"what people?"},
//{"text":"乜嘢名", "jp":"mat1 je5 meng2", "eng":"what name?"},
{"text":"美國", "jp":"Mei5 Gwok3", "eng":"USA"},
{"text":"美國人", "jp":"Mei5 Gwok3 jan4", "eng":"Americans"},
{"text":"妹妹", "jp":"mui4 mui2", "eng":"younger sister"},
{"text":"紐約", "jp":"Nau2 Joek3", "eng":"New York"},
{"text":"歲", "jp":"seoi3", "eng":"years old"},
{"text":"食煙", "jp":"sik6 jin1", "eng":"smoke"},
{"text":"上網", "jp":"soeng5 mong5", "eng":"to surf the internet"},
{"text":"睇戲", "jp":"tai2 hei3", "eng":"watchmovies"},
{"text":"睇書", "jp":"tai2 syu1", "eng":"read books"},
{"text":"聽", "jp":"teng1", "eng":"hear; listen"},
{"text":"聽音樂", "jp":"teng1 jam1 ngok6", "eng":"listen to music"},
{"text":"跳舞", "jp":"tiu3 mou5", "eng":"dance"},
{"text":"同事", "jp":"tung4 si6", "eng":"colleague"},
{"text":"華裔", "jp":"Waa4 jeoi6", "eng":"Chinese descent"},
{"text":"姐姐", "jp":"ze4 ze1", "eng":"elder sister"},
{"text":"做嘢", "jp":"zou6 je5", "eng":"work"},
{"text":"兩", "jp":"loeng5", "eng":"two"},
{"text":"拜拜", "jp":"baai1 baai3", "eng":"bye-bye"},
{"text":"返學", "jp":"faan1 hok6", "eng":"to go to school"},
{"text":"㗎", "jp":"gaa3", "eng":"particle - past, factual"},
{"text":"係唔係", "jp":"hai6 m4 hai6", "eng":"Is it true?"},
{"text":"係呢", "jp":"hai6 ne1", "eng":"by the way"},
{"text":"香港人", "jp":"Hoeng1 Gong2 jan4", "eng":"Hongkonger"},
{"text":"開會", "jp":"hoi1 wui2", "eng":"to attend a meeting"},
{"text":"由", "jp":"jau4", "eng":"from"},
{"text":"游水", "jp":"jau4 seoi2", "eng":"swim"},
{"text":"有事", "jp":"jau5 si6", "eng":"have something to do"},
{"text":"英國", "jp":"Jing1 Gwok3", "eng":"United Kingdom"},
{"text":"英國人", "jp":"Jing1 Gwok3 jan4", "eng":"British"},
{"text":"英文", "jp":"Jing1 Man2", "eng":"English language"},
{"text":"唔好意思", "jp":"m4 hou2 ji3 si1", "eng":"Sorry!"},
{"text":"乜嘢", "jp":"mat1 je5", "eng":"what"},
{"text":"乜嘢名", "jp":"mat1 je5 meng2", "eng":"what name?"},
{"text":"呢", "jp":"ne1", "eng":"particle - how about"},
{"text":"你貴姓呀", "jp":"nei5 gwai3 sing3 aa3", "eng":"What's your surname?"},
{"text":"你呢", "jp":"nei5 ne1", "eng":"How about you?"},
{"text":"跑步", "jp":"paau2 bou6", "eng":"running; jogging"},
{"text":"姓", "jp":"sing3", "eng":"be surnamed"},
{"text":"少少", "jp":"siu2 siu2", "eng":"a few; a little"},
{"text":"彈琴", "jp":"taan4 kam4", "eng":"play piano"},
{"text":"揸車", "jp":"zaa1 ce1", "eng":"drive (a vehicle)"},
{"text":"走", "jp":"zau2", "eng":"leave"},
{"text":"啫", "jp":"ze1", "eng":"particle - just"},
{"text":"再見", "jp":"zoi3 gin3", "eng":"goodbye"},
{"text":"中文", "jp":"Zung1 Man4", "eng":"Chinese language"},
{"text":"煮飯", "jp":"zyu2 faan6", "eng":"cook"},
{"text":"廣東話", "jp":"Gwong2 Dung1 Waa2", "eng":"Cantonese"},
{"text":"識", "jp":"sik1", "eng":"to know"},
{"text":"幾點", "jp":"gei2 dim2", "eng":"what time"},
{"text":"幾點鐘", "jp":"gei2 dim2 zung1", "eng":"what time"},
{"text":"阿", "jp":"aa3", "eng":"name prefix"},
{"text":"百貨公司", "jp":"baak3 fo3 gung1 si1", "eng":"department store"},
{"text":"不過", "jp":"bat1 gwo3", "eng":"but, however"},
{"text":"餐廳", "jp":"caan1 teng1", "eng":"restaurant"},
{"text":"診所", "jp":"can2 so2", "eng":"clinic"},
{"text":"從來唔", "jp":"cung4 loi4 m4", "eng":"never"},
{"text":"廚師", "jp":"cyu4 si1", "eng":"cook; a chef"},
{"text":"家庭主婦", "jp":"gaa1 ting4 zyu2 fu5", "eng":"housewife"},
{"text":"間中", "jp":"gaan3 zung1", "eng":"occasionally"},
{"text":"教", "jp":"gaau3", "eng":"teach"},
{"text":"教練", "jp":"gaau3 lin6", "eng":"coach; instructor"},
{"text":"教授", "jp":"gaau3 sau6", "eng":"professor"},
{"text":"經理", "jp":"ging1 lei5", "eng":"manager"},
{"text":"經常", "jp":"ging1 soeng4", "eng":"always; often"},
{"text":"警察", "jp":"ging2 caat3", "eng":"police"},
{"text":"歌手", "jp":"go1 sau2", "eng":"singer"},
{"text":"講", "jp":"gong2", "eng":"speak; talk"},
{"text":"工廠", "jp":"gung1 cong2", "eng":"factory"},
{"text":"工人", "jp":"gung1 jan4", "eng":"worker; servant"},
{"text":"公務員", "jp":"gung1 mou6 jyun4", "eng":"civil servant"},
{"text":"公司", "jp":"gung1 si1", "eng":"company; firm"},
{"text":"廣東人", "jp":"Gwong2 Dung1 jan4", "eng":"Cantonese people"},
{"text":"學", "jp":"hok6", "eng":"learn; study"},
{"text":"學院", "jp":"hok6 jyun2", "eng":"college; faculty"},
{"text":"好少", "jp":"hou2 siu2", "eng":"rarely;seldom"},
{"text":"一齊", "jp":"jat1 cai4", "eng":"together"},
{"text":"有時", "jp":"jau5 si4", "eng":"sometimes"},
{"text":"醫院", "jp":"ji1 jyun2", "eng":"hospital"},
{"text":"醫生", "jp":"ji1 sang1", "eng":"medical doctor"},
{"text":"演員", "jp":"jin2 jyun4", "eng":"actor"},
{"text":"律師", "jp":"leot6 si1", "eng":"lawyer"},
{"text":"練習", "jp":"lin6 zaap6", "eng":"to practice"},
{"text":"男朋友", "jp":"naam4 pang4 jau5", "eng":"boyfriend"},
{"text":"女演員", "jp":"neoi5 jin2 jyun4", "eng":"actress"},
{"text":"社工", "jp":"se5 gung1", "eng":"social worker"},
{"text":"時時", "jp":"si4 si4", "eng":"always; often"},
{"text":"侍應", "jp":"si6 jing3", "eng":"waiter; waitress"},
{"text":"消防員", "jp":"siu1 fong4 jyun4", "eng":"fireman"},
{"text":"位", "jp":"wai2", "eng":"MW - person"},
{"text":"護士", "jp":"wu6 si6", "eng":"nurse"},
{"text":"會計師", "jp":"wui6 gai3 si1", "eng":"accountant"},
{"text":"酒樓", "jp":"zau2 lau4", "eng":"Chinese restaurant"},
{"text":"政府部門", "jp":"zing3 fu2 bou6 mun4", "eng":"government departments"},
{"text":"中醫", "jp":"zung1 ji1", "eng":"Chinese med doctor"},
{"text":"鍾意", "jp":"zung1 ji3", "eng":"to like, be fond of"},
{"text":"八月", "jp":"baat3 jyut6", "eng":"August"},
{"text":"報紙", "jp":"bou3 zi2", "eng":"newpapers"},
{"text":"噚日", "jp":"cam4 jat6", "eng":"yesterday"},
{"text":"七月", "jp":"cat1 jyut6", "eng":"July"},
{"text":"出年", "jp":"ceot1 nin2", "eng":"next year"},
{"text":"前年", "jp":"cin4 nin2", "eng":"the year before last"},
{"text":"前日", "jp":"cin4 jat6", "eng":"the day before yesterday"},
{"text":"沖涼", "jp":"cung1 loeng4", "eng":"take a bath or shower"},
{"text":"打波", "jp":"daa2 bo1", "eng":"play ball games"},
{"text":"得閒", "jp":"dak1 haan4", "eng":"have free time; not busy"},
{"text":"都", "jp":"dou1", "eng":"also; too; all"},
{"text":"到", "jp":"dou3", "eng":"until; to"},
{"text":"讀大學", "jp":"duk6 daai6 hok6", "eng":"go to university"},
{"text":"返工", "jp":"faan1 gung1", "eng":"go to work"},
{"text":"瞓覺", "jp":"fan3 gaau3", "eng":"sleep"},
{"text":"今個星期", "jp":"gam1 go3 sing1 kei4", "eng":"this week"},
{"text":"今個月", "jp":"gam1 go3 jyut6", "eng":"this month"},
{"text":"今日", "jp":"gam1 jat6", "eng":"today"},
{"text":"今晚", "jp":"gam1 maan5", "eng":"tonight"},
{"text":"緊", "jp":"gan2", "eng":"-ing as in doing"},
{"text":"九月", "jp":"gau2 jyut6", "eng":"September"},
{"text":"舊年", "jp":"gau6 nin2", "eng":"last year"},
{"text":"幾", "jp":"gei2", "eng":"quite; fairly"},
{"text":"幾時", "jp":"gei2 si4", "eng":"when; at what time"},
{"text":"過獎", "jp":"gwo3 zoeng2", "eng":"you flatter me"},
{"text":"下個月", "jp":"haa6 go3 jyut6", "eng":"next month"},
{"text":"下個星期", "jp":"haa6 go3 sing1 kei4", "eng":"next week"},
{"text":"後日", "jp":"hau6 jat6", "eng":"the day after tomorrow"},
{"text":"後年", "jp":"hau6 nin2", "eng":"the year after next"},
{"text":"起身", "jp":"hei2 san1", "eng":"get up"},
{"text":"一月", "jp":"jat1 jyut6", "eng":"January"},
{"text":"二月", "jp":"ji6 jyut6", "eng":"February"},
{"text":"傾電話", "jp":"king1 din6 waa2", "eng":"chat on the phone"},
{"text":"傾偈", "jp":"king1 gai2", "eng":"chat"},
{"text":"律師樓", "jp":"leot6 si1 lau4", "eng":"law firm"},
{"text":"六月", "jp":"luk6 jyut6", "eng":"June"},
{"text":"唔係幾", "jp":"m4 hai6 gei2", "eng":"not quite"},
{"text":"唔使", "jp":"m4 sai2", "eng":"no need"},
{"text":"麻麻哋", "jp":"maa4 maa2 dei2", "eng":"so-so"},
{"text":"買嘢", "jp":"maai5 je5", "eng":"do shopping; buy sth"},
{"text":"乜嘢公司", "jp":"mat1 je5 gung1 si1", "eng":"what kind of company"},
{"text":"忙", "jp":"mong4", "eng":"busy"},
{"text":"五月", "jp":"ng5 jyut6", "eng":"May"},
{"text":"呢個月", "jp":"ni1 go3 jyut6", "eng":"this month"},
{"text":"呢個星期", "jp":"ni1 go3 sing1 kei4", "eng":"this week"},
{"text":"年", "jp":"nin4", "eng":"year"},
{"text":"三月", "jp":"saam1 jyut6", "eng":"March"},
{"text":"散步", "jp":"saan3 bou6", "eng":"stroll"},
{"text":"十一月", "jp":"sap6 jat1 jyut6", "eng":"November"},
{"text":"十二月", "jp":"sap6 ji6 jyut6", "eng":"December"},
{"text":"十月", "jp":"sap6 jyut6", "eng":"October"},
{"text":"四月", "jp":"sei3 jyut6", "eng":"April"},
{"text":"食嘢", "jp":"sik6 je5", "eng":"eat something"},
{"text":"星期", "jp":"sing1 kei4", "eng":"week; day of a week"},
{"text":"星期一", "jp":"sing1 kei4 jat1", "eng":"Monday"},
{"text":"星期日", "jp":"sing1 kei4 jat6", "eng":"Sunday"},
{"text":"星期二", "jp":"sing1 kei4 ji6", "eng":"Tuesday"},
{"text":"星期六", "jp":"sing1 kei4 luk6", "eng":"Saturday"},
{"text":"星期五", "jp":"sing1 kei4 ng5", "eng":"Friday"},
{"text":"星期三", "jp":"sing1 kei4 saam1", "eng":"Wednesday"},
{"text":"星期四", "jp":"sing1 kei4 sei3", "eng":"Thursday"},
{"text":"上堂", "jp":"soeng5 tong4", "eng":"to attend class"},
{"text":"上個月", "jp":"soeng6 go3 jyut6", "eng":"last month"},
{"text":"上個星期", "jp":"soeng6 go3 sing1 kei4", "eng":"last week"},
{"text":"探朋友", "jp":"taam3 pang4 jau5", "eng":"visit a friend"},
{"text":"睇報紙", "jp":"tai2 bou3 zi2", "eng":"read newspaper"},
{"text":"踢波", "jp":"tek3 bo1", "eng":"play soccer"},
{"text":"聽日", "jp":"ting1 jat6", "eng":"tomorrow"},
{"text":"運動", "jp":"wan6 dung6", "eng":"workout"},
{"text":"喎", "jp":"wo3", "eng":"particle - realization"},
{"text":"周末", "jp":"zau1 mut6", "eng":"weekend"},
{"text":"最", "jp":"zeoi3", "eng":"the most"},
{"text":"至", "jp":"zi3", "eng":"until; to"},
{"text":"做", "jp":"zou6", "eng":"do; work; engage in"},
{"text":"做乜嘢", "jp":"zou6 mat1 je5", "eng":"What's the matter?"},
{"text":"做事", "jp":"zou6 si6", "eng":"work"},
{"text":"做運動", "jp":"zou6 wan6 dung6", "eng":"to workout"},
{"text":"月", "jp":"jyut6", "eng":"moon; months"},
{"text":"便利店", "jp":"bin6 lei6 dim3", "eng":"convenience store"},
{"text":"茶餐廳", "jp":"caa4 caan1 teng1", "eng":"Hong Kong style cafe"},
{"text":"請問", "jp":"ceng2 man6", "eng":"may I ask"},
{"text":"出面", "jp":"ceot1 min6", "eng":"outside"},
{"text":"超級市場", "jp":"ciu1 kap1 si5 coeng4", "eng":"supermarket"},
{"text":"地下", "jp":"dei6 haa2", "eng":"ground floor"},
{"text":"地下", "jp":"dei6 haa6", "eng":"underground"},
{"text":"地鐵", "jp":"dei6 tit3", "eng":"underground railway"},
{"text":"地鐵站", "jp":"dei6 tit3 zaam6", "eng":"MTR station"},
{"text":"對面", "jp":"deoi3 min6", "eng":"opposite (side)"},
{"text":"賭場", "jp":"dou2 coeng4", "eng":"casino"},
{"text":"返", "jp":"faan1", "eng":"return; go/come back"},
{"text":"附近", "jp":"fu6 gan6", "eng":"vicinity; nearby"},
{"text":"街市", "jp":"gaai1 si5", "eng":"market"},
{"text":"隔離", "jp":"gaak3 lei4", "eng":"neighboring; next to"},
{"text":"間", "jp":"gaan1", "eng":"MW for buildings etc."},
{"text":"警局", "jp":"ging2 guk2", "eng":"police station"},
{"text":"公園", "jp":"gung1 jyun2", "eng":"park"},
{"text":"櫃員機", "jp":"gwai6 jyun4 gei1", "eng":"teller machine"},
{"text":"下面", "jp":"haa6 min6", "eng":"below; under"},
{"text":"後面", "jp":"hau6 min6", "eng":"at the back"},
{"text":"戲院", "jp":"hei3 jyun2", "eng":"cinema"},
{"text":"入面", "jp":"jap6 min6", "eng":"inside; in"},
{"text":"郵局", "jp":"jau4 guk2", "eng":"post office"},
{"text":"右面", "jp":"jau6 min6", "eng":"the right side"},
{"text":"二樓", "jp":"ji6 lau2", "eng":"second floor"},
{"text":"藥房", "jp":"joek6 fong4", "eng":"pharmacy"},
{"text":"樓", "jp":"lau2", "eng":"floor"},
{"text":"樓下", "jp":"lau4 haa6", "eng":"downstairs"},
{"text":"樓上", "jp":"lau4 soeng6", "eng":"upstairs"},
{"text":"裏面", "jp":"leoi5 min6", "eng":"in; inside"},
{"text":"攞", "jp":"lo2", "eng":"take; get; fetch"},
{"text":"攞錢", "jp":"lo2 cin2", "eng":"withdraw money"},
{"text":"唔使多謝", "jp":"m4 sai2 do1 ze6", "eng":"You're welcome."},
{"text":"唔使客氣", "jp":"m4 sai2 haak3 hei3", "eng":"Don't mention it."},
{"text":"唔使唔該", "jp":"m4 sai2 m4 goi1", "eng":"not at all; you're welcome"},
{"text":"馬場", "jp":"maa5 coeng4", "eng":"horse racing track"},
{"text":"外面", "jp":"ngoi6 min6", "eng":"outside"},
{"text":"澳門", "jp":"Ou3 Mun2", "eng":"Macau"},
{"text":"旁邊", "jp":"pong4 bin1", "eng":"beside; by the side of"},
{"text":"食", "jp":"sik6", "eng":"eat"},
{"text":"消防局", "jp":"siu1 fong4 guk2", "eng":"fire station"},
{"text":"上面", "jp":"soeng6 min6", "eng":"above; on-top"},
{"text":"書局", "jp":"syu1 guk2", "eng":"bookshop"},
{"text":"站", "jp":"zaam6", "eng":"station; a stop"},
{"text":"側邊", "jp":"zak1 bin1", "eng":"beside; by the side of"},
{"text":"周圍", "jp":"zau1 wai4", "eng":"around; surroundings"},
{"text":"知", "jp":"zi1", "eng":"to know about"},
{"text":"知道", "jp":"zi1 dou3", "eng":"to know about"},
{"text":"自動", "jp":"zi6 dung6", "eng":"automatic"},
{"text":"櫃員機", "jp":"gwai6 jyun4 gei1", "eng":"ATM"},
{"text":"左面", "jp":"zo2 min6", "eng":"the left side"},
{"text":"早餐", "jp":"zou2 caan1", "eng":"breakfast"},
{"text":"早晨", "jp":"zou2 san4", "eng":"good morning"},
{"text":"做功課", "jp":"zou6 gung1 fo3", "eng":"do homework"},
{"text":"中間", "jp":"zung1 gaan1", "eng":"in the middle of"},
{"text":"白粥", "jp":"baak6 zuk1", "eng":"plain rice congee"},
{"text":"飽", "jp":"baau2", "eng":"full; not hungry"},
{"text":"邊啲", "jp":"bin1 di1", "eng":"which"},
{"text":"邊間", "jp":"bin1 gaan1", "eng":"which building"},
{"text":"菠蘿包", "jp":"bo1 lo4 baau1", "eng":"pineapple bun"},
{"text":"出街", "jp":"ceot1 gaai1", "eng":"go out"},
{"text":"腸仔", "jp":"coeng2 zai2", "eng":"sausage"},
{"text":"蛋撻", "jp":"daan6 taat1", "eng":"egg tart"},
{"text":"多士", "jp":"do1 si2", "eng":"toast"},
{"text":"火腿", "jp":"fo2 teoi2", "eng":"ham"},
{"text":"叫做", "jp":"giu3 zou6", "eng":"named; known as"},
{"text":"嗰啲", "jp":"go2 di1", "eng":"that; those"},
{"text":"嗰個", "jp":"go2 go3", "eng":"that person"},
{"text":"覺得", "jp":"gok3 dak1", "eng":"to think; to feel"},
{"text":"港式", "jp":"Gong2 sik1", "eng":"HK style"},
{"text":"香腸", "jp":"hoeng1 coeng2", "eng":"sausage"},
{"text":"香港式", "jp":"Hoeng1 Gong2 sik1", "eng":"Hong Kong style"},
{"text":"好好食", "jp":"hou2 hou2 sik6", "eng":"very tasty"},
{"text":"好味", "jp":"hou2 mei6", "eng":"tasty"},
{"text":"好食", "jp":"hou2 sik6", "eng":"good to eat; tasty"},
{"text":"嚟嘅", "jp":"lai4 ge3", "eng":"particle - explanation"},
{"text":"乜嘢嚟㗎", "jp":"mat1 je5 lai4 gaa3", "eng":"What on earth is this/that?"},
{"text":"麵", "jp":"min6", "eng":"noodles"},
{"text":"麵包", "jp":"min6 baau1", "eng":"bread"},
{"text":"呢對鞋", "jp":"ni1 deoi3 haai4", "eng":"this pair of shoes"},
{"text":"呢啲", "jp":"ni1 di1", "eng":"this; these"},
{"text":"呢個", "jp":"ni1 go3", "eng":"this one"},
{"text":"呢件衫", "jp":"ni1 gin6 saam1", "eng":"this piece of clothing; this clothes"},
{"text":"皮蛋", "jp":"pei4 daan2", "eng":"preserved egg"},
{"text":"瘦肉粥", "jp":"sau3 juk6 zuk1", "eng":"congee with lean pork"},
{"text":"三文治", "jp":"saam1 man4 zi6", "eng":"sandwiches"},
{"text":"西式", "jp":"sai1 sik1", "eng":"Western style"},
{"text":"瘦肉", "jp":"sau3 juk6", "eng":"lean pork; lean meat"},
{"text":"試吓", "jp":"si3 haa5", "eng":"have a try"},
{"text":"肚餓", "jp":"tou5 ngo6", "eng":"hungry"},
{"text":"粥", "jp":"zuk1", "eng":"rice congee"},
{"text":"中式", "jp":"Zung1 sik1", "eng":"Chinese style"},
{"text":"啱", "jp":"aam1", "eng":"correct"},
{"text":"杯", "jp":"bui1", "eng":"glass, cup, mug"},
{"text":"差", "jp":"caa1", "eng":"bad; below standard"},
{"text":"橙汁", "jp":"caang2 zap1", "eng":"orange juice"},
{"text":"醜樣", "jp":"cau2 joeng2", "eng":"ugly"},
{"text":"臭", "jp":"cau3", "eng":"smelly, stench"},
{"text":"請", "jp":"ceng2", "eng":"please; invite, treat"},
{"text":"蠢", "jp":"ceon2", "eng":"stupid"},
{"text":"黐線", "jp":"ci1 sin3", "eng":"crazy"},
{"text":"錯", "jp":"co3", "eng":"wrong"},
{"text":"長", "jp":"coeng4", "eng":"long"},
{"text":"嘈", "jp":"cou4", "eng":"noisy"},
{"text":"聰明", "jp":"cung1 ming4", "eng":"smart, intelligent"},
{"text":"蛋", "jp":"daan2", "eng":"egg"},
{"text":"低", "jp":"dai1", "eng":"low"},
{"text":"定係", "jp":"ding6 hai6", "eng":"or (in questions)"},
{"text":"碟", "jp":"dip6", "eng":"a plate of"},
{"text":"短", "jp":"dyun2", "eng":"short (in length)"},
{"text":"肥", "jp":"fei4", "eng":"fat"},
{"text":"方便", "jp":"fong1 bin6", "eng":"convenient"},
{"text":"父母", "jp":"fu6 mou5", "eng":"parents"},
{"text":"加", "jp":"gaa1", "eng":"add"},
{"text":"咖啡", "jp":"gaa3 fe1", "eng":"coffee"},
{"text":"雞蛋", "jp":"gai1 daan2", "eng":"egg"},
{"text":"緊張", "jp":"gan2 zoeng1", "eng":"nervous"},
{"text":"頸渴", "jp":"geng2 hot3", "eng":"thirsty"},
{"text":"高", "jp":"gou1", "eng":"tall; high"},
{"text":"乖", "jp":"gwaai1", "eng":"good; obedient"},
{"text":"喺度食", "jp":"hai2 dou6 sik6", "eng":"eat here"},
{"text":"冚唪唥", "jp":"ham6 baang6 laang6", "eng":"all; whole"},
{"text":"後生", "jp":"hau6 saang1", "eng":"young"},
{"text":"汽水", "jp":"hei3 seoi2", "eng":"soft drinks"},
{"text":"兄弟", "jp":"hing1 dai6", "eng":"brothers"},
{"text":"可樂", "jp":"ho2 lok6", "eng":"coke"},
{"text":"開心", "jp":"hoi1 sam1", "eng":"happy"},
{"text":"好飲", "jp":"hou2 jam2", "eng":"tasty (for drinks)"},
{"text":"好人", "jp":"hou2 jan4", "eng":"kind; nice person"},
{"text":"好玩", "jp":"hou2 waan2", "eng":"fun, interesting"},
{"text":"曳", "jp":"jai5", "eng":"naughty"},
{"text":"飲", "jp":"jam2", "eng":"drink"},
{"text":"一共", "jp":"jat1 gung6", "eng":"total, altogether"},
{"text":"一陣", "jp":"jat1 zan6", "eng":"a little while"},
{"text":"鴛鴦", "jp":"jin1 joeng1", "eng":"milktea + coffee"},
{"text":"容易", "jp":"jung4 ji6", "eng":"easy"},
{"text":"遠", "jp":"jyun5", "eng":"far"},
{"text":"勤力", "jp":"kan4 lik6", "eng":"hardworking"},
{"text":"懶", "jp":"laan5", "eng":"lazy"},
{"text":"老", "jp":"lou5", "eng":"old (not young)"},
{"text":"慢", "jp":"maan6", "eng":"slow"},
{"text":"奶", "jp":"naai5", "eng":"milk"},
{"text":"奶茶", "jp":"naai5 caa4", "eng":"milk tea"},
{"text":"危險", "jp":"ngai4 him2", "eng":"dangerous"},
{"text":"牛奶", "jp":"ngau4 naai5", "eng":"milk"},
{"text":"餓", "jp":"ngo6", "eng":"hungry"},
{"text":"拎走", "jp":"ning1 zau2", "eng":"take away"},
{"text":"檸檬茶", "jp":"ning4 mung1 caa4", "eng":"lemon tea"},
{"text":"檸檬水", "jp":"ning4 mung1 seoi2", "eng":"lemonade"},
{"text":"安全", "jp":"on1 cyun4", "eng":"safe"},
{"text":"犀利", "jp":"sai1 lei6", "eng":"terrific, extreme"},
{"text":"辛苦", "jp":"san1 fu2", "eng":"hard;tough"},
{"text":"新嘢", "jp":"san1 je5", "eng":"new stuff"},
{"text":"瘦", "jp":"sau3", "eng":"thin; slim; not fat"},
{"text":"衰", "jp":"seoi1", "eng":"bad; evil minded"},
{"text":"水皮", "jp":"seoi2 pei4", "eng":"not up to standard"},
{"text":"鮮奶", "jp":"sin1 naai5", "eng":"fresh milk"},
{"text":"傻", "jp":"so4", "eng":"silly"},
{"text":"舒服", "jp":"syu1 fuk6", "eng":"comfortable"},
{"text":"糖", "jp":"tong4", "eng":"sugar"},
{"text":"齋啡", "jp":"zaai1 fe1", "eng":"black coffee"},
{"text":"正", "jp":"zeng3", "eng":"exact; cool"},
{"text":"姐妹", "jp":"zi2 mui6", "eng":"sisters"},
{"text":"即係", "jp":"zik1 hai6", "eng":"it means..."},
{"text":"靜", "jp":"zing6", "eng":"quiet"},
{"text":"朱古力", "jp":"zyu1 gu1 lik1", "eng":"chocolate"},
{"text":"吖", "jp":"aa1", "eng":"particle - suggestion"},
{"text":"叉燒包", "jp":"caa1 siu1 baau1", "eng":"BBQ pork buns"},
{"text":"炒飯", "jp":"caau2 faan6", "eng":"fried rice"},
{"text":"春卷", "jp":"ceon1 gyun2", "eng":"spring rolls"},
{"text":"豆腐花", "jp":"dau6 fu6 faa1", "eng":"bean curd dessert"},
{"text":"點心", "jp":"dim2 sam1", "eng":"dim-sum"},
{"text":"多謝先", "jp":"do1 ze6 sin1", "eng":"thank you in advance"},
{"text":"AA制", "jp":"ei1 ei1 zai3", "eng":"go Dutch"},
{"text":"返屋企", "jp":"faan1 uk1 kei2", "eng":"go/come home"},
{"text":"飯", "jp":"faan6", "eng":"cooked rice"},
{"text":"交功課", "jp":"gaau1 gung1 fo3", "eng":"submit homework"},
{"text":"結婚", "jp":"git3 fan1", "eng":"get married"},
{"text":"焗", "jp":"guk6", "eng":"baked"},
{"text":"滾水", "jp":"gwan2 seoi2", "eng":"boiling water"},
{"text":"行喇", "jp":"haang4 laa3", "eng":"let's go"},
{"text":"去街", "jp":"heoi3 gaai1", "eng":"go out"},
{"text":"好唔好呀", "jp":"hou2 m4 hou2 aa3", "eng":"Is that good? Is it okay?"},
{"text":"紅豆沙", "jp":"hung4 dau2 saa1", "eng":"red bean sweet soup"},
{"text":"飲嘢", "jp":"jam2 je5", "eng":"have a drink"},
{"text":"飲酒", "jp":"jam2 zau2", "eng":"have a alcohol drink"},
{"text":"肉", "jp":"juk6", "eng":"meat"},
{"text":"埋單", "jp":"maai4 daan1", "eng":"add up the bill; pay"},
{"text":"晚飯", "jp":"maan5 faan6", "eng":"dinner"},
{"text":"未", "jp":"mei6", "eng":"not yet"},
{"text":"女", "jp":"neoi2", "eng":"daughter"},
{"text":"普洱", "jp":"Pou2 Lei2", "eng":"Pu'er tea (black tea)"},
{"text":"食晏晝", "jp":"sik6 aan3 zau3", "eng":"have a lunch"},
{"text":"先", "jp":"sin1", "eng":"first; in advance"},
{"text":"添", "jp":"tim1", "eng":"particle - even"},
{"text":"甜品", "jp":"tim4 ban2", "eng":"dessert"},
{"text":"或者", "jp":"waak6 ze2", "eng":"or (in statements)"},
{"text":"喂", "jp":"wai3", "eng":"hello; hey"},
{"text":"壺", "jp":"wu4", "eng":"a pot of"},
{"text":"炸", "jp":"zaa3", "eng":"deep fry"},
{"text":"齋", "jp":"zaai1", "eng":"vegetarian food"},
{"text":"仔", "jp":"zai2", "eng":"son"},
{"text":"真係", "jp":"zan1 hai6", "eng":"really; indeed"},
{"text":"蒸", "jp":"zing1", "eng":"steam"},
{"text":"咗", "jp":"zo2", "eng":"(perfective form)"},
{"text":"中國菜", "jp":"Zung1 Gwok3 coi3", "eng":"Chinese cuisine"},
{"text":"仲", "jp":"zung6", "eng":"still; also"},
{"text":"放工", "jp":"fong3 gung1", "eng":"finish work; off duty"},
];

function Question(mode, id){
  var item = BANK[id];
  this.text = item.text;
  this.jp = item.jp;
  this.eng = item.eng;

  String.prototype.replaceAll = function(search, replacement) {
    var target = this;
    return target.replace(new RegExp(search, 'g'), replacement);
  };

  switch (mode){
    case MODE_REGULAR: this.lshk = item.jp.replaceAll("[0-6]",""); break;  
    case MODE_FULL:    this.lshk = item.jp; break;  
  }
  this.english = item.eng;
  this.sound = item.sound;
  this.id = id;

  this.check = function(mode, attempt) {
    return this.lshk.replaceAll(" ","").toLowerCase() == attempt.replaceAll(" ","");
  };  
}
