var BANK = [
{"text":"阿Sir", "lshk":"aa soe", "full":"aa3 soe4", "initial":"0 s", "rhyme":"aa oe", "tone":"3 4", "sound":"cfe0001.mp3" , "english":"Sir"},
{"text":"歡迎", "lshk":"fun jing", "full":"fun1 jing4", "initial":"f j", "rhyme":"un ing", "tone":"1 4", "sound":"cfe0002.mp3" , "english":"to welcome"},
{"text":"歡迎光臨", "lshk":"fun jing gwong lam", "full":"fun1 jing4 gwong1 lam4", "initial":"f j gw l", "rhyme":"un ing ong am", "tone":"1 4 1 4", "sound":"cfe0003.mp3" , "english":"welcome for coming"},
{"text":"噉", "lshk":"gam", "full":"gam2", "initial":"g", "rhyme":"am", "tone":"2", "sound":"cfe0004.mp3" , "english":"so, well..."},
{"text":"嘅", "lshk":"ge", "full":"ge3", "initial":"g", "rhyme":"e", "tone":"3", "sound":"cfe0005.mp3" , "english":"'s"},
{"text":"叫", "lshk":"giu", "full":"giu3", "initial":"g", "rhyme":"iu", "tone":"3", "sound":"cfe0006.mp3" , "english":"to be called; to call"},
{"text":"香港", "lshk":"Hoeng Gong", "full":"Hoeng1 Gong2", "initial":"h g", "rhyme":"oeng ong", "tone":"1 2", "sound":"cfe0007.mp3" , "english":"Hong Kong"},
{"text":"香港大學", "lshk":"Hoeng Gong Daai Hok", "full":"Hoeng1 Gong2 Daai6 Hok6", "initial":"h g d h", "rhyme":"oeng ong aai ok", "tone":"1 2 6 6", "sound":"cfe0008.mp3" , "english":"HKU"},
{"text":"港大", "lshk":"Gong Daai", "full":"Gong2 Daai6", "initial":"g d", "rhyme":"ong aai", "tone":"2 6", "sound":"cfe0009.mp3" , "english":"short for HKU"},
{"text":"係", "lshk":"hai", "full":"hai6", "initial":"h", "rhyme":"ai", "tone":"6", "sound":"cfe0010.mp3" , "english":"is, am, are, was, were"},
{"text":"學校", "lshk":"hok haau", "full":"hok6 haau6", "initial":"h h", "rhyme":"ok aau", "tone":"6 6", "sound":"cfe0011.mp3" , "english":"school"},
{"text":"學生", "lshk":"hok saang", "full":"hok6 saang1", "initial":"h s", "rhyme":"ok aang", "tone":"6 1", "sound":"cfe0012.mp3" , "english":"student"},
{"text":"佢哋", "lshk":"keoi dei", "full":"keoi5 dei6", "initial":"k d", "rhyme":"eoi ei", "tone":"5 6", "sound":"cfe0013.mp3" , "english":"they, them"},
{"text":"佢嘅", "lshk":"keoi ge", "full":"keoi5 ge3", "initial":"k g", "rhyme":"eoi e", "tone":"5 3", "sound":"cfe0014.mp3" , "english":"his, her, hers"},
{"text":"啦", "lshk":"laa", "full":"laa1", "initial":"l", "rhyme":"aa", "tone":"1", "sound":"cfe0015.mp3" , "english":"particle - request"},
{"text":"你哋", "lshk":"nei dei", "full":"nei5 dei6", "initial":"n d", "rhyme":"ei ei", "tone":"5 6", "sound":"cfe0016.mp3" , "english":"you - plural"},
{"text":"你嘅", "lshk":"nei ge", "full":"nei5 ge3", "initial":"n g", "rhyme":"ei e", "tone":"5 3", "sound":"cfe0017.mp3" , "english":"your, yours"},
{"text":"你好", "lshk":"nei hou", "full":"nei5 hou2", "initial":"n h", "rhyme":"ei ou", "tone":"5 2", "sound":"cfe0018.mp3" , "english":"(formal) Hello"},
{"text":"我嘅", "lshk":"ngo ge", "full":"ngo5 ge3", "initial":"ng g", "rhyme":"o e", "tone":"5 3", "sound":"cfe0019.mp3" , "english":"my; mine"},
{"text":"先生", "lshk":"sin saang", "full":"sin1 saang1", "initial":"s s", "rhyme":"in aang", "tone":"1 1", "sound":"cfe0020.mp3" , "english":"Mr.; sir; husband"},
{"text":"小姐", "lshk":"siu ze", "full":"siu2 ze2", "initial":"s z", "rhyme":"iu e", "tone":"2 2", "sound":"cfe0021.mp3" , "english":"Miss, young lady"},
{"text":"太太", "lshk":"taai taai", "full":"taai3 taai2", "initial":"t t", "rhyme":"aai aai", "tone":"3 2", "sound":"cfe0022.mp3" , "english":"Mrs.; wife"},
{"text":"呀", "lshk":"aa", "full":"aa3", "initial":"0", "rhyme":"aa", "tone":"3", "sound":"cfe0023.mp3" , "english":"particle - question / soften"},
{"text":"亞洲", "lshk":"Aa Zau", "full":"Aa3 Zau1", "initial":"0 z", "rhyme":"aa au", "tone":"3 1", "sound":"cfe0024.mp3" , "english":"Asia"},
{"text":"歐洲", "lshk":"Au Zau", "full":"Au1 Zau1", "initial":"0 z", "rhyme":"au au", "tone":"1 1", "sound":"cfe0025.mp3" , "english":"Europe"},
{"text":"北美洲", "lshk":"Bak Mei Zau", "full":"Bak1 Mei5 Zau1", "initial":"b m z", "rhyme":"ak ei au", "tone":"1 5 1", "sound":"cfe0026.mp3" , "english":"North America"},
{"text":"邊度", "lshk":"bin dou", "full":"bin1 dou6", "initial":"b d", "rhyme":"in ou", "tone":"1 6", "sound":"cfe0027.mp3" , "english":"where"},
{"text":"出口", "lshk":"ceot hau", "full":"ceot1 hau2", "initial":"c h", "rhyme":"eot au", "tone":"1 2", "sound":"cfe0028.mp3" , "english":"exit"},
{"text":"大陸", "lshk":"daai luk", "full":"daai6 luk6", "initial":"d l", "rhyme":"aai uk", "tone":"6 6", "sound":"cfe0029.mp3" , "english":"Mainland China"},
{"text":"地圖", "lshk":"dei tou", "full":"dei6 tou4", "initial":"d t", "rhyme":"ei ou", "tone":"6 4", "sound":"cfe0030.mp3" , "english":"map"},
{"text":"的士", "lshk":"dik si", "full":"dik1 si2", "initial":"d s", "rhyme":"ik i", "tone":"1 2", "sound":"cfe0031.mp3" , "english":"taxi"},
{"text":"電話", "lshk":"din waa", "full":"din6 waa2", "initial":"d w", "rhyme":"in aa", "tone":"6 2", "sound":"cfe0032.mp3" , "english":"telephone"},
{"text":"快餐店", "lshk":"faai caan dim", "full":"faai3 caan1 dim3", "initial":"f c d", "rhyme":"aai aan im", "tone":"3 1 3", "sound":"cfe0033.mp3" , "english":"fast food shop"},
{"text":"非洲", "lshk":"Fei Zau", "full":"Fei1 Zau1", "initial":"f z", "rhyme":"ei au", "tone":"1 1", "sound":"cfe0034.mp3" , "english":"Africa"},
{"text":"九龍", "lshk":"Gau Lung", "full":"Gau2 Lung4", "initial":"g l", "rhyme":"au ung", "tone":"2 4", "sound":"cfe0035.mp3" , "english":"Kowloon"},
{"text":"機場", "lshk":"gei coeng", "full":"gei1 coeng4", "initial":"g c", "rhyme":"ei oeng", "tone":"1 4", "sound":"cfe0036.mp3" , "english":"airport"},
{"text":"嗰度", "lshk":"go dou", "full":"go2 dou6", "initial":"g d", "rhyme":"o ou", "tone":"2 6", "sound":"cfe0037.mp3" , "english":"there; over there"},
{"text":"國家", "lshk":"gwok gaa", "full":"gwok3 gaa1", "initial":"gw g", "rhyme":"ok aa", "tone":"3 1", "sound":"cfe0038.mp3" , "english":"country"},
{"text":"國際", "lshk":"gwok zai", "full":"gwok3 zai3", "initial":"gw z", "rhyme":"ok ai", "tone":"3 3", "sound":"cfe0039.mp3" , "english":"international"},
{"text":"喺", "lshk":"hai", "full":"hai2", "initial":"h", "rhyme":"ai", "tone":"2", "sound":"cfe0040.mp3" , "english":"at; in; on"},
{"text":"去", "lshk":"heoi", "full":"heoi3", "initial":"h", "rhyme":"eoi", "tone":"3", "sound":"cfe0041.mp3" , "english":"go"},
{"text":"香港島", "lshk":"Hoeng Gong Dou", "full":"Hoeng1 Gong2 Dou2", "initial":"h g d", "rhyme":"oeng ong ou", "tone":"1 2 2", "sound":"cfe0042.mp3" , "english":"Hong Kong Island"},
{"text":"入口", "lshk":"jap hau", "full":"jap6 hau2", "initial":"j h", "rhyme":"ap au", "tone":"6 2", "sound":"cfe0043.mp3" , "english":"entrance"},
{"text":"而家", "lshk":"ji gaa", "full":"ji4 gaa1", "initial":"j g", "rhyme":"i aa", "tone":"4 1", "sound":"cfe0044.mp3" , "english":"now"},
{"text":"老師", "lshk":"lou si", "full":"lou5 si1", "initial":"l s", "rhyme":"ou i", "tone":"5 1", "sound":"cfe0045.mp3" , "english":"teacher"},
{"text":"唔該", "lshk":"m goi", "full":"m4 goi1", "initial":"0 g", "rhyme":"m oi", "tone":"4 1", "sound":"cfe0046.mp3" , "english":"please; excuse me"},
{"text":"南美洲", "lshk":"Naam Mei Zau", "full":"Naam4 Mei5 Zau1", "initial":"n m z", "rhyme":"aam ei au", "tone":"4 5 1", "sound":"cfe0047.mp3" , "english":"South America"},
{"text":"銀行", "lshk":"ngan hong", "full":"ngan4 hong4", "initial":"ng h", "rhyme":"an ong", "tone":"4 4", "sound":"cfe0048.mp3" , "english":"bank"},
{"text":"我哋", "lshk":"ngo dei", "full":"ngo5 dei6", "initial":"ng d", "rhyme":"o ei", "tone":"5 6", "sound":"cfe0049.mp3" , "english":"we, us"},
{"text":"呢度", "lshk":"ni dou", "full":"ni1 dou6", "initial":"n d", "rhyme":"i ou", "tone":"1 6", "sound":"cfe0050.mp3" , "english":"here"},
{"text":"澳洲", "lshk":"Ou Zau", "full":"Ou3 Zau1", "initial":"0 z", "rhyme":"ou au", "tone":"3 1", "sound":"cfe0051.mp3" , "english":"Australia"},
{"text":"洗手間", "lshk":"sai sau gaan", "full":"sai2 sau2 gaan1", "initial":"s s g", "rhyme":"ai au aan", "tone":"2 2 1", "sound":"cfe0052.mp3" , "english":"toilet; washroom"},
{"text":"中東", "lshk":"Zung Dung", "full":"Zung1 Dung1", "initial":"z d", "rhyme":"ung ung", "tone":"1 1", "sound":"cfe0053.mp3" , "english":"Middle East"},
{"text":"中國", "lshk":"Zung Gwok", "full":"Zung1 Gwok3", "initial":"z gw", "rhyme":"ung ok", "tone":"1 3", "sound":"cfe0054.mp3" , "english":"China"},
{"text":"中美洲", "lshk":"Zung Mei Zau", "full":"Zung1 Mei5 Zau1", "initial":"z m z", "rhyme":"ung ei au", "tone":"1 5 1", "sound":"cfe0055.mp3" , "english":"Middle America"},
{"text":"中環", "lshk":"Zung Waan", "full":"Zung1 Waan4", "initial":"z w", "rhyme":"ung aan", "tone":"1 4", "sound":"cfe0056.mp3" , "english":"Central"},
{"text":"停車場", "lshk":"ting ce coeng", "full":"ting4 ce1 coeng4", "initial":"t c c", "rhyme":"ing e oeng", "tone":"4 1 4", "sound":"cfe0057.mp3" , "english":"carpark"},
{"text":"辦公室", "lshk":"baan gung sat", "full":"baan6 gung1 sat1", "initial":"b g s", "rhyme":"aan ung at", "tone":"6 1 1", "sound":"cfe0058.mp3" , "english":"office"},
{"text":"啤酒", "lshk":"be zau", "full":"be1 zau2", "initial":"b z", "rhyme":"e au", "tone":"1 2", "sound":"cfe0059.mp3" , "english":"beer"},
{"text":"叉", "lshk":"caa", "full":"caa1", "initial":"c", "rhyme":"aa", "tone":"1", "sound":"cfe0060.mp3" , "english":"fork"},
{"text":"厠所", "lshk":"ci so", "full":"ci3 so2", "initial":"c s", "rhyme":"i o", "tone":"3 2", "sound":"cfe0061.mp3" , "english":"washroom; toilet"},
{"text":"簽名", "lshk":"cim meng", "full":"cim1 meng2", "initial":"c m", "rhyme":"im eng", "tone":"1 2", "sound":"cfe0062.mp3" , "english":"to sign"},
{"text":"前面", "lshk":"cin min", "full":"cin4 min6", "initial":"c m", "rhyme":"in in", "tone":"4 6", "sound":"cfe0063.mp3" , "english":"in front; ahead"},
{"text":"前門", "lshk":"cin mun", "full":"cin4 mun2", "initial":"c m", "rhyme":"in un", "tone":"4 2", "sound":"cfe0064.mp3" , "english":"front door"},
{"text":"坐", "lshk":"co", "full":"co5", "initial":"c", "rhyme":"o", "tone":"5", "sound":"cfe0065.mp3" , "english":"sit"},
{"text":"沖涼房", "lshk":"cung loeng fong", "full":"cung1 loeng4 fong2", "initial":"c l f", "rhyme":"ung oeng ong", "tone":"1 4 2", "sound":"cfe0066.mp3" , "english":"bathroom"},
{"text":"廚房", "lshk":"cyu fong", "full":"cyu4 fong2", "initial":"c f", "rhyme":"yu ong", "tone":"4 2", "sound":"cfe0067.mp3" , "english":"kitchen"},
{"text":"大", "lshk":"daai", "full":"daai6", "initial":"d", "rhyme":"aai", "tone":"6", "sound":"cfe0068.mp3" , "english":"big"},
{"text":"大學", "lshk":"daai hok", "full":"daai6 hok6", "initial":"d h", "rhyme":"aai ok", "tone":"6 6", "sound":"cfe0069.mp3" , "english":"university"},
{"text":"電梯", "lshk":"din tai", "full":"din6 tai1", "initial":"d t", "rhyme":"in ai", "tone":"6 1", "sound":"cfe0070.mp3" , "english":"escalator;elevator"},
{"text":"電話號碼", "lshk":"din waa hou maa", "full":"din6 waa2 hou6 maa5", "initial":"d w h m", "rhyme":"in aa ou aa", "tone":"6 2 6 5", "sound":"cfe0071.mp3" , "english":"telephone number"},
{"text":"飯廳", "lshk":"faan teng", "full":"faan6 teng1", "initial":"f t", "rhyme":"aan eng", "tone":"6 1", "sound":"cfe0072.mp3" , "english":"dining room"},
{"text":"房", "lshk":"fong", "full":"fong2", "initial":"f", "rhyme":"ong", "tone":"2", "sound":"cfe0073.mp3" , "english":"room"},
{"text":"舊", "lshk":"gau", "full":"gau6", "initial":"g", "rhyme":"au", "tone":"6", "sound":"cfe0074.mp3" , "english":"old (not new)"},
{"text":"幾多", "lshk":"gei do", "full":"gei2 do1", "initial":"g d", "rhyme":"ei o", "tone":"2 1", "sound":"cfe0075.mp3" , "english":"how many; how much"},
{"text":"幾多號", "lshk":"gei do hou", "full":"gei2 do1 hou6", "initial":"g d h", "rhyme":"ei o ou", "tone":"2 1 6", "sound":"cfe0076.mp3" , "english":"what number"},
{"text":"客廳", "lshk":"haak teng", "full":"haak3 teng1", "initial":"h t", "rhyme":"aak eng", "tone":"3 1", "sound":"cfe0077.mp3" , "english":"living room"},
{"text":"後門", "lshk":"hau mun", "full":"hau6 mun2", "initial":"h m", "rhyme":"au un", "tone":"6 2", "sound":"cfe0078.mp3" , "english":"back door"},
{"text":"好呃", "lshk":"hou aak", "full":"hou2 aak3", "initial":"h 0", "rhyme":"ou aak", "tone":"2 3", "sound":"cfe0079.mp3" , "english":"fine, okay"},
{"text":"號", "lshk":"hou", "full":"hou6", "initial":"h", "rhyme":"ou", "tone":"6", "sound":"cfe0080.mp3" , "english":"number; days of month"},
{"text":"飲茶", "lshk":"jam caa", "full":"jam2 caa4", "initial":"j c", "rhyme":"am aa", "tone":"2 4", "sound":"cfe0081.mp3" , "english":"to have tea / dim-sum"},
{"text":"入嚟", "lshk":"jap lei", "full":"jap6 lei4", "initial":"j l", "rhyme":"ap ei", "tone":"6 4", "sound":"cfe0082.mp3" , "english":"come in"},
{"text":"要", "lshk":"jiu", "full":"jiu3", "initial":"j", "rhyme":"iu", "tone":"3", "sound":"cfe0083.mp3" , "english":"want; need; have to"},
{"text":"喇", "lshk":"laa", "full":"laa3", "initial":"l", "rhyme":"aa", "tone":"3", "sound":"cfe0084.mp3" , "english":"particle - already"},
{"text":"嚟", "lshk":"lai", "full":"lai4", "initial":"l", "rhyme":"ai", "tone":"4", "sound":"cfe0085.mp3" , "english":"to come"},
{"text":"留學生", "lshk":"lau hok saang", "full":"lau4 hok6 saang1", "initial":"l h s", "rhyme":"au ok aang", "tone":"4 6 1", "sound":"cfe0086.mp3" , "english":"foreign student"},
{"text":"樓梯", "lshk":"lau tai", "full":"lau4 tai1", "initial":"l t", "rhyme":"au ai", "tone":"4 1", "sound":"cfe0087.mp3" , "english":"staircase"},
{"text":"𨋢", "lshk":"lip", "full":"lip1", "initial":"l", "rhyme":"ip", "tone":"1", "sound":"cfe0088.mp3" , "english":"lift, elevator"},
{"text":"新嚟嘅", "lshk":"san lei ge", "full":"san1 lei4 ge3", "initial":"s l g", "rhyme":"an ei e", "tone":"1 4 3", "sound":"cfe0089.mp3" , "english":"just arrived; newcomer"},
{"text":"睡房", "lshk":"seoi fong", "full":"seoi6 fong2", "initial":"s f", "rhyme":"eoi ong", "tone":"6 2", "sound":"cfe0090.mp3" , "english":"bedroom"},
{"text":"司機", "lshk":"si gei", "full":"si1 gei1", "initial":"s g", "rhyme":"i ei", "tone":"1 1", "sound":"cfe0091.mp3" , "english":"driver"},
{"text":"鎖匙", "lshk":"so si", "full":"so2 si4", "initial":"s s", "rhyme":"o i", "tone":"2 4", "sound":"cfe0092.mp3" , "english":"key"},
{"text":"想", "lshk":"soeng", "full":"soeng2", "initial":"s", "rhyme":"oeng", "tone":"2", "sound":"cfe0093.mp3" , "english":"to want to"},
{"text":"想要", "lshk":"soeng jiu", "full":"soeng2 jiu3", "initial":"s j", "rhyme":"oeng iu", "tone":"2 3", "sound":"cfe0094.mp3" , "english":"to want (something)"},
{"text":"宿舍", "lshk":"suk se", "full":"suk1 se3", "initial":"s s", "rhyme":"uk e", "tone":"1 3", "sound":"cfe0095.mp3" , "english":"hostel; dormitory"},
{"text":"書房", "lshk":"syu fong", "full":"syu1 fong2", "initial":"s f", "rhyme":"yu ong", "tone":"1 2", "sound":"cfe0096.mp3" , "english":"study room"},
{"text":"停車", "lshk":"ting ce", "full":"ting4 ce1", "initial":"t c", "rhyme":"ing e", "tone":"4 1", "sound":"cfe0097.mp3" , "english":"to stop the car"},
{"text":"圖書館", "lshk":"tou syu gun", "full":"tou4 syu1 gun2", "initial":"t s g", "rhyme":"ou yu un", "tone":"4 1 2", "sound":"cfe0098.mp3" , "english":"library"},
{"text":"屋企人", "lshk":"uk kei jan", "full":"uk1 kei2 jan4", "initial":"0 k j", "rhyme":"uk ei an", "tone":"1 2 4", "sound":"cfe0099.mp3" , "english":"family members"},
{"text":"酒店", "lshk":"zau dim", "full":"zau2 dim3", "initial":"z d", "rhyme":"au im", "tone":"2 3", "sound":"cfe0100.mp3" , "english":"hotel"},
{"text":"中學", "lshk":"zung hok", "full":"zung1 hok6", "initial":"z h", "rhyme":"ung ok", "tone":"1 6", "sound":"cfe0101.mp3" , "english":"secondary school"},
{"text":"住", "lshk":"zyu", "full":"zyu6", "initial":"z", "rhyme":"yu", "tone":"6", "sound":"cfe0102.mp3" , "english":"live"},
{"text":"朋友", "lshk":"pang jau", "full":"pang4 jau5", "initial":"p j", "rhyme":"ang au", "tone":"4 5", "sound":"cfe0103.mp3" , "english":"friend"},
{"text":"好", "lshk":"hou", "full":"hou2", "initial":"h", "rhyme":"ou", "tone":"2", "sound":"cfe0104.mp3" , "english":"good; fine; very"},
{"text":"細", "lshk":"sai", "full":"sai3", "initial":"s", "rhyme":"ai", "tone":"3", "sound":"cfe0105.mp3" , "english":"small"},
{"text":"新", "lshk":"san", "full":"san1", "initial":"s", "rhyme":"an", "tone":"1", "sound":"cfe0106.mp3" , "english":"new"},
{"text":"靚", "lshk":"leng", "full":"leng3", "initial":"l", "rhyme":"eng", "tone":"3", "sound":"cfe0107.mp3" , "english":"good-looking; good quality"},
{"text":"爸爸", "lshk":"baa baa", "full":"baa4 baa1", "initial":"b b", "rhyme":"aa aa", "tone":"4 1", "sound":"cfe0108.mp3" , "english":"father"},
{"text":"八達通咭", "lshk":"baat daat tung kaat", "full":"baat3 daat6 tung1 kaat1", "initial":"b d t k", "rhyme":"aat aat ung aat", "tone":"3 6 1 1", "sound":"cfe0109.mp3" , "english":"Octopus card"},
{"text":"簽證", "lshk":"cim zing", "full":"cim1 zing3", "initial":"c z", "rhyme":"im ing", "tone":"1 3", "sound":"cfe0110.mp3" , "english":"visa"},
{"text":"錢", "lshk":"cin", "full":"cin2", "initial":"c", "rhyme":"in", "tone":"2", "sound":"cfe0111.mp3" , "english":"money"},
{"text":"幾錢", "lshk":"gei cin", "full":"gei2 cin2", "initial":"g c", "rhyme":"ei in", "tone":"2 2", "sound":"cfe0112.mp3" , "english":"how much"},
{"text":"幾多錢", "lshk":"gei do cin", "full":"gei2 do1 cin2", "initial":"g d c", "rhyme":"ei o in", "tone":"2 1 2", "sound":"cfe0113.mp3" , "english":"howmuch (money)"},
{"text":"幾多歲", "lshk":"gei do seoi", "full":"gei2 do1 seoi3", "initial":"g d s", "rhyme":"ei o eoi", "tone":"2 1 3", "sound":"cfe0114.mp3" , "english":"how old"},
{"text":"幾多人", "lshk":"gei do jan", "full":"gei2 do1 jan4", "initial":"g d j", "rhyme":"ei o an", "tone":"2 1 4", "sound":"cfe0115.mp3" , "english":"How many people"},
{"text":"港幣", "lshk":"Gong Bai", "full":"Gong2 Bai6", "initial":"g b", "rhyme":"ong ai", "tone":"2 6", "sound":"cfe0116.mp3" , "english":"HK$"},
{"text":"身份證", "lshk":"san fan zing", "full":"san1 fan2 zing3", "initial":"s f z", "rhyme":"an an ing", "tone":"1 2 3", "sound":"cfe0117.mp3" , "english":"ID card"},
{"text":"一百蚊", "lshk":"jat baak man", "full":"jat1 baak3 man1", "initial":"j b m", "rhyme":"at aak an", "tone":"1 3 1", "sound":"cfe0118.mp3" , "english":"one hundred dollars"},
{"text":"一千蚊", "lshk":"jat cin man", "full":"jat1 cin1 man1", "initial":"j c m", "rhyme":"at in an", "tone":"1 1 1", "sound":"cfe0119.mp3" , "english":"one thousand dollars"},
{"text":"一啲", "lshk":"jat di", "full":"jat1 di1", "initial":"j d", "rhyme":"at i", "tone":"1 1", "sound":"cfe0120.mp3" , "english":"some"},
{"text":"一毫", "lshk":"jat hou", "full":"jat1 hou4", "initial":"j h", "rhyme":"at ou", "tone":"1 4", "sound":"cfe0121.mp3" , "english":"ten cents"},
{"text":"一蚊", "lshk":"jat man", "full":"jat1 man1", "initial":"j m", "rhyme":"at an", "tone":"1 1", "sound":"cfe0122.mp3" , "english":"one dollar"},
{"text":"有", "lshk":"jau", "full":"jau5", "initial":"j", "rhyme":"au", "tone":"5", "sound":"cfe0123.mp3" , "english":"have; possess"},
{"text":"二十蚊", "lshk":"ji sap man", "full":"ji6 sap6 man1", "initial":"j s m", "rhyme":"i ap an", "tone":"6 6 1", "sound":"cfe0124.mp3" , "english":"twenty dollars"},
{"text":"兩毫", "lshk":"loeng hou", "full":"loeng5 hou4", "initial":"l h", "rhyme":"oeng ou", "tone":"5 4", "sound":"cfe0125.mp3" , "english":"twenty cents"},
{"text":"兩蚊", "lshk":"loeng man", "full":"loeng5 man1", "initial":"l m", "rhyme":"oeng an", "tone":"5 1", "sound":"cfe0126.mp3" , "english":"two dollars"},
{"text":"媽媽", "lshk":"maa maa", "full":"maa4 maa1", "initial":"m m", "rhyme":"aa aa", "tone":"4 1", "sound":"cfe0127.mp3" , "english":"mother"},
{"text":"蚊", "lshk":"man", "full":"man1", "initial":"m", "rhyme":"an", "tone":"1", "sound":"cfe0128.mp3" , "english":"dollars"},
{"text":"問題", "lshk":"man tai", "full":"man6 tai4", "initial":"m t", "rhyme":"an ai", "tone":"6 4", "sound":"cfe0129.mp3" , "english":"question; problem"},
{"text":"美金", "lshk":"Mei Gam", "full":"Mei5 Gam1", "initial":"m g", "rhyme":"ei am", "tone":"5 1", "sound":"cfe0130.mp3" , "english":"U.S.Dollars"},
{"text":"冇", "lshk":"mou", "full":"mou5", "initial":"m", "rhyme":"ou", "tone":"5", "sound":"cfe0131.mp3" , "english":"have not, not to have"},
{"text":"冇問題", "lshk":"mou man tai", "full":"mou5 man6 tai4", "initial":"m m t", "rhyme":"ou an ai", "tone":"5 6 4", "sound":"cfe0132.mp3" , "english":"no problem"},
{"text":"嗱", "lshk":"naa", "full":"naa4", "initial":"n", "rhyme":"aa", "tone":"4", "sound":"cfe0133.mp3" , "english":"Here it is!"},
{"text":"女朋友", "lshk":"neoi pang jau", "full":"neoi5 pang4 jau5", "initial":"n p j", "rhyme":"eoi ang au", "tone":"5 4 5", "sound":"cfe0134.mp3" , "english":"girlfriend"},
{"text":"五百蚊", "lshk":"ng baak man", "full":"ng5 baak3 man1", "initial":"0 b m", "rhyme":"ng aak an", "tone":"5 3 1", "sound":"cfe0135.mp3" , "english":"five hundred dollars"},
{"text":"五毫", "lshk":"ng hou", "full":"ng5 hou4", "initial":"0 h", "rhyme":"ng ou", "tone":"5 4", "sound":"cfe0136.mp3" , "english":"fifty cents"},
{"text":"五蚊", "lshk":"ng man", "full":"ng5 man1", "initial":"0 m", "rhyme":"ng an", "tone":"5 1", "sound":"cfe0137.mp3" , "english":"five dollars"},
{"text":"五十蚊", "lshk":"ng sap man", "full":"ng5 sap6 man1", "initial":"0 s m", "rhyme":"ng ap an", "tone":"5 6 1", "sound":"cfe0138.mp3" , "english":"fifty dollars"},
{"text":"硬幣", "lshk":"ngaang bai", "full":"ngaang6 bai6", "initial":"ng b", "rhyme":"aang ai", "tone":"6 6", "sound":"cfe0139.mp3" , "english":"coin"},
{"text":"散銀", "lshk":"saan ngan", "full":"saan2 ngan2", "initial":"s ng", "rhyme":"aan an", "tone":"2 2", "sound":"cfe0140.mp3" , "english":"coins"},
{"text":"十蚊", "lshk":"sap man", "full":"sap6 man1", "initial":"s m", "rhyme":"ap an", "tone":"6 1", "sound":"cfe0141.mp3" , "english":"ten dollars"},
{"text":"手提電話", "lshk":"sau tai din waa", "full":"sau2 tai4 din6 waa2", "initial":"s t d w", "rhyme":"au ai in aa", "tone":"2 4 6 2", "sound":"cfe0142.mp3" , "english":"mobile phone"},
{"text":"信用咭", "lshk":"seon jung kaat", "full":"seon3 jung6 kaat1", "initial":"s j k", "rhyme":"eon ung aat", "tone":"3 6 1", "sound":"cfe0143.mp3" , "english":"credit card"},
{"text":"同", "lshk":"tung", "full":"tung4", "initial":"t", "rhyme":"ung", "tone":"4", "sound":"cfe0144.mp3" , "english":"and; with"},
{"text":"護照", "lshk":"wu ziu", "full":"wu6 ziu3", "initial":"w z", "rhyme":"u iu", "tone":"6 3", "sound":"cfe0145.mp3" , "english":"passport"},
{"text":"換", "lshk":"wun", "full":"wun6", "initial":"w", "rhyme":"un", "tone":"6", "sound":"cfe0146.mp3" , "english":"change; exchange"},
{"text":"紙幣", "lshk":"zi bai", "full":"zi2 bai6", "initial":"z b", "rhyme":"i ai", "tone":"2 6", "sound":"cfe0147.mp3" , "english":"banknotes"},
{"text":"淨係", "lshk":"zing hai", "full":"zing6 hai6", "initial":"z h", "rhyme":"ing ai", "tone":"6 6", "sound":"cfe0148.mp3" , "english":"only"},
{"text":"巴黎", "lshk":"Baa Lai", "full":"Baa1 Lai4", "initial":"b l", "rhyme":"aa ai", "tone":"1 4", "sound":"cfe0149.mp3" , "english":"Paris"},
{"text":"唱歌", "lshk":"coeng go", "full":"coeng3 go1", "initial":"c g", "rhyme":"oeng o", "tone":"3 1", "sound":"cfe0150.mp3" , "english":"sing"},
{"text":"唱K", "lshk":"coeng kei", "full":"coeng3 kei1", "initial":"c k", "rhyme":"oeng ei", "tone":"3 1", "sound":"cfe0151.mp3" , "english":"sing karaoke"},
{"text":"打麻雀", "lshk":"daa maa zoek", "full":"daa2 maa4 zoek3", "initial":"d m z", "rhyme":"aa aa oek", "tone":"2 4 3", "sound":"cfe0152.mp3" , "english":"play mahjong"},
{"text":"大家", "lshk":"daai gaa", "full":"daai6 gaa1", "initial":"d g", "rhyme":"aai aa", "tone":"6 1", "sound":"cfe0153.mp3" , "english":"all, everybody"},
{"text":"弟弟", "lshk":"dai dai", "full":"dai4 dai2", "initial":"d d", "rhyme":"ai ai", "tone":"4 2", "sound":"cfe0154.mp3" , "english":"younger brother"},
{"text":"多謝", "lshk":"do ze", "full":"do1 ze6", "initial":"d z", "rhyme":"o e", "tone":"1 6", "sound":"cfe0155.mp3" , "english":"thank you, many thanks"},
{"text":"讀", "lshk":"duk", "full":"duk6", "initial":"d", "rhyme":"uk", "tone":"6", "sound":"cfe0156.mp3" , "english":"go to school; study"},
{"text":"讀書", "lshk":"duk syu", "full":"duk6 syu1", "initial":"d s", "rhyme":"uk yu", "tone":"6 1", "sound":"cfe0157.mp3" , "english":"study; read books"},
{"text":"翻譯", "lshk":"faan jik", "full":"faan1 jik6", "initial":"f j", "rhyme":"aan ik", "tone":"1 6", "sound":"cfe0158.mp3" , "english":"translation"},
{"text":"交換", "lshk":"gaau wun", "full":"gaau1 wun6", "initial":"g w", "rhyme":"aau un", "tone":"1 6", "sound":"cfe0159.mp3" , "english":"exchange"},
{"text":"教育", "lshk":"gaau juk", "full":"gaau3 juk6", "initial":"g j", "rhyme":"aau uk", "tone":"3 6", "sound":"cfe0160.mp3" , "english":"education"},
{"text":"今年", "lshk":"gam nin", "full":"gam1 nin4", "initial":"g n", "rhyme":"am in", "tone":"1 4", "sound":"cfe0161.mp3" , "english":"this year"},
{"text":"哥哥", "lshk":"go go", "full":"go4 go1", "initial":"g g", "rhyme":"o o", "tone":"4 1", "sound":"cfe0162.mp3" , "english":"elder brother"},
{"text":"行街", "lshk":"haang gaai", "full":"haang4 gaai1", "initial":"h g", "rhyme":"aang aai", "tone":"4 1", "sound":"cfe0163.mp3" , "english":"shopping; walking around"},
{"text":"行山", "lshk":"haang saan", "full":"haang4 saan1", "initial":"h s", "rhyme":"aang aan", "tone":"4 1", "sound":"cfe0164.mp3" , "english":"hiking"},
{"text":"兄弟姊妹", "lshk":"hing dai zi mui", "full":"hing1 dai6 zi2 mui6", "initial":"h d z m", "rhyme":"ing ai i ui", "tone":"1 6 2 6", "sound":"cfe0165.mp3" , "english":"brothers and sisters"},
{"text":"興趣", "lshk":"hing ceoi", "full":"hing3 ceoi3", "initial":"h c", "rhyme":"ing eoi", "tone":"3 3", "sound":"cfe0166.mp3" , "english":"a hobby; an interest"},
{"text":"音樂", "lshk":"jam ngok", "full":"jam1 ngok6", "initial":"j ng", "rhyme":"am ok", "tone":"1 6", "sound":"cfe0167.mp3" , "english":"music"},
{"text":"人", "lshk":"jan", "full":"jan4", "initial":"j", "rhyme":"an", "tone":"4", "sound":"cfe0168.mp3" , "english":"people; person"},
//{"text":"英文", "lshk":"Jing Man", "full":"Jing1 Man4", "initial":"j m", "rhyme":"ing an", "tone":"1 4", "sound":"cfe0169.mp3" , "english":"English language"},
{"text":"影相", "lshk":"jing soeng", "full":"jing2 soeng2", "initial":"j s", "rhyme":"ing oeng", "tone":"2 2", "sound":"cfe0170.mp3" , "english":"take photographs"},
{"text":"旅行", "lshk":"leoi hang", "full":"leoi5 hang4", "initial":"l h", "rhyme":"eoi ang", "tone":"5 4", "sound":"cfe0171.mp3" , "english":"travel; traveling"},
{"text":"老闆", "lshk":"lou baan", "full":"lou5 baan2", "initial":"l b", "rhyme":"ou aan", "tone":"5 2", "sound":"cfe0172.mp3" , "english":"boss"},
{"text":"乜嘢科", "lshk":"mat je fo", "full":"mat1 je5 fo1", "initial":"m j f", "rhyme":"at e o", "tone":"1 5 1", "sound":"cfe0173.mp3" , "english":"what subject?"},
{"text":"乜嘢人", "lshk":"mat je jan", "full":"mat1 je5 jan4", "initial":"m j j", "rhyme":"at e an", "tone":"1 5 4", "sound":"cfe0174.mp3" , "english":"what people?"},
//{"text":"乜嘢名", "lshk":"mat je meng", "full":"mat1 je5 meng2", "initial":"m j m", "rhyme":"at e eng", "tone":"1 5 2", "sound":"cfe0175.mp3" , "english":"what name?"},
{"text":"美國", "lshk":"Mei Gwok", "full":"Mei5 Gwok3", "initial":"m gw", "rhyme":"ei ok", "tone":"5 3", "sound":"cfe0176.mp3" , "english":"USA"},
{"text":"美國人", "lshk":"Mei Gwok jan", "full":"Mei5 Gwok3 jan4", "initial":"m gw j", "rhyme":"ei ok an", "tone":"5 3 4", "sound":"cfe0177.mp3" , "english":"Americans"},
{"text":"妹妹", "lshk":"mui mui", "full":"mui4 mui2", "initial":"m m", "rhyme":"ui ui", "tone":"4 2", "sound":"cfe0178.mp3" , "english":"younger sister"},
{"text":"紐約", "lshk":"Nau Joek", "full":"Nau2 Joek3", "initial":"n j", "rhyme":"au oek", "tone":"2 3", "sound":"cfe0179.mp3" , "english":"New York"},
{"text":"歲", "lshk":"seoi", "full":"seoi3", "initial":"s", "rhyme":"eoi", "tone":"3", "sound":"cfe0180.mp3" , "english":"years old"},
{"text":"食煙", "lshk":"sik jin", "full":"sik6 jin1", "initial":"s j", "rhyme":"ik in", "tone":"6 1", "sound":"cfe0181.mp3" , "english":"smoke"},
{"text":"上網", "lshk":"soeng mong", "full":"soeng5 mong5", "initial":"s m", "rhyme":"oeng ong", "tone":"5 5", "sound":"cfe0182.mp3" , "english":"to surf the internet"},
{"text":"睇戲", "lshk":"tai hei", "full":"tai2 hei3", "initial":"t h", "rhyme":"ai ei", "tone":"2 3", "sound":"cfe0183.mp3" , "english":"watchmovies"},
{"text":"睇書", "lshk":"tai syu", "full":"tai2 syu1", "initial":"t s", "rhyme":"ai yu", "tone":"2 1", "sound":"cfe0184.mp3" , "english":"read books"},
{"text":"聽", "lshk":"teng", "full":"teng1", "initial":"t", "rhyme":"eng", "tone":"1", "sound":"cfe0185.mp3" , "english":"hear; listen"},
{"text":"聽音樂", "lshk":"teng jam ngok", "full":"teng1 jam1 ngok6", "initial":"t j ng", "rhyme":"eng am ok", "tone":"1 1 6", "sound":"cfe0186.mp3" , "english":"listen to music"},
{"text":"跳舞", "lshk":"tiu mou", "full":"tiu3 mou5", "initial":"t m", "rhyme":"iu ou", "tone":"3 5", "sound":"cfe0187.mp3" , "english":"dance"},
{"text":"同事", "lshk":"tung si", "full":"tung4 si6", "initial":"t s", "rhyme":"ung i", "tone":"4 6", "sound":"cfe0188.mp3" , "english":"colleague"},
{"text":"華裔", "lshk":"Waa jeoi", "full":"Waa4 jeoi6", "initial":"w j", "rhyme":"aa eoi", "tone":"4 6", "sound":"cfe0189.mp3" , "english":"Chinese descent"},
{"text":"姐姐", "lshk":"ze ze", "full":"ze4 ze1", "initial":"z z", "rhyme":"e e", "tone":"4 1", "sound":"cfe0190.mp3" , "english":"elder sister"},
{"text":"做嘢", "lshk":"zou je", "full":"zou6 je5", "initial":"z j", "rhyme":"ou e", "tone":"6 5", "sound":"cfe0191.mp3" , "english":"work"},
{"text":"兩", "lshk":"loeng", "full":"loeng5", "initial":"l", "rhyme":"oeng", "tone":"5", "sound":"cfe0192.mp3" , "english":"two"},
{"text":"拜拜", "lshk":"baai baai", "full":"baai1 baai3", "initial":"b b", "rhyme":"aai aai", "tone":"1 3", "sound":"cfe0193.mp3" , "english":"bye-bye"},
{"text":"返學", "lshk":"faan hok", "full":"faan1 hok6", "initial":"f h", "rhyme":"aan ok", "tone":"1 6", "sound":"cfe0194.mp3" , "english":"to go to school"},
{"text":"㗎", "lshk":"gaa", "full":"gaa3", "initial":"g", "rhyme":"aa", "tone":"3", "sound":"cfe0195.mp3" , "english":"particle - past, factual"},
{"text":"係唔係", "lshk":"hai m hai", "full":"hai6 m4 hai6", "initial":"h 0 h", "rhyme":"ai m ai", "tone":"6 4 6", "sound":"cfe0196.mp3" , "english":"Is it true?"},
{"text":"係呢", "lshk":"hai ne", "full":"hai6 ne1", "initial":"h n", "rhyme":"ai e", "tone":"6 1", "sound":"cfe0197.mp3" , "english":"by the way"},
{"text":"香港人", "lshk":"Hoeng Gong jan", "full":"Hoeng1 Gong2 jan4", "initial":"h g j", "rhyme":"oeng ong an", "tone":"1 2 4", "sound":"cfe0198.mp3" , "english":"Hongkonger"},
{"text":"開會", "lshk":"hoi wui", "full":"hoi1 wui2", "initial":"h w", "rhyme":"oi ui", "tone":"1 2", "sound":"cfe0199.mp3" , "english":"to attend a meeting"},
{"text":"由", "lshk":"jau", "full":"jau4", "initial":"j", "rhyme":"au", "tone":"4", "sound":"cfe0200.mp3" , "english":"from"},
{"text":"游水", "lshk":"jau seoi", "full":"jau4 seoi2", "initial":"j s", "rhyme":"au eoi", "tone":"4 2", "sound":"cfe0201.mp3" , "english":"swim"},
{"text":"有事", "lshk":"jau si", "full":"jau5 si6", "initial":"j s", "rhyme":"au i", "tone":"5 6", "sound":"cfe0202.mp3" , "english":"have something to do"},
{"text":"英國", "lshk":"Jing Gwok", "full":"Jing1 Gwok3", "initial":"j gw", "rhyme":"ing ok", "tone":"1 3", "sound":"cfe0203.mp3" , "english":"United Kingdom"},
{"text":"英國人", "lshk":"Jing Gwok jan", "full":"Jing1 Gwok3 jan4", "initial":"j gw j", "rhyme":"ing ok an", "tone":"1 3 4", "sound":"cfe0204.mp3" , "english":"British"},
{"text":"英文", "lshk":"Jing Man", "full":"Jing1 Man2", "initial":"j m", "rhyme":"ing an", "tone":"1 2", "sound":"cfe0205.mp3" , "english":"English language"},
{"text":"唔好意思", "lshk":"m hou ji si", "full":"m4 hou2 ji3 si1", "initial":"0 h j s", "rhyme":"m ou i i", "tone":"4 2 3 1", "sound":"cfe0206.mp3" , "english":"Sorry!"},
{"text":"乜嘢", "lshk":"mat je", "full":"mat1 je5", "initial":"m j", "rhyme":"at e", "tone":"1 5", "sound":"cfe0207.mp3" , "english":"what"},
{"text":"咩嘢名", "lshk":"me je meng", "full":"me1 je5 meng2", "initial":"m j m", "rhyme":"e e eng", "tone":"1 5 2", "sound":"cfe0208.mp3" , "english":"what name?"},
{"text":"呢", "lshk":"ne", "full":"ne1", "initial":"n", "rhyme":"e", "tone":"1", "sound":"cfe0209.mp3" , "english":"particle - how about"},
{"text":"你貴姓呀", "lshk":"nei gwai sing aa", "full":"nei5 gwai3 sing3 aa3", "initial":"n gw s 0", "rhyme":"ei ai ing aa", "tone":"5 3 3 3", "sound":"cfe0210.mp3" , "english":"What's your surname?"},
{"text":"你呢", "lshk":"nei ne", "full":"nei5 ne1", "initial":"n n", "rhyme":"ei e", "tone":"5 1", "sound":"cfe0211.mp3" , "english":"How about you?"},
{"text":"跑步", "lshk":"paau bou", "full":"paau2 bou6", "initial":"p b", "rhyme":"aau ou", "tone":"2 6", "sound":"cfe0212.mp3" , "english":"running; jogging"},
{"text":"姓", "lshk":"sing", "full":"sing3", "initial":"s", "rhyme":"ing", "tone":"3", "sound":"cfe0213.mp3" , "english":"be surnamed"},
{"text":"少少", "lshk":"siu siu", "full":"siu2 siu2", "initial":"s s", "rhyme":"iu iu", "tone":"2 2", "sound":"cfe0214.mp3" , "english":"a few; a little"},
{"text":"彈琴", "lshk":"taan kam", "full":"taan4 kam4", "initial":"t k", "rhyme":"aan am", "tone":"4 4", "sound":"cfe0215.mp3" , "english":"play piano"},
{"text":"揸車", "lshk":"zaa ce", "full":"zaa1 ce1", "initial":"z c", "rhyme":"aa e", "tone":"1 1", "sound":"cfe0216.mp3" , "english":"drive (a vehicle)"},
{"text":"走", "lshk":"zau", "full":"zau2", "initial":"z", "rhyme":"au", "tone":"2", "sound":"cfe0217.mp3" , "english":"leave"},
{"text":"啫", "lshk":"ze", "full":"ze1", "initial":"z", "rhyme":"e", "tone":"1", "sound":"cfe0218.mp3" , "english":"particle - just"},
{"text":"再見", "lshk":"zoi gin", "full":"zoi3 gin3", "initial":"z g", "rhyme":"oi in", "tone":"3 3", "sound":"cfe0219.mp3" , "english":"goodbye"},
{"text":"中文", "lshk":"Zung Man", "full":"Zung1 Man4", "initial":"z m", "rhyme":"ung an", "tone":"1 4", "sound":"cfe0220.mp3" , "english":"Chinese language"},
{"text":"煮飯", "lshk":"zyu faan", "full":"zyu2 faan6", "initial":"z f", "rhyme":"yu aan", "tone":"2 6", "sound":"cfe0221.mp3" , "english":"cook"},
{"text":"廣東話", "lshk":"Gwong Dung Waa", "full":"Gwong2 Dung1 Waa2", "initial":"gw d w", "rhyme":"ong ung aa", "tone":"2 1 2", "sound":"cfe0222.mp3" , "english":"Cantonese"},
{"text":"識", "lshk":"sik", "full":"sik1", "initial":"s", "rhyme":"ik", "tone":"1", "sound":"cfe0223.mp3" , "english":"to know"},
{"text":"幾點", "lshk":"gei dim", "full":"gei2 dim2", "initial":"g d", "rhyme":"ei im", "tone":"2 2", "sound":"cfe0224.mp3" , "english":"what time"},
{"text":"幾點鐘", "lshk":"gei dim zung", "full":"gei2 dim2 zung1", "initial":"g d z", "rhyme":"ei im ung", "tone":"2 2 1", "sound":"cfe0225.mp3" , "english":"what time"},
{"text":"阿", "lshk":"aa", "full":"aa3", "initial":"0", "rhyme":"aa", "tone":"3", "sound":"cfe0226.mp3" , "english":"name prefix"},
{"text":"百貨公司", "lshk":"baak fo gung si", "full":"baak3 fo3 gung1 si1", "initial":"b f g s", "rhyme":"aak o ung i", "tone":"3 3 1 1", "sound":"cfe0227.mp3" , "english":"department store"},
{"text":"不過", "lshk":"bat gwo", "full":"bat1 gwo3", "initial":"b gw", "rhyme":"at o", "tone":"1 3", "sound":"cfe0228.mp3" , "english":"but, however"},
{"text":"餐廳", "lshk":"caan teng", "full":"caan1 teng1", "initial":"c t", "rhyme":"aan eng", "tone":"1 1", "sound":"cfe0229.mp3" , "english":"restaurant"},
{"text":"診所", "lshk":"can so", "full":"can2 so2", "initial":"c s", "rhyme":"an o", "tone":"2 2", "sound":"cfe0230.mp3" , "english":"clinic"},
{"text":"從來唔", "lshk":"cung loi m", "full":"cung4 loi4 m4", "initial":"c l 0", "rhyme":"ung oi m", "tone":"4 4 4", "sound":"cfe0231.mp3" , "english":"never"},
{"text":"廚師", "lshk":"cyu si", "full":"cyu4 si1", "initial":"c s", "rhyme":"yu i", "tone":"4 1", "sound":"cfe0232.mp3" , "english":"cook; a chef"},
{"text":"家庭主婦", "lshk":"gaa ting zyu fu", "full":"gaa1 ting4 zyu2 fu5", "initial":"g t z f", "rhyme":"aa ing yu u", "tone":"1 4 2 5", "sound":"cfe0233.mp3" , "english":"housewife"},
{"text":"間中", "lshk":"gaan zung", "full":"gaan3 zung1", "initial":"g z", "rhyme":"aan ung", "tone":"3 1", "sound":"cfe0234.mp3" , "english":"occasionally"},
{"text":"教", "lshk":"gaau", "full":"gaau3", "initial":"g", "rhyme":"aau", "tone":"3", "sound":"cfe0235.mp3" , "english":"teach"},
{"text":"教練", "lshk":"gaau lin", "full":"gaau3 lin6", "initial":"g l", "rhyme":"aau in", "tone":"3 6", "sound":"cfe0236.mp3" , "english":"coach; instructor"},
{"text":"教授", "lshk":"gaau sau", "full":"gaau3 sau6", "initial":"g s", "rhyme":"aau au", "tone":"3 6", "sound":"cfe0237.mp3" , "english":"professor"},
{"text":"經理", "lshk":"ging lei", "full":"ging1 lei5", "initial":"g l", "rhyme":"ing ei", "tone":"1 5", "sound":"cfe0238.mp3" , "english":"manager"},
{"text":"經常", "lshk":"ging soeng", "full":"ging1 soeng4", "initial":"g s", "rhyme":"ing oeng", "tone":"1 4", "sound":"cfe0239.mp3" , "english":"always; often"},
{"text":"警察", "lshk":"ging caat", "full":"ging2 caat3", "initial":"g c", "rhyme":"ing aat", "tone":"2 3", "sound":"cfe0240.mp3" , "english":"police"},
{"text":"歌手", "lshk":"go sau", "full":"go1 sau2", "initial":"g s", "rhyme":"o au", "tone":"1 2", "sound":"cfe0241.mp3" , "english":"singer"},
{"text":"講", "lshk":"gong", "full":"gong2", "initial":"g", "rhyme":"ong", "tone":"2", "sound":"cfe0242.mp3" , "english":"speak; talk"},
{"text":"工廠", "lshk":"gung cong", "full":"gung1 cong2", "initial":"g c", "rhyme":"ung ong", "tone":"1 2", "sound":"cfe0243.mp3" , "english":"factory"},
{"text":"工人", "lshk":"gung jan", "full":"gung1 jan4", "initial":"g j", "rhyme":"ung an", "tone":"1 4", "sound":"cfe0244.mp3" , "english":"worker; servant"},
{"text":"公務員", "lshk":"gung mou jyun", "full":"gung1 mou6 jyun4", "initial":"g m j", "rhyme":"ung ou yun", "tone":"1 6 4", "sound":"cfe0245.mp3" , "english":"civil servant"},
{"text":"公司", "lshk":"gung si", "full":"gung1 si1", "initial":"g s", "rhyme":"ung i", "tone":"1 1", "sound":"cfe0246.mp3" , "english":"company; firm"},
{"text":"廣東人", "lshk":"Gwong Dung jan", "full":"Gwong2 Dung1 jan4", "initial":"gw d j", "rhyme":"ong ung an", "tone":"2 1 4", "sound":"cfe0247.mp3" , "english":"Cantonese people"},
{"text":"學", "lshk":"hok", "full":"hok6", "initial":"h", "rhyme":"ok", "tone":"6", "sound":"cfe0248.mp3" , "english":"learn; study"},
{"text":"學院", "lshk":"hok jyun", "full":"hok6 jyun2", "initial":"h j", "rhyme":"ok yun", "tone":"6 2", "sound":"cfe0249.mp3" , "english":"college; faculty"},
{"text":"好少", "lshk":"hou siu", "full":"hou2 siu2", "initial":"h s", "rhyme":"ou iu", "tone":"2 2", "sound":"cfe0250.mp3" , "english":"rarely;seldom"},
{"text":"一齊", "lshk":"jat cai", "full":"jat1 cai4", "initial":"j c", "rhyme":"at ai", "tone":"1 4", "sound":"cfe0251.mp3" , "english":"together"},
{"text":"有時", "lshk":"jau si", "full":"jau5 si4", "initial":"j s", "rhyme":"au i", "tone":"5 4", "sound":"cfe0252.mp3" , "english":"sometimes"},
{"text":"醫院", "lshk":"ji jyun", "full":"ji1 jyun2", "initial":"j j", "rhyme":"i yun", "tone":"1 2", "sound":"cfe0253.mp3" , "english":"hospital"},
{"text":"醫生", "lshk":"ji sang", "full":"ji1 sang1", "initial":"j s", "rhyme":"i ang", "tone":"1 1", "sound":"cfe0254.mp3" , "english":"medical doctor"},
{"text":"演員", "lshk":"jin jyun", "full":"jin2 jyun4", "initial":"j j", "rhyme":"in yun", "tone":"2 4", "sound":"cfe0255.mp3" , "english":"actor"},
{"text":"律師", "lshk":"leot si", "full":"leot6 si1", "initial":"l s", "rhyme":"eot i", "tone":"6 1", "sound":"cfe0256.mp3" , "english":"lawyer"},
{"text":"練習", "lshk":"lin zaap", "full":"lin6 zaap6", "initial":"l z", "rhyme":"in aap", "tone":"6 6", "sound":"cfe0257.mp3" , "english":"to practice"},
{"text":"男朋友", "lshk":"naam pang jau", "full":"naam4 pang4 jau5", "initial":"n p j", "rhyme":"aam ang au", "tone":"4 4 5", "sound":"cfe0258.mp3" , "english":"boyfriend"},
{"text":"女演員", "lshk":"neoi jin jyun", "full":"neoi5 jin2 jyun4", "initial":"n j j", "rhyme":"eoi in yun", "tone":"5 2 4", "sound":"cfe0259.mp3" , "english":"actress"},
{"text":"社工", "lshk":"se gung", "full":"se5 gung1", "initial":"s g", "rhyme":"e ung", "tone":"5 1", "sound":"cfe0260.mp3" , "english":"social worker"},
{"text":"時時", "lshk":"si si", "full":"si4 si4", "initial":"s s", "rhyme":"i i", "tone":"4 4", "sound":"cfe0261.mp3" , "english":"always; often"},
{"text":"侍應", "lshk":"si jing", "full":"si6 jing3", "initial":"s j", "rhyme":"i ing", "tone":"6 3", "sound":"cfe0262.mp3" , "english":"waiter; waitress"},
{"text":"消防員", "lshk":"siu fong jyun", "full":"siu1 fong4 jyun4", "initial":"s f j", "rhyme":"iu ong yun", "tone":"1 4 4", "sound":"cfe0263.mp3" , "english":"fireman"},
{"text":"位", "lshk":"wai", "full":"wai2", "initial":"w", "rhyme":"ai", "tone":"2", "sound":"cfe0264.mp3" , "english":"MW - person"},
{"text":"護士", "lshk":"wu si", "full":"wu6 si6", "initial":"w s", "rhyme":"u i", "tone":"6 6", "sound":"cfe0265.mp3" , "english":"nurse"},
{"text":"會計師", "lshk":"wui gai si", "full":"wui6 gai3 si1", "initial":"w g s", "rhyme":"ui ai i", "tone":"6 3 1", "sound":"cfe0266.mp3" , "english":"accountant"},
{"text":"酒樓", "lshk":"zau lau", "full":"zau2 lau4", "initial":"z l", "rhyme":"au au", "tone":"2 4", "sound":"cfe0267.mp3" , "english":"Chinese restaurant"},
{"text":"政府部門", "lshk":"zing fu bou mun", "full":"zing3 fu2 bou6 mun4", "initial":"z f b m", "rhyme":"ing u ou un", "tone":"3 2 6 4", "sound":"cfe0268.mp3" , "english":"government departments"},
{"text":"中醫", "lshk":"zung ji", "full":"zung1 ji1", "initial":"z j", "rhyme":"ung i", "tone":"1 1", "sound":"cfe0269.mp3" , "english":"Chinese med doctor"},
{"text":"鍾意", "lshk":"zung ji", "full":"zung1 ji3", "initial":"z j", "rhyme":"ung i", "tone":"1 3", "sound":"cfe0270.mp3" , "english":"to like, be fond of"},
{"text":"八月", "lshk":"baat jyut", "full":"baat3 jyut6", "initial":"b j", "rhyme":"aat yut", "tone":"3 6", "sound":"cfe0271.mp3" , "english":"August"},
{"text":"報紙", "lshk":"bou zi", "full":"bou3 zi2", "initial":"b z", "rhyme":"ou i", "tone":"3 2", "sound":"cfe0272.mp3" , "english":"newpapers"},
{"text":"噚日", "lshk":"cam jat", "full":"cam4 jat6", "initial":"c j", "rhyme":"am at", "tone":"4 6", "sound":"cfe0273.mp3" , "english":"yesterday"},
{"text":"七月", "lshk":"cat jyut", "full":"cat1 jyut6", "initial":"c j", "rhyme":"at yut", "tone":"1 6", "sound":"cfe0274.mp3" , "english":"July"},
{"text":"出年", "lshk":"ceot nin", "full":"ceot1 nin2", "initial":"c n", "rhyme":"eot in", "tone":"1 2", "sound":"cfe0275.mp3" , "english":"next year"},
{"text":"前年", "lshk":"cin nin", "full":"cin4 nin2", "initial":"c n", "rhyme":"in in", "tone":"4 2", "sound":"cfe0276.mp3" , "english":"the year before last"},
{"text":"前日", "lshk":"cin jat", "full":"cin4 jat6", "initial":"c j", "rhyme":"in at", "tone":"4 6", "sound":"cfe0277.mp3" , "english":"the day before yesterday"},
{"text":"沖涼", "lshk":"cung loeng", "full":"cung1 loeng4", "initial":"c l", "rhyme":"ung oeng", "tone":"1 4", "sound":"cfe0278.mp3" , "english":"take a bath or shower"},
{"text":"打波", "lshk":"daa bo", "full":"daa2 bo1", "initial":"d b", "rhyme":"aa o", "tone":"2 1", "sound":"cfe0279.mp3" , "english":"play ball games"},
{"text":"得閒", "lshk":"dak haan", "full":"dak1 haan4", "initial":"d h", "rhyme":"ak aan", "tone":"1 4", "sound":"cfe0280.mp3" , "english":"have free time; not busy"},
{"text":"都", "lshk":"dou", "full":"dou1", "initial":"d", "rhyme":"ou", "tone":"1", "sound":"cfe0281.mp3" , "english":"also; too; all"},
{"text":"到", "lshk":"dou", "full":"dou3", "initial":"d", "rhyme":"ou", "tone":"3", "sound":"cfe0282.mp3" , "english":"until; to"},
{"text":"讀大學", "lshk":"duk daai hok", "full":"duk6 daai6 hok6", "initial":"d d h", "rhyme":"uk aai ok", "tone":"6 6 6", "sound":"cfe0283.mp3" , "english":"go to university"},
{"text":"返工", "lshk":"faan gung", "full":"faan1 gung1", "initial":"f g", "rhyme":"aan ung", "tone":"1 1", "sound":"cfe0284.mp3" , "english":"go to work"},
{"text":"瞓覺", "lshk":"fan gaau", "full":"fan3 gaau3", "initial":"f g", "rhyme":"an aau", "tone":"3 3", "sound":"cfe0285.mp3" , "english":"sleep"},
{"text":"今個星期", "lshk":"gam go sing kei", "full":"gam1 go3 sing1 kei4", "initial":"g g s k", "rhyme":"am o ing ei", "tone":"1 3 1 4", "sound":"cfe0286.mp3" , "english":"this week"},
{"text":"今個月", "lshk":"gam go jyut", "full":"gam1 go3 jyut6", "initial":"g g j", "rhyme":"am o yut", "tone":"1 3 6", "sound":"cfe0287.mp3" , "english":"this month"},
{"text":"今日", "lshk":"gam jat", "full":"gam1 jat6", "initial":"g j", "rhyme":"am at", "tone":"1 6", "sound":"cfe0288.mp3" , "english":"today"},
{"text":"今晚", "lshk":"gam maan", "full":"gam1 maan5", "initial":"g m", "rhyme":"am aan", "tone":"1 5", "sound":"cfe0289.mp3" , "english":"tonight"},
{"text":"緊", "lshk":"gan", "full":"gan2", "initial":"g", "rhyme":"an", "tone":"2", "sound":"cfe0290.mp3" , "english":"-ing as in doing"},
{"text":"九月", "lshk":"gau jyut", "full":"gau2 jyut6", "initial":"g j", "rhyme":"au yut", "tone":"2 6", "sound":"cfe0291.mp3" , "english":"September"},
{"text":"舊年", "lshk":"gau nin", "full":"gau6 nin2", "initial":"g n", "rhyme":"au in", "tone":"6 2", "sound":"cfe0292.mp3" , "english":"last year"},
{"text":"幾", "lshk":"gei", "full":"gei2", "initial":"g", "rhyme":"ei", "tone":"2", "sound":"cfe0293.mp3" , "english":"quite; fairly"},
{"text":"幾時", "lshk":"gei si", "full":"gei2 si4", "initial":"g s", "rhyme":"ei i", "tone":"2 4", "sound":"cfe0294.mp3" , "english":"when; at what time"},
{"text":"過獎", "lshk":"gwo zoeng", "full":"gwo3 zoeng2", "initial":"gw z", "rhyme":"o oeng", "tone":"3 2", "sound":"cfe0295.mp3" , "english":"you flatter me"},
{"text":"下個月", "lshk":"haa go jyut", "full":"haa6 go3 jyut6", "initial":"h g j", "rhyme":"aa o yut", "tone":"6 3 6", "sound":"cfe0296.mp3" , "english":"next month"},
{"text":"下個星期", "lshk":"haa go sing kei", "full":"haa6 go3 sing1 kei4", "initial":"h g s k", "rhyme":"aa o ing ei", "tone":"6 3 1 4", "sound":"cfe0297.mp3" , "english":"next week"},
{"text":"後日", "lshk":"hau jat", "full":"hau6 jat6", "initial":"h j", "rhyme":"au at", "tone":"6 6", "sound":"cfe0298.mp3" , "english":"the day after tomorrow"},
{"text":"後年", "lshk":"hau nin", "full":"hau6 nin2", "initial":"h n", "rhyme":"au in", "tone":"6 2", "sound":"cfe0299.mp3" , "english":"the year after next"},
{"text":"起身", "lshk":"hei san", "full":"hei2 san1", "initial":"h s", "rhyme":"ei an", "tone":"2 1", "sound":"cfe0300.mp3" , "english":"get up"},
{"text":"一月", "lshk":"jat jyut", "full":"jat1 jyut6", "initial":"j j", "rhyme":"at yut", "tone":"1 6", "sound":"cfe0301.mp3" , "english":"January"},
{"text":"二月", "lshk":"ji jyut", "full":"ji6 jyut6", "initial":"j j", "rhyme":"i yut", "tone":"6 6", "sound":"cfe0302.mp3" , "english":"February"},
{"text":"傾電話", "lshk":"king din waa", "full":"king1 din6 waa2", "initial":"k d w", "rhyme":"ing in aa", "tone":"1 6 2", "sound":"cfe0303.mp3" , "english":"chat on the phone"},
{"text":"傾偈", "lshk":"king gai", "full":"king1 gai2", "initial":"k g", "rhyme":"ing ai", "tone":"1 2", "sound":"cfe0304.mp3" , "english":"chat"},
{"text":"律師樓", "lshk":"leot si lau", "full":"leot6 si1 lau4", "initial":"l s l", "rhyme":"eot i au", "tone":"6 1 4", "sound":"cfe0305.mp3" , "english":"law firm"},
{"text":"六月", "lshk":"luk jyut", "full":"luk6 jyut6", "initial":"l j", "rhyme":"uk yut", "tone":"6 6", "sound":"cfe0306.mp3" , "english":"June"},
{"text":"唔係幾", "lshk":"m hai gei", "full":"m4 hai6 gei2", "initial":"0 h g", "rhyme":"m ai ei", "tone":"4 6 2", "sound":"cfe0307.mp3" , "english":"not quite"},
{"text":"唔使", "lshk":"m sai", "full":"m4 sai2", "initial":"0 s", "rhyme":"m ai", "tone":"4 2", "sound":"cfe0308.mp3" , "english":"no need"},
{"text":"麻麻哋", "lshk":"maa maa dei", "full":"maa4 maa2 dei2", "initial":"m m d", "rhyme":"aa aa ei", "tone":"4 2 2", "sound":"cfe0309.mp3" , "english":"so-so"},
{"text":"買嘢", "lshk":"maai je", "full":"maai5 je5", "initial":"m j", "rhyme":"aai e", "tone":"5 5", "sound":"cfe0310.mp3" , "english":"do shopping; buy sth"},
{"text":"乜嘢公司", "lshk":"mat je gung si", "full":"mat1 je5 gung1 si1", "initial":"m j g s", "rhyme":"at e ung i", "tone":"1 5 1 1", "sound":"cfe0311.mp3" , "english":"what kind of company"},
{"text":"忙", "lshk":"mong", "full":"mong4", "initial":"m", "rhyme":"ong", "tone":"4", "sound":"cfe0312.mp3" , "english":"busy"},
{"text":"五月", "lshk":"ng jyut", "full":"ng5 jyut6", "initial":"0 j", "rhyme":"ng yut", "tone":"5 6", "sound":"cfe0313.mp3" , "english":"May"},
{"text":"呢個月", "lshk":"ni go jyut", "full":"ni1 go3 jyut6", "initial":"n g j", "rhyme":"i o yut", "tone":"1 3 6", "sound":"cfe0314.mp3" , "english":"this month"},
{"text":"呢個星期", "lshk":"ni go sing kei", "full":"ni1 go3 sing1 kei4", "initial":"n g s k", "rhyme":"i o ing ei", "tone":"1 3 1 4", "sound":"cfe0315.mp3" , "english":"this week"},
{"text":"年", "lshk":"nin", "full":"nin4", "initial":"n", "rhyme":"in", "tone":"4", "sound":"cfe0316.mp3" , "english":"year"},
{"text":"三月", "lshk":"saam jyut", "full":"saam1 jyut6", "initial":"s j", "rhyme":"aam yut", "tone":"1 6", "sound":"cfe0317.mp3" , "english":"March"},
{"text":"散步", "lshk":"saan bou", "full":"saan3 bou6", "initial":"s b", "rhyme":"aan ou", "tone":"3 6", "sound":"cfe0318.mp3" , "english":"stroll"},
{"text":"十一月", "lshk":"sap jat jyut", "full":"sap6 jat1 jyut6", "initial":"s j j", "rhyme":"ap at yut", "tone":"6 1 6", "sound":"cfe0319.mp3" , "english":"November"},
{"text":"十二月", "lshk":"sap ji jyut", "full":"sap6 ji6 jyut6", "initial":"s j j", "rhyme":"ap i yut", "tone":"6 6 6", "sound":"cfe0320.mp3" , "english":"December"},
{"text":"十月", "lshk":"sap jyut", "full":"sap6 jyut6", "initial":"s j", "rhyme":"ap yut", "tone":"6 6", "sound":"cfe0321.mp3" , "english":"October"},
{"text":"四月", "lshk":"sei jyut", "full":"sei3 jyut6", "initial":"s j", "rhyme":"ei yut", "tone":"3 6", "sound":"cfe0322.mp3" , "english":"April"},
{"text":"食嘢", "lshk":"sik je", "full":"sik6 je5", "initial":"s j", "rhyme":"ik e", "tone":"6 5", "sound":"cfe0323.mp3" , "english":"eat something"},
{"text":"星期", "lshk":"sing kei", "full":"sing1 kei4", "initial":"s k", "rhyme":"ing ei", "tone":"1 4", "sound":"cfe0324.mp3" , "english":"week; day of a week"},
{"text":"星期一", "lshk":"sing kei jat", "full":"sing1 kei4 jat1", "initial":"s k j", "rhyme":"ing ei at", "tone":"1 4 1", "sound":"cfe0325.mp3" , "english":"Monday"},
{"text":"星期日", "lshk":"sing kei jat", "full":"sing1 kei4 jat6", "initial":"s k j", "rhyme":"ing ei at", "tone":"1 4 6", "sound":"cfe0326.mp3" , "english":"Sunday"},
{"text":"星期二", "lshk":"sing kei ji", "full":"sing1 kei4 ji6", "initial":"s k j", "rhyme":"ing ei i", "tone":"1 4 6", "sound":"cfe0327.mp3" , "english":"Tuesday"},
{"text":"星期六", "lshk":"sing kei luk", "full":"sing1 kei4 luk6", "initial":"s k l", "rhyme":"ing ei uk", "tone":"1 4 6", "sound":"cfe0328.mp3" , "english":"Saturday"},
{"text":"星期五", "lshk":"sing kei ng", "full":"sing1 kei4 ng5", "initial":"s k 0", "rhyme":"ing ei ng", "tone":"1 4 5", "sound":"cfe0329.mp3" , "english":"Friday"},
{"text":"星期三", "lshk":"sing kei saam", "full":"sing1 kei4 saam1", "initial":"s k s", "rhyme":"ing ei aam", "tone":"1 4 1", "sound":"cfe0330.mp3" , "english":"Wednesday"},
{"text":"星期四", "lshk":"sing kei sei", "full":"sing1 kei4 sei3", "initial":"s k s", "rhyme":"ing ei ei", "tone":"1 4 3", "sound":"cfe0331.mp3" , "english":"Thursday"},
{"text":"上堂", "lshk":"soeng tong", "full":"soeng5 tong4", "initial":"s t", "rhyme":"oeng ong", "tone":"5 4", "sound":"cfe0332.mp3" , "english":"to attend class"},
{"text":"上個月", "lshk":"soeng go jyut", "full":"soeng6 go3 jyut6", "initial":"s g j", "rhyme":"oeng o yut", "tone":"6 3 6", "sound":"cfe0333.mp3" , "english":"last month"},
{"text":"上個星期", "lshk":"soeng go sing kei", "full":"soeng6 go3 sing1 kei4", "initial":"s g s k", "rhyme":"oeng o ing ei", "tone":"6 3 1 4", "sound":"cfe0334.mp3" , "english":"last week"},
{"text":"探朋友", "lshk":"taam pang jau", "full":"taam3 pang4 jau5", "initial":"t p j", "rhyme":"aam ang au", "tone":"3 4 5", "sound":"cfe0335.mp3" , "english":"visit a friend"},
{"text":"睇報紙", "lshk":"tai bou zi", "full":"tai2 bou3 zi2", "initial":"t b z", "rhyme":"ai ou i", "tone":"2 3 2", "sound":"cfe0336.mp3" , "english":"read newspaper"},
{"text":"踢波", "lshk":"tek bo", "full":"tek3 bo1", "initial":"t b", "rhyme":"ek o", "tone":"3 1", "sound":"cfe0337.mp3" , "english":"play soccer"},
{"text":"聽日", "lshk":"ting jat", "full":"ting1 jat6", "initial":"t j", "rhyme":"ing at", "tone":"1 6", "sound":"cfe0338.mp3" , "english":"tomorrow"},
{"text":"運動", "lshk":"wan dung", "full":"wan6 dung6", "initial":"w d", "rhyme":"an ung", "tone":"6 6", "sound":"cfe0339.mp3" , "english":"workout"},
{"text":"喎", "lshk":"wo", "full":"wo3", "initial":"w", "rhyme":"o", "tone":"3", "sound":"cfe0340.mp3" , "english":"particle - realization"},
{"text":"周末", "lshk":"zau mut", "full":"zau1 mut6", "initial":"z m", "rhyme":"au ut", "tone":"1 6", "sound":"cfe0341.mp3" , "english":"weekend"},
{"text":"最", "lshk":"zeoi", "full":"zeoi3", "initial":"z", "rhyme":"eoi", "tone":"3", "sound":"cfe0342.mp3" , "english":"the most"},
{"text":"至", "lshk":"zi", "full":"zi3", "initial":"z", "rhyme":"i", "tone":"3", "sound":"cfe0343.mp3" , "english":"until; to"},
{"text":"做", "lshk":"zou", "full":"zou6", "initial":"z", "rhyme":"ou", "tone":"6", "sound":"cfe0344.mp3" , "english":"do; work; engage in"},
{"text":"做乜嘢", "lshk":"zou mat je", "full":"zou6 mat1 je5", "initial":"z m j", "rhyme":"ou at e", "tone":"6 1 5", "sound":"cfe0345.mp3" , "english":"What's the matter?"},
{"text":"做事", "lshk":"zou si", "full":"zou6 si6", "initial":"z s", "rhyme":"ou i", "tone":"6 6", "sound":"cfe0346.mp3" , "english":"work"},
{"text":"做運動", "lshk":"zou wan dung", "full":"zou6 wan6 dung6", "initial":"z w d", "rhyme":"ou an ung", "tone":"6 6 6", "sound":"cfe0347.mp3" , "english":"to workout"},
{"text":"月", "lshk":"jyut", "full":"jyut6", "initial":"j", "rhyme":"yut", "tone":"6", "sound":"cfe0348.mp3" , "english":"moon; months"},
{"text":"便利店", "lshk":"bin lei dim", "full":"bin6 lei6 dim3", "initial":"b l d", "rhyme":"in ei im", "tone":"6 6 3", "sound":"cfe0349.mp3" , "english":"convenience store"},
{"text":"茶餐廳", "lshk":"caa caan teng", "full":"caa4 caan1 teng1", "initial":"c c t", "rhyme":"aa aan eng", "tone":"4 1 1", "sound":"cfe0350.mp3" , "english":"Hong Kong style cafe"},
{"text":"請問", "lshk":"ceng man", "full":"ceng2 man6", "initial":"c m", "rhyme":"eng an", "tone":"2 6", "sound":"cfe0351.mp3" , "english":"may I ask"},
{"text":"出面", "lshk":"ceot min", "full":"ceot1 min6", "initial":"c m", "rhyme":"eot in", "tone":"1 6", "sound":"cfe0352.mp3" , "english":"outside"},
{"text":"超級市場", "lshk":"ciu kap si coeng", "full":"ciu1 kap1 si5 coeng4", "initial":"c k s c", "rhyme":"iu ap i oeng", "tone":"1 1 5 4", "sound":"cfe0353.mp3" , "english":"supermarket"},
{"text":"地下", "lshk":"dei haa", "full":"dei6 haa2", "initial":"d h", "rhyme":"ei aa", "tone":"6 2", "sound":"cfe0354.mp3" , "english":"ground floor"},
{"text":"地下", "lshk":"dei haa", "full":"dei6 haa6", "initial":"d h", "rhyme":"ei aa", "tone":"6 6", "sound":"cfe0355.mp3" , "english":"underground"},
{"text":"地鐵", "lshk":"dei tit", "full":"dei6 tit3", "initial":"d t", "rhyme":"ei it", "tone":"6 3", "sound":"cfe0356.mp3" , "english":"underground railway"},
{"text":"地鐵站", "lshk":"dei tit zaam", "full":"dei6 tit3 zaam6", "initial":"d t z", "rhyme":"ei it aam", "tone":"6 3 6", "sound":"cfe0357.mp3" , "english":"MTR station"},
{"text":"對面", "lshk":"deoi min", "full":"deoi3 min6", "initial":"d m", "rhyme":"eoi in", "tone":"3 6", "sound":"cfe0358.mp3" , "english":"opposite (side)"},
{"text":"賭場", "lshk":"dou coeng", "full":"dou2 coeng4", "initial":"d c", "rhyme":"ou oeng", "tone":"2 4", "sound":"cfe0359.mp3" , "english":"casino"},
{"text":"返", "lshk":"faan", "full":"faan1", "initial":"f", "rhyme":"aan", "tone":"1", "sound":"cfe0360.mp3" , "english":"return; go/come back"},
{"text":"附近", "lshk":"fu gan", "full":"fu6 gan6", "initial":"f g", "rhyme":"u an", "tone":"6 6", "sound":"cfe0361.mp3" , "english":"vicinity; nearby"},
{"text":"街市", "lshk":"gaai si", "full":"gaai1 si5", "initial":"g s", "rhyme":"aai i", "tone":"1 5", "sound":"cfe0362.mp3" , "english":"market"},
{"text":"隔離", "lshk":"gaak lei", "full":"gaak3 lei4", "initial":"g l", "rhyme":"aak ei", "tone":"3 4", "sound":"cfe0363.mp3" , "english":"neighboring; next to"},
{"text":"間", "lshk":"gaan", "full":"gaan1", "initial":"g", "rhyme":"aan", "tone":"1", "sound":"cfe0364.mp3" , "english":"MW for buildings etc."},
{"text":"警局", "lshk":"ging guk", "full":"ging2 guk2", "initial":"g g", "rhyme":"ing uk", "tone":"2 2", "sound":"cfe0365.mp3" , "english":"police station"},
{"text":"公園", "lshk":"gung jyun", "full":"gung1 jyun2", "initial":"g j", "rhyme":"ung yun", "tone":"1 2", "sound":"cfe0366.mp3" , "english":"park"},
{"text":"櫃員機", "lshk":"gwai jyun gei", "full":"gwai6 jyun4 gei1", "initial":"gw j g", "rhyme":"ai yun ei", "tone":"6 4 1", "sound":"cfe0367.mp3" , "english":"teller machine"},
{"text":"下面", "lshk":"haa min", "full":"haa6 min6", "initial":"h m", "rhyme":"aa in", "tone":"6 6", "sound":"cfe0368.mp3" , "english":"below; under"},
{"text":"後面", "lshk":"hau min", "full":"hau6 min6", "initial":"h m", "rhyme":"au in", "tone":"6 6", "sound":"cfe0369.mp3" , "english":"at the back"},
{"text":"戲院", "lshk":"hei jyun", "full":"hei3 jyun2", "initial":"h j", "rhyme":"ei yun", "tone":"3 2", "sound":"cfe0370.mp3" , "english":"cinema"},
{"text":"入面", "lshk":"jap min", "full":"jap6 min6", "initial":"j m", "rhyme":"ap in", "tone":"6 6", "sound":"cfe0371.mp3" , "english":"inside; in"},
{"text":"郵局", "lshk":"jau guk", "full":"jau4 guk2", "initial":"j g", "rhyme":"au uk", "tone":"4 2", "sound":"cfe0372.mp3" , "english":"post office"},
{"text":"右面", "lshk":"jau min", "full":"jau6 min6", "initial":"j m", "rhyme":"au in", "tone":"6 6", "sound":"cfe0373.mp3" , "english":"the right side"},
{"text":"二樓", "lshk":"ji lau", "full":"ji6 lau2", "initial":"j l", "rhyme":"i au", "tone":"6 2", "sound":"cfe0374.mp3" , "english":"second floor"},
{"text":"藥房", "lshk":"joek fong", "full":"joek6 fong4", "initial":"j f", "rhyme":"oek ong", "tone":"6 4", "sound":"cfe0375.mp3" , "english":"pharmacy"},
{"text":"樓", "lshk":"lau", "full":"lau2", "initial":"l", "rhyme":"au", "tone":"2", "sound":"cfe0376.mp3" , "english":"floor"},
{"text":"樓下", "lshk":"lau haa", "full":"lau4 haa6", "initial":"l h", "rhyme":"au aa", "tone":"4 6", "sound":"cfe0377.mp3" , "english":"downstairs"},
{"text":"樓上", "lshk":"lau soeng", "full":"lau4 soeng6", "initial":"l s", "rhyme":"au oeng", "tone":"4 6", "sound":"cfe0378.mp3" , "english":"upstairs"},
{"text":"裏面", "lshk":"leoi min", "full":"leoi5 min6", "initial":"l m", "rhyme":"eoi in", "tone":"5 6", "sound":"cfe0379.mp3" , "english":"in; inside"},
{"text":"攞", "lshk":"lo", "full":"lo2", "initial":"l", "rhyme":"o", "tone":"2", "sound":"cfe0380.mp3" , "english":"take; get; fetch"},
{"text":"攞錢", "lshk":"lo cin", "full":"lo2 cin2", "initial":"l c", "rhyme":"o in", "tone":"2 2", "sound":"cfe0381.mp3" , "english":"withdraw money"},
{"text":"唔使多謝", "lshk":"m sai do ze", "full":"m4 sai2 do1 ze6", "initial":"0 s d z", "rhyme":"m ai o e", "tone":"4 2 1 6", "sound":"cfe0382.mp3" , "english":"You're welcome."},
{"text":"唔使客氣", "lshk":"m sai haak hei", "full":"m4 sai2 haak3 hei3", "initial":"0 s h h", "rhyme":"m ai aak ei", "tone":"4 2 3 3", "sound":"cfe0383.mp3" , "english":"Don't mention it."},
{"text":"唔使唔該", "lshk":"m sai m goi", "full":"m4 sai2 m4 goi1", "initial":"0 s 0 g", "rhyme":"m ai m oi", "tone":"4 2 4 1", "sound":"cfe0384.mp3" , "english":"not at all; you're welcome"},
{"text":"馬場", "lshk":"maa coeng", "full":"maa5 coeng4", "initial":"m c", "rhyme":"aa oeng", "tone":"5 4", "sound":"cfe0385.mp3" , "english":"horse racing track"},
{"text":"外面", "lshk":"ngoi min", "full":"ngoi6 min6", "initial":"ng m", "rhyme":"oi in", "tone":"6 6", "sound":"cfe0386.mp3" , "english":"outside"},
{"text":"澳門", "lshk":"Ou Mun", "full":"Ou3 Mun2", "initial":"0 m", "rhyme":"ou un", "tone":"3 2", "sound":"cfe0387.mp3" , "english":"Macau"},
{"text":"旁邊", "lshk":"pong bin", "full":"pong4 bin1", "initial":"p b", "rhyme":"ong in", "tone":"4 1", "sound":"cfe0388.mp3" , "english":"beside; by the side of"},
{"text":"食", "lshk":"sik", "full":"sik6", "initial":"s", "rhyme":"ik", "tone":"6", "sound":"cfe0389.mp3" , "english":"eat"},
{"text":"消防局", "lshk":"siu fong guk", "full":"siu1 fong4 guk2", "initial":"s f g", "rhyme":"iu ong uk", "tone":"1 4 2", "sound":"cfe0390.mp3" , "english":"fire station"},
{"text":"上面", "lshk":"soeng min", "full":"soeng6 min6", "initial":"s m", "rhyme":"oeng in", "tone":"6 6", "sound":"cfe0391.mp3" , "english":"above; on-top"},
{"text":"書局", "lshk":"syu guk", "full":"syu1 guk2", "initial":"s g", "rhyme":"yu uk", "tone":"1 2", "sound":"cfe0392.mp3" , "english":"bookshop"},
{"text":"站", "lshk":"zaam", "full":"zaam6", "initial":"z", "rhyme":"aam", "tone":"6", "sound":"cfe0393.mp3" , "english":"station; a stop"},
{"text":"側邊", "lshk":"zak bin", "full":"zak1 bin1", "initial":"z b", "rhyme":"ak in", "tone":"1 1", "sound":"cfe0394.mp3" , "english":"beside; by the side of"},
{"text":"周圍", "lshk":"zau wai", "full":"zau1 wai4", "initial":"z w", "rhyme":"au ai", "tone":"1 4", "sound":"cfe0395.mp3" , "english":"around; surroundings"},
{"text":"知", "lshk":"zi", "full":"zi1", "initial":"z", "rhyme":"i", "tone":"1", "sound":"cfe0396.mp3" , "english":"to know about"},
{"text":"知道", "lshk":"zi dou", "full":"zi1 dou3", "initial":"z d", "rhyme":"i ou", "tone":"1 3", "sound":"cfe0397.mp3" , "english":"to know about"},
{"text":"自動", "lshk":"zi dung", "full":"zi6 dung6", "initial":"z d", "rhyme":"i ung", "tone":"6 6", "sound":"cfe0398.mp3" , "english":"automatic"},
{"text":"櫃員機", "lshk":"gwai jyun gei", "full":"gwai6 jyun4 gei1", "initial":"gw j g", "rhyme":"ai yun ei", "tone":"6 4 1", "sound":"cfe0399.mp3" , "english":"ATM"},
{"text":"左面", "lshk":"zo min", "full":"zo2 min6", "initial":"z m", "rhyme":"o in", "tone":"2 6", "sound":"cfe0400.mp3" , "english":"the left side"},
{"text":"早餐", "lshk":"zou caan", "full":"zou2 caan1", "initial":"z c", "rhyme":"ou aan", "tone":"2 1", "sound":"cfe0401.mp3" , "english":"breakfast"},
{"text":"早晨", "lshk":"zou san", "full":"zou2 san4", "initial":"z s", "rhyme":"ou an", "tone":"2 4", "sound":"cfe0402.mp3" , "english":"good morning"},
{"text":"做功課", "lshk":"zou gung fo", "full":"zou6 gung1 fo3", "initial":"z g f", "rhyme":"ou ung o", "tone":"6 1 3", "sound":"cfe0403.mp3" , "english":"do homework"},
{"text":"中間", "lshk":"zung gaan", "full":"zung1 gaan1", "initial":"z g", "rhyme":"ung aan", "tone":"1 1", "sound":"cfe0404.mp3" , "english":"in the middle of"},
{"text":"白粥", "lshk":"baak zuk", "full":"baak6 zuk1", "initial":"b z", "rhyme":"aak uk", "tone":"6 1", "sound":"cfe0405.mp3" , "english":"plain rice congee"},
{"text":"飽", "lshk":"baau", "full":"baau2", "initial":"b", "rhyme":"aau", "tone":"2", "sound":"cfe0406.mp3" , "english":"full; not hungry"},
{"text":"邊啲", "lshk":"bin di", "full":"bin1 di1", "initial":"b d", "rhyme":"in i", "tone":"1 1", "sound":"cfe0407.mp3" , "english":"which"},
{"text":"邊間", "lshk":"bin gaan", "full":"bin1 gaan1", "initial":"b g", "rhyme":"in aan", "tone":"1 1", "sound":"cfe0408.mp3" , "english":"which building"},
{"text":"菠蘿包", "lshk":"bo lo baau", "full":"bo1 lo4 baau1", "initial":"b l b", "rhyme":"o o aau", "tone":"1 4 1", "sound":"cfe0409.mp3" , "english":"pineapple bun"},
{"text":"出街", "lshk":"ceot gaai", "full":"ceot1 gaai1", "initial":"c g", "rhyme":"eot aai", "tone":"1 1", "sound":"cfe0410.mp3" , "english":"go out"},
{"text":"腸仔", "lshk":"coeng zai", "full":"coeng2 zai2", "initial":"c z", "rhyme":"oeng ai", "tone":"2 2", "sound":"cfe0411.mp3" , "english":"sausage"},
{"text":"蛋撻", "lshk":"daan taat", "full":"daan6 taat1", "initial":"d t", "rhyme":"aan aat", "tone":"6 1", "sound":"cfe0412.mp3" , "english":"egg tart"},
{"text":"多士", "lshk":"do si", "full":"do1 si2", "initial":"d s", "rhyme":"o i", "tone":"1 2", "sound":"cfe0413.mp3" , "english":"toast"},
{"text":"火腿", "lshk":"fo teoi", "full":"fo2 teoi2", "initial":"f t", "rhyme":"o eoi", "tone":"2 2", "sound":"cfe0414.mp3" , "english":"ham"},
{"text":"叫做", "lshk":"giu zou", "full":"giu3 zou6", "initial":"g z", "rhyme":"iu ou", "tone":"3 6", "sound":"cfe0415.mp3" , "english":"named; known as"},
{"text":"嗰啲", "lshk":"go di", "full":"go2 di1", "initial":"g d", "rhyme":"o i", "tone":"2 1", "sound":"cfe0416.mp3" , "english":"that; those"},
{"text":"嗰個", "lshk":"go go", "full":"go2 go3", "initial":"g g", "rhyme":"o o", "tone":"2 3", "sound":"cfe0417.mp3" , "english":"that person"},
{"text":"覺得", "lshk":"gok dak", "full":"gok3 dak1", "initial":"g d", "rhyme":"ok ak", "tone":"3 1", "sound":"cfe0418.mp3" , "english":"to think; to feel"},
{"text":"港式", "lshk":"Gong sik", "full":"Gong2 sik1", "initial":"g s", "rhyme":"ong ik", "tone":"2 1", "sound":"cfe0419.mp3" , "english":"HK style"},
{"text":"香腸", "lshk":"hoeng coeng", "full":"hoeng1 coeng2", "initial":"h c", "rhyme":"oeng oeng", "tone":"1 2", "sound":"cfe0420.mp3" , "english":"sausage"},
{"text":"香港式", "lshk":"Hoeng Gong sik", "full":"Hoeng1 Gong2 sik1", "initial":"h g s", "rhyme":"oeng ong ik", "tone":"1 2 1", "sound":"cfe0421.mp3" , "english":"Hong Kong style"},
{"text":"好好食", "lshk":"hou hou sik", "full":"hou2 hou2 sik6", "initial":"h h s", "rhyme":"ou ou ik", "tone":"2 2 6", "sound":"cfe0422.mp3" , "english":"very tasty"},
{"text":"好味", "lshk":"hou mei", "full":"hou2 mei6", "initial":"h m", "rhyme":"ou ei", "tone":"2 6", "sound":"cfe0423.mp3" , "english":"tasty"},
{"text":"好食", "lshk":"hou sik", "full":"hou2 sik6", "initial":"h s", "rhyme":"ou ik", "tone":"2 6", "sound":"cfe0424.mp3" , "english":"good to eat; tasty"},
{"text":"嚟嘅", "lshk":"lai ge", "full":"lai4 ge3", "initial":"l g", "rhyme":"ai e", "tone":"4 3", "sound":"cfe0425.mp3" , "english":"particle - explanation"},
{"text":"乜嘢嚟㗎", "lshk":"mat je lai gaa", "full":"mat1 je5 lai4 gaa3", "initial":"m j l g", "rhyme":"at e ai aa", "tone":"1 5 4 3", "sound":"cfe0426.mp3" , "english":"What on earth is this/that?"},
{"text":"麵", "lshk":"min", "full":"min6", "initial":"m", "rhyme":"in", "tone":"6", "sound":"cfe0427.mp3" , "english":"noodles"},
{"text":"麵包", "lshk":"min baau", "full":"min6 baau1", "initial":"m b", "rhyme":"in aau", "tone":"6 1", "sound":"cfe0428.mp3" , "english":"bread"},
{"text":"呢對鞋", "lshk":"ni deoi haai", "full":"ni1 deoi3 haai4", "initial":"n d h", "rhyme":"i eoi aai", "tone":"1 3 4", "sound":"cfe0429.mp3" , "english":"this pair of shoes"},
{"text":"呢啲", "lshk":"ni di", "full":"ni1 di1", "initial":"n d", "rhyme":"i i", "tone":"1 1", "sound":"cfe0430.mp3" , "english":"this; these"},
{"text":"呢個", "lshk":"ni go", "full":"ni1 go3", "initial":"n g", "rhyme":"i o", "tone":"1 3", "sound":"cfe0431.mp3" , "english":"this one"},
{"text":"呢件衫", "lshk":"ni gin saam", "full":"ni1 gin6 saam1", "initial":"n g s", "rhyme":"i in aam", "tone":"1 6 1", "sound":"cfe0432.mp3" , "english":"this piece of clothing; this clothes"},
{"text":"皮蛋", "lshk":"pei daan", "full":"pei4 daan2", "initial":"p d", "rhyme":"ei aan", "tone":"4 2", "sound":"cfe0433.mp3" , "english":"preserved egg"},
{"text":"瘦肉粥", "lshk":"sau juk zuk", "full":"sau3 juk6 zuk1", "initial":"s j z", "rhyme":"au uk uk", "tone":"3 6 1", "sound":"cfe0434.mp3" , "english":"congee with lean pork"},
{"text":"三文治", "lshk":"saam man zi", "full":"saam1 man4 zi6", "initial":"s m z", "rhyme":"aam an i", "tone":"1 4 6", "sound":"cfe0435.mp3" , "english":"sandwiches"},
{"text":"西式", "lshk":"sai sik", "full":"sai1 sik1", "initial":"s s", "rhyme":"ai ik", "tone":"1 1", "sound":"cfe0436.mp3" , "english":"Western style"},
{"text":"瘦肉", "lshk":"sau juk", "full":"sau3 juk6", "initial":"s j", "rhyme":"au uk", "tone":"3 6", "sound":"cfe0437.mp3" , "english":"lean pork; lean meat"},
{"text":"試吓", "lshk":"si haa", "full":"si3 haa5", "initial":"s h", "rhyme":"i aa", "tone":"3 5", "sound":"cfe0438.mp3" , "english":"have a try"},
{"text":"肚餓", "lshk":"tou ngo", "full":"tou5 ngo6", "initial":"t ng", "rhyme":"ou o", "tone":"5 6", "sound":"cfe0439.mp3" , "english":"hungry"},
{"text":"粥", "lshk":"zuk", "full":"zuk1", "initial":"z", "rhyme":"uk", "tone":"1", "sound":"cfe0440.mp3" , "english":"rice congee"},
{"text":"中式", "lshk":"Zung sik", "full":"Zung1 sik1", "initial":"z s", "rhyme":"ung ik", "tone":"1 1", "sound":"cfe0441.mp3" , "english":"Chinese style"},
{"text":"啱", "lshk":"aam", "full":"aam1", "initial":"0", "rhyme":"aam", "tone":"1", "sound":"cfe0442.mp3" , "english":"correct"},
{"text":"杯", "lshk":"bui", "full":"bui1", "initial":"b", "rhyme":"ui", "tone":"1", "sound":"cfe0443.mp3" , "english":"glass, cup, mug"},
{"text":"差", "lshk":"caa", "full":"caa1", "initial":"c", "rhyme":"aa", "tone":"1", "sound":"cfe0444.mp3" , "english":"bad; below standard"},
{"text":"橙汁", "lshk":"caang zap", "full":"caang2 zap1", "initial":"c z", "rhyme":"aang ap", "tone":"2 1", "sound":"cfe0445.mp3" , "english":"orange juice"},
{"text":"醜樣", "lshk":"cau joeng", "full":"cau2 joeng2", "initial":"c j", "rhyme":"au oeng", "tone":"2 2", "sound":"cfe0446.mp3" , "english":"ugly"},
{"text":"臭", "lshk":"cau", "full":"cau3", "initial":"c", "rhyme":"au", "tone":"3", "sound":"cfe0447.mp3" , "english":"smelly, stench"},
{"text":"請", "lshk":"ceng", "full":"ceng2", "initial":"c", "rhyme":"eng", "tone":"2", "sound":"cfe0448.mp3" , "english":"please; invite, treat"},
{"text":"蠢", "lshk":"ceon", "full":"ceon2", "initial":"c", "rhyme":"eon", "tone":"2", "sound":"cfe0449.mp3" , "english":"stupid"},
{"text":"黐線", "lshk":"ci sin", "full":"ci1 sin3", "initial":"c s", "rhyme":"i in", "tone":"1 3", "sound":"cfe0450.mp3" , "english":"crazy"},
{"text":"錯", "lshk":"co", "full":"co3", "initial":"c", "rhyme":"o", "tone":"3", "sound":"cfe0451.mp3" , "english":"wrong"},
{"text":"長", "lshk":"coeng", "full":"coeng4", "initial":"c", "rhyme":"oeng", "tone":"4", "sound":"cfe0452.mp3" , "english":"long"},
{"text":"嘈", "lshk":"cou", "full":"cou4", "initial":"c", "rhyme":"ou", "tone":"4", "sound":"cfe0453.mp3" , "english":"noisy"},
{"text":"聰明", "lshk":"cung ming", "full":"cung1 ming4", "initial":"c m", "rhyme":"ung ing", "tone":"1 4", "sound":"cfe0454.mp3" , "english":"smart, intelligent"},
{"text":"蛋", "lshk":"daan", "full":"daan2", "initial":"d", "rhyme":"aan", "tone":"2", "sound":"cfe0455.mp3" , "english":"egg"},
{"text":"低", "lshk":"dai", "full":"dai1", "initial":"d", "rhyme":"ai", "tone":"1", "sound":"cfe0456.mp3" , "english":"low"},
{"text":"定係", "lshk":"ding hai", "full":"ding6 hai6", "initial":"d h", "rhyme":"ing ai", "tone":"6 6", "sound":"cfe0457.mp3" , "english":"or (in questions)"},
{"text":"碟", "lshk":"dip", "full":"dip6", "initial":"d", "rhyme":"ip", "tone":"6", "sound":"cfe0458.mp3" , "english":"a plate of"},
{"text":"短", "lshk":"dyun", "full":"dyun2", "initial":"d", "rhyme":"yun", "tone":"2", "sound":"cfe0459.mp3" , "english":"short (in length)"},
{"text":"肥", "lshk":"fei", "full":"fei4", "initial":"f", "rhyme":"ei", "tone":"4", "sound":"cfe0460.mp3" , "english":"fat"},
{"text":"方便", "lshk":"fong bin", "full":"fong1 bin6", "initial":"f b", "rhyme":"ong in", "tone":"1 6", "sound":"cfe0461.mp3" , "english":"convenient"},
{"text":"父母", "lshk":"fu mou", "full":"fu6 mou5", "initial":"f m", "rhyme":"u ou", "tone":"6 5", "sound":"cfe0462.mp3" , "english":"parents"},
{"text":"加", "lshk":"gaa", "full":"gaa1", "initial":"g", "rhyme":"aa", "tone":"1", "sound":"cfe0463.mp3" , "english":"add"},
{"text":"咖啡", "lshk":"gaa fe", "full":"gaa3 fe1", "initial":"g f", "rhyme":"aa e", "tone":"3 1", "sound":"cfe0464.mp3" , "english":"coffee"},
{"text":"雞蛋", "lshk":"gai daan", "full":"gai1 daan2", "initial":"g d", "rhyme":"ai aan", "tone":"1 2", "sound":"cfe0465.mp3" , "english":"egg"},
{"text":"緊張", "lshk":"gan zoeng", "full":"gan2 zoeng1", "initial":"g z", "rhyme":"an oeng", "tone":"2 1", "sound":"cfe0466.mp3" , "english":"nervous"},
{"text":"頸渴", "lshk":"geng hot", "full":"geng2 hot3", "initial":"g h", "rhyme":"eng ot", "tone":"2 3", "sound":"cfe0467.mp3" , "english":"thirsty"},
{"text":"高", "lshk":"gou", "full":"gou1", "initial":"g", "rhyme":"ou", "tone":"1", "sound":"cfe0468.mp3" , "english":"tall; high"},
{"text":"乖", "lshk":"gwaai", "full":"gwaai1", "initial":"gw", "rhyme":"aai", "tone":"1", "sound":"cfe0469.mp3" , "english":"good; obedient"},
{"text":"喺度食", "lshk":"hai dou sik", "full":"hai2 dou6 sik6", "initial":"h d s", "rhyme":"ai ou ik", "tone":"2 6 6", "sound":"cfe0470.mp3" , "english":"eat here"},
{"text":"冚唪唥", "lshk":"ham baang laang", "full":"ham6 baang6 laang6", "initial":"h b l", "rhyme":"am aang aang", "tone":"6 6 6", "sound":"cfe0471.mp3" , "english":"all; whole"},
{"text":"後生", "lshk":"hau saang", "full":"hau6 saang1", "initial":"h s", "rhyme":"au aang", "tone":"6 1", "sound":"cfe0472.mp3" , "english":"young"},
{"text":"汽水", "lshk":"hei seoi", "full":"hei3 seoi2", "initial":"h s", "rhyme":"ei eoi", "tone":"3 2", "sound":"cfe0473.mp3" , "english":"soft drinks"},
{"text":"兄弟", "lshk":"hing dai", "full":"hing1 dai6", "initial":"h d", "rhyme":"ing ai", "tone":"1 6", "sound":"cfe0474.mp3" , "english":"brothers"},
{"text":"可樂", "lshk":"ho lok", "full":"ho2 lok6", "initial":"h l", "rhyme":"o ok", "tone":"2 6", "sound":"cfe0475.mp3" , "english":"coke"},
{"text":"開心", "lshk":"hoi sam", "full":"hoi1 sam1", "initial":"h s", "rhyme":"oi am", "tone":"1 1", "sound":"cfe0476.mp3" , "english":"happy"},
{"text":"好飲", "lshk":"hou jam", "full":"hou2 jam2", "initial":"h j", "rhyme":"ou am", "tone":"2 2", "sound":"cfe0477.mp3" , "english":"tasty (for drinks)"},
{"text":"好人", "lshk":"hou jan", "full":"hou2 jan4", "initial":"h j", "rhyme":"ou an", "tone":"2 4", "sound":"cfe0478.mp3" , "english":"kind; nice person"},
{"text":"好玩", "lshk":"hou waan", "full":"hou2 waan2", "initial":"h w", "rhyme":"ou aan", "tone":"2 2", "sound":"cfe0479.mp3" , "english":"fun, interesting"},
{"text":"曳", "lshk":"jai", "full":"jai5", "initial":"j", "rhyme":"ai", "tone":"5", "sound":"cfe0480.mp3" , "english":"naughty"},
{"text":"飲", "lshk":"jam", "full":"jam2", "initial":"j", "rhyme":"am", "tone":"2", "sound":"cfe0481.mp3" , "english":"drink"},
{"text":"一共", "lshk":"jat gung", "full":"jat1 gung6", "initial":"j g", "rhyme":"at ung", "tone":"1 6", "sound":"cfe0482.mp3" , "english":"total, altogether"},
{"text":"一陣", "lshk":"jat zan", "full":"jat1 zan6", "initial":"j z", "rhyme":"at an", "tone":"1 6", "sound":"cfe0483.mp3" , "english":"a little while"},
{"text":"鴛鴦", "lshk":"jin joeng", "full":"jin1 joeng1", "initial":"j j", "rhyme":"in oeng", "tone":"1 1", "sound":"cfe0484.mp3" , "english":"milktea + coffee"},
{"text":"容易", "lshk":"jung ji", "full":"jung4 ji6", "initial":"j j", "rhyme":"ung i", "tone":"4 6", "sound":"cfe0485.mp3" , "english":"easy"},
{"text":"遠", "lshk":"jyun", "full":"jyun5", "initial":"j", "rhyme":"yun", "tone":"5", "sound":"cfe0486.mp3" , "english":"far"},
{"text":"勤力", "lshk":"kan lik", "full":"kan4 lik6", "initial":"k l", "rhyme":"an ik", "tone":"4 6", "sound":"cfe0487.mp3" , "english":"hardworking"},
{"text":"懶", "lshk":"laan", "full":"laan5", "initial":"l", "rhyme":"aan", "tone":"5", "sound":"cfe0488.mp3" , "english":"lazy"},
{"text":"老", "lshk":"lou", "full":"lou5", "initial":"l", "rhyme":"ou", "tone":"5", "sound":"cfe0489.mp3" , "english":"old (not young)"},
{"text":"慢", "lshk":"maan", "full":"maan6", "initial":"m", "rhyme":"aan", "tone":"6", "sound":"cfe0490.mp3" , "english":"slow"},
{"text":"奶", "lshk":"naai", "full":"naai5", "initial":"n", "rhyme":"aai", "tone":"5", "sound":"cfe0491.mp3" , "english":"milk"},
{"text":"奶茶", "lshk":"naai caa", "full":"naai5 caa4", "initial":"n c", "rhyme":"aai aa", "tone":"5 4", "sound":"cfe0492.mp3" , "english":"milk tea"},
{"text":"危險", "lshk":"ngai him", "full":"ngai4 him2", "initial":"ng h", "rhyme":"ai im", "tone":"4 2", "sound":"cfe0493.mp3" , "english":"dangerous"},
{"text":"牛奶", "lshk":"ngau naai", "full":"ngau4 naai5", "initial":"ng n", "rhyme":"au aai", "tone":"4 5", "sound":"cfe0494.mp3" , "english":"milk"},
{"text":"餓", "lshk":"ngo", "full":"ngo6", "initial":"ng", "rhyme":"o", "tone":"6", "sound":"cfe0495.mp3" , "english":"hungry"},
{"text":"拎走", "lshk":"ning zau", "full":"ning1 zau2", "initial":"n z", "rhyme":"ing au", "tone":"1 2", "sound":"cfe0496.mp3" , "english":"take away"},
{"text":"檸檬茶", "lshk":"ning mung caa", "full":"ning4 mung1 caa4", "initial":"n m c", "rhyme":"ing ung aa", "tone":"4 1 4", "sound":"cfe0497.mp3" , "english":"lemon tea"},
{"text":"檸檬水", "lshk":"ning mung seoi", "full":"ning4 mung1 seoi2", "initial":"n m s", "rhyme":"ing ung eoi", "tone":"4 1 2", "sound":"cfe0498.mp3" , "english":"lemonade"},
{"text":"安全", "lshk":"on cyun", "full":"on1 cyun4", "initial":"0 c", "rhyme":"on yun", "tone":"1 4", "sound":"cfe0499.mp3" , "english":"safe"},
{"text":"犀利", "lshk":"sai lei", "full":"sai1 lei6", "initial":"s l", "rhyme":"ai ei", "tone":"1 6", "sound":"cfe0500.mp3" , "english":"terrific, extreme"},
{"text":"辛苦", "lshk":"san fu", "full":"san1 fu2", "initial":"s f", "rhyme":"an u", "tone":"1 2", "sound":"cfe0501.mp3" , "english":"hard;tough"},
{"text":"新嘢", "lshk":"san je", "full":"san1 je5", "initial":"s j", "rhyme":"an e", "tone":"1 5", "sound":"cfe0502.mp3" , "english":"new stuff"},
{"text":"瘦", "lshk":"sau", "full":"sau3", "initial":"s", "rhyme":"au", "tone":"3", "sound":"cfe0503.mp3" , "english":"thin; slim; not fat"},
{"text":"衰", "lshk":"seoi", "full":"seoi1", "initial":"s", "rhyme":"eoi", "tone":"1", "sound":"cfe0504.mp3" , "english":"bad; evil minded"},
{"text":"水皮", "lshk":"seoi pei", "full":"seoi2 pei4", "initial":"s p", "rhyme":"eoi ei", "tone":"2 4", "sound":"cfe0505.mp3" , "english":"not up to standard"},
{"text":"鮮奶", "lshk":"sin naai", "full":"sin1 naai5", "initial":"s n", "rhyme":"in aai", "tone":"1 5", "sound":"cfe0506.mp3" , "english":"fresh milk"},
{"text":"傻", "lshk":"so", "full":"so4", "initial":"s", "rhyme":"o", "tone":"4", "sound":"cfe0507.mp3" , "english":"silly"},
{"text":"舒服", "lshk":"syu fuk", "full":"syu1 fuk6", "initial":"s f", "rhyme":"yu uk", "tone":"1 6", "sound":"cfe0508.mp3" , "english":"comfortable"},
{"text":"糖", "lshk":"tong", "full":"tong4", "initial":"t", "rhyme":"ong", "tone":"4", "sound":"cfe0509.mp3" , "english":"sugar"},
{"text":"齋啡", "lshk":"zaai fe", "full":"zaai1 fe1", "initial":"z f", "rhyme":"aai e", "tone":"1 1", "sound":"cfe0510.mp3" , "english":"black coffee"},
{"text":"正", "lshk":"zeng", "full":"zeng3", "initial":"z", "rhyme":"eng", "tone":"3", "sound":"cfe0511.mp3" , "english":"exact; cool"},
{"text":"姐妹", "lshk":"zi mui", "full":"zi2 mui6", "initial":"z m", "rhyme":"i ui", "tone":"2 6", "sound":"cfe0512.mp3" , "english":"sisters"},
{"text":"即係", "lshk":"zik hai", "full":"zik1 hai6", "initial":"z h", "rhyme":"ik ai", "tone":"1 6", "sound":"cfe0513.mp3" , "english":"it means..."},
{"text":"靜", "lshk":"zing", "full":"zing6", "initial":"z", "rhyme":"ing", "tone":"6", "sound":"cfe0514.mp3" , "english":"quiet"},
{"text":"朱古力", "lshk":"zyu gu lik", "full":"zyu1 gu1 lik1", "initial":"z g l", "rhyme":"yu u ik", "tone":"1 1 1", "sound":"cfe0515.mp3" , "english":"chocolate"},
{"text":"吖", "lshk":"aa", "full":"aa1", "initial":"0", "rhyme":"aa", "tone":"1", "sound":"cfe0516.mp3" , "english":"particle - suggestion"},
{"text":"叉燒包", "lshk":"caa siu baau", "full":"caa1 siu1 baau1", "initial":"c s b", "rhyme":"aa iu aau", "tone":"1 1 1", "sound":"cfe0517.mp3" , "english":"BBQ pork buns"},
{"text":"炒飯", "lshk":"caau faan", "full":"caau2 faan6", "initial":"c f", "rhyme":"aau aan", "tone":"2 6", "sound":"cfe0518.mp3" , "english":"fried rice"},
{"text":"春卷", "lshk":"ceon gyun", "full":"ceon1 gyun2", "initial":"c g", "rhyme":"eon yun", "tone":"1 2", "sound":"cfe0519.mp3" , "english":"spring rolls"},
{"text":"豆腐花", "lshk":"dau fu faa", "full":"dau6 fu6 faa1", "initial":"d f f", "rhyme":"au u aa", "tone":"6 6 1", "sound":"cfe0520.mp3" , "english":"bean curd dessert"},
{"text":"點心", "lshk":"dim sam", "full":"dim2 sam1", "initial":"d s", "rhyme":"im am", "tone":"2 1", "sound":"cfe0521.mp3" , "english":"dim-sum"},
{"text":"多謝先", "lshk":"do ze sin", "full":"do1 ze6 sin1", "initial":"d z s", "rhyme":"o e in", "tone":"1 6 1", "sound":"cfe0522.mp3" , "english":"thank you in advance"},
{"text":"AA制", "lshk":"ei ei zai", "full":"ei1 ei1 zai3", "initial":"0 0 z", "rhyme":"ei ei ai", "tone":"1 1 3", "sound":"cfe0523.mp3" , "english":"go Dutch"},
{"text":"返屋企", "lshk":"faan uk kei", "full":"faan1 uk1 kei2", "initial":"f 0 k", "rhyme":"aan uk ei", "tone":"1 1 2", "sound":"cfe0524.mp3" , "english":"go/come home"},
{"text":"飯", "lshk":"faan", "full":"faan6", "initial":"f", "rhyme":"aan", "tone":"6", "sound":"cfe0525.mp3" , "english":"cooked rice"},
{"text":"交功課", "lshk":"gaau gung fo", "full":"gaau1 gung1 fo3", "initial":"g g f", "rhyme":"aau ung o", "tone":"1 1 3", "sound":"cfe0526.mp3" , "english":"submit homework"},
{"text":"結婚", "lshk":"git fan", "full":"git3 fan1", "initial":"g f", "rhyme":"it an", "tone":"3 1", "sound":"cfe0527.mp3" , "english":"get married"},
{"text":"焗", "lshk":"guk", "full":"guk6", "initial":"g", "rhyme":"uk", "tone":"6", "sound":"cfe0528.mp3" , "english":"baked"},
{"text":"滾水", "lshk":"gwan seoi", "full":"gwan2 seoi2", "initial":"gw s", "rhyme":"an eoi", "tone":"2 2", "sound":"cfe0529.mp3" , "english":"boiling water"},
{"text":"行喇", "lshk":"haang laa", "full":"haang4 laa3", "initial":"h l", "rhyme":"aang aa", "tone":"4 3", "sound":"cfe0530.mp3" , "english":"let's go"},
{"text":"去街", "lshk":"heoi gaai", "full":"heoi3 gaai1", "initial":"h g", "rhyme":"eoi aai", "tone":"3 1", "sound":"cfe0531.mp3" , "english":"go out"},
{"text":"好唔好呀", "lshk":"hou m hou aa", "full":"hou2 m4 hou2 aa3", "initial":"h 0 h 0", "rhyme":"ou m ou aa", "tone":"2 4 2 3", "sound":"cfe0532.mp3" , "english":"Is that good? Is it okay?"},
{"text":"紅豆沙", "lshk":"hung dau saa", "full":"hung4 dau2 saa1", "initial":"h d s", "rhyme":"ung au aa", "tone":"4 2 1", "sound":"cfe0533.mp3" , "english":"red bean sweet soup"},
{"text":"飲嘢", "lshk":"jam je", "full":"jam2 je5", "initial":"j j", "rhyme":"am e", "tone":"2 5", "sound":"cfe0534.mp3" , "english":"have a drink"},
{"text":"飲酒", "lshk":"jam zau", "full":"jam2 zau2", "initial":"j z", "rhyme":"am au", "tone":"2 2", "sound":"cfe0535.mp3" , "english":"have a alcohol drink"},
{"text":"肉", "lshk":"juk", "full":"juk6", "initial":"j", "rhyme":"uk", "tone":"6", "sound":"cfe0536.mp3" , "english":"meat"},
{"text":"埋單", "lshk":"maai daan", "full":"maai4 daan1", "initial":"m d", "rhyme":"aai aan", "tone":"4 1", "sound":"cfe0537.mp3" , "english":"add up the bill; pay"},
{"text":"晚飯", "lshk":"maan faan", "full":"maan5 faan6", "initial":"m f", "rhyme":"aan aan", "tone":"5 6", "sound":"cfe0538.mp3" , "english":"dinner"},
{"text":"未", "lshk":"mei", "full":"mei6", "initial":"m", "rhyme":"ei", "tone":"6", "sound":"cfe0539.mp3" , "english":"not yet"},
{"text":"女", "lshk":"neoi", "full":"neoi2", "initial":"n", "rhyme":"eoi", "tone":"2", "sound":"cfe0540.mp3" , "english":"daughter"},
{"text":"普洱", "lshk":"Pou Lei", "full":"Pou2 Lei2", "initial":"p l", "rhyme":"ou ei", "tone":"2 2", "sound":"cfe0541.mp3" , "english":"Pu'er tea (black tea)"},
{"text":"食晏晝", "lshk":"sik aan zau", "full":"sik6 aan3 zau3", "initial":"s 0 z", "rhyme":"ik aan au", "tone":"6 3 3", "sound":"cfe0542.mp3" , "english":"have a lunch"},
{"text":"先", "lshk":"sin", "full":"sin1", "initial":"s", "rhyme":"in", "tone":"1", "sound":"cfe0543.mp3" , "english":"first; in advance"},
{"text":"添", "lshk":"tim", "full":"tim1", "initial":"t", "rhyme":"im", "tone":"1", "sound":"cfe0544.mp3" , "english":"particle - even"},
{"text":"甜品", "lshk":"tim ban", "full":"tim4 ban2", "initial":"t b", "rhyme":"im an", "tone":"4 2", "sound":"cfe0545.mp3" , "english":"dessert"},
{"text":"或者", "lshk":"waak ze", "full":"waak6 ze2", "initial":"w z", "rhyme":"aak e", "tone":"6 2", "sound":"cfe0546.mp3" , "english":"or (in statements)"},
{"text":"喂", "lshk":"wai", "full":"wai3", "initial":"w", "rhyme":"ai", "tone":"3", "sound":"cfe0547.mp3" , "english":"hello; hey"},
{"text":"壺", "lshk":"wu", "full":"wu4", "initial":"w", "rhyme":"u", "tone":"4", "sound":"cfe0548.mp3" , "english":"a pot of"},
{"text":"炸", "lshk":"zaa", "full":"zaa3", "initial":"z", "rhyme":"aa", "tone":"3", "sound":"cfe0549.mp3" , "english":"deep fry"},
{"text":"齋", "lshk":"zaai", "full":"zaai1", "initial":"z", "rhyme":"aai", "tone":"1", "sound":"cfe0550.mp3" , "english":"vegetarian food"},
{"text":"仔", "lshk":"zai", "full":"zai2", "initial":"z", "rhyme":"ai", "tone":"2", "sound":"cfe0551.mp3" , "english":"son"},
{"text":"真係", "lshk":"zan hai", "full":"zan1 hai6", "initial":"z h", "rhyme":"an ai", "tone":"1 6", "sound":"cfe0552.mp3" , "english":"really; indeed"},
{"text":"蒸", "lshk":"zing", "full":"zing1", "initial":"z", "rhyme":"ing", "tone":"1", "sound":"cfe0553.mp3" , "english":"steam"},
{"text":"咗", "lshk":"zo", "full":"zo2", "initial":"z", "rhyme":"o", "tone":"2", "sound":"cfe0554.mp3" , "english":"(perfective form)"},
{"text":"中國菜", "lshk":"Zung Gwok coi", "full":"Zung1 Gwok3 coi3", "initial":"z gw c", "rhyme":"ung ok oi", "tone":"1 3 3", "sound":"cfe0555.mp3" , "english":"Chinese cuisine"},
{"text":"仲", "lshk":"zung", "full":"zung6", "initial":"z", "rhyme":"ung", "tone":"6", "sound":"cfe0556.mp3" , "english":"still; also"},
{"text":"放工", "lshk":"fong gung", "full":"fong3 gung1", "initial":"f g", "rhyme":"ong ung", "tone":"3 1", "sound":"cfe0557.mp3" , "english":"finish work; off duty"},
];

function Question(mode, id){
  var item = BANK[id];
  this.text = item.text;
  this.lshk = "";

  switch (mode){
    case MODE_REGULAR: this.lshk = item.lshk; break;  
    case MODE_FULL:    this.lshk = item.full; break;  
    case MODE_INITIAL: this.lshk = item.initial; break;  
    case MODE_FINAL:   this.lshk = item.rhyme; break;  
    case MODE_TONE:    this.lshk = item.tone; break;  
  }
  this.english = item.english;
  this.sound = item.sound;
  this.id = this.sound.substr(0,this.sound.length-4);
  
  String.prototype.replaceAll = function(search, replacement) {
    var target = this;
    return target.replace(new RegExp(search, 'g'), replacement);
  };

  this.check = function(mode, attempt) {
    if (mode == MODE_INITIAL || mode == MODE_FINAL) {
      return this.lshk.toLowerCase() == attempt;  
    }
    return this.lshk.replaceAll(" ","").toLowerCase() == attempt.replaceAll(" ","");
  };  
}





