var MAX_Q = 200;

var BANK = [
{"text":"係", "lshk":"hai", "sound":"0001.mp3" , "english":"to be"},
{"text":"有", "lshk":"jau", "sound":"0002.mp3" , "english":"to have"},
{"text":"話", "lshk":"waa", "sound":"0003.mp3" , "english":"to say"},
{"text":"會", "lshk":"wui", "sound":"0004.mp3" , "english":"will"},
{"text":"唔係", "lshk":"m hai", "sound":"0005.mp3" , "english":"not to be"},
{"text":"冇", "lshk":"mou", "sound":"0006.mp3" , "english":"have not"},
{"text":"人", "lshk":"jan", "sound":"0007.mp3" , "english":"man"},
{"text":"去", "lshk":"heoi", "sound":"0008.mp3" , "english":"to go"},
{"text":"覺得", "lshk":"gok dak", "sound":"0009.mp3" , "english":"to feel"},
{"text":"講", "lshk":"gong", "sound":"0010.mp3" , "english":"to speak"},
{"text":"要", "lshk":"jiu", "sound":"0011.mp3" , "english":"to need"},
{"text":"嘢", "lshk":"je", "sound":"0012.mp3" , "english":"thing"},
{"text":"做", "lshk":"zou", "sound":"0013.mp3" , "english":"to do"},
{"text":"好", "lshk":"hou", "sound":"0014.mp3" , "english":"good; very"},
{"text":"知", "lshk":"zi", "sound":"0015.mp3" , "english":"to know"},
{"text":"睇", "lshk":"tai", "sound":"0016.mp3" , "english":"to see; to watch"},
{"text":"多", "lshk":"do", "sound":"0017.mp3" , "english":"many"},
{"text":"來", "lshk":"lai", "sound":"0018.mp3" , "english":"to come"},
{"text":"諗", "lshk":"nam", "sound":"0019.mp3" , "english":"to think"},
{"text":"可以", "lshk":"ho ji", "sound":"0020.mp3" , "english":"can; to be able to"},
{"text":"好似", "lshk":"hou ci", "sound":"0021.mp3" , "english":"to seem; look alike"},
{"text":"買", "lshk":"maai", "sound":"0022.mp3" , "english":"to buy"},
{"text":"俾", "lshk":"bei", "sound":"0023.mp3" , "english":"to give"},
{"text":"譬如", "lshk":"pei jyu", "sound":"0024.mp3" , "english":"for example"},
{"text":"食", "lshk":"sik", "sound":"0025.mp3" , "english":"to eat"},
{"text":"得", "lshk":"dak", "sound":"0026.mp3" , "english":"able; okay"},
{"text":"可能", "lshk":"ho nang", "sound":"0027.mp3" , "english":"perhaps"},
{"text":"係咪", "lshk":"hai mai", "sound":"0028.mp3" , "english":"is or is not"},
{"text":"想", "lshk":"soeng", "sound":"0029.mp3" , "english":"to want (to do something)"},
{"text":"到", "lshk":"dou", "sound":"0030.mp3" , "english":"to arrive; to reach"},
{"text":"大", "lshk":"daai", "sound":"0031.mp3" , "english":"big"},
{"text":"見", "lshk":"gin", "sound":"0032.mp3" , "english":"to see"},
{"text":"揾", "lshk":"wan", "sound":"0033.mp3" , "english":"to find"},
{"text":"返", "lshk":"faan", "sound":"0034.mp3" , "english":"to return"},
{"text":"錢", "lshk":"cin", "sound":"0035.mp3" , "english":"money"},
{"text":"聽", "lshk":"teng", "sound":"0036.mp3" , "english":"to hear; to listen"},
{"text":"應該", "lshk":"jing goi", "sound":"0037.mp3" , "english":"should; probably"},
{"text":"識", "lshk":"sik", "sound":"0038.mp3" , "english":"to know (for knowledge)"},
{"text":"讀", "lshk":"duk", "sound":"0039.mp3" , "english":"to read aloud; to study"},
{"text":"問", "lshk":"man", "sound":"0040.mp3" , "english":"to ask"},
{"text":"有冇", "lshk":"jau mou", "sound":"0041.mp3" , "english":"have or not have"},
{"text":"香港", "lshk":"hoeng gong", "sound":"0042.mp3" , "english":"Hong Kong"},
{"text":"用", "lshk":"jung", "sound":"0043.mp3" , "english":"to use"},
{"text":"鍾意", "lshk":"zung ji", "sound":"0044.mp3" , "english":"to like"},
{"text":"狗", "lshk":"gau", "sound":"0045.mp3" , "english":"dogs"},
{"text":"時候", "lshk":"si hau", "sound":"0046.mp3" , "english":"time, instance"},
{"text":"叫", "lshk":"giu", "sound":"0047.mp3" , "english":"to ask; to shout"},
{"text":"出來", "lshk":"ceot lai", "sound":"0048.mp3" , "english":"out; to come out"},
{"text":"死", "lshk":"sei", "sound":"0049.mp3" , "english":"to die"},
{"text":"攞", "lshk":"lo", "sound":"0050.mp3" , "english":"to take"},
{"text":"玩", "lshk":"waan", "sound":"0051.mp3" , "english":"to play"},
{"text":"唔使", "lshk":"m sai", "sound":"0052.mp3" , "english":"no need"},
{"text":"養", "lshk":"joeng", "sound":"0053.mp3" , "english":"to keep as pet; to cultivate"},
{"text":"驚", "lshk":"geng", "sound":"0054.mp3" , "english":"afraid"},
{"text":"行", "lshk":"haang", "sound":"0055.mp3" , "english":"to walk"},
{"text":"車", "lshk":"ce", "sound":"0056.mp3" , "english":"cars, vehicles"},
{"text":"出", "lshk":"ceot", "sound":"0057.mp3" , "english":"out"},
{"text":"嚟", "lshk":"lai", "sound":"0058.mp3" , "english":"come"},
{"text":"走", "lshk":"zau", "sound":"0059.mp3" , "english":"to leave"},
{"text":"飲", "lshk":"jam", "sound":"0060.mp3" , "english":"to drink"},
{"text":"問題", "lshk":"man tai", "sound":"0061.mp3" , "english":"problems"},
{"text":"事", "lshk":"si", "sound":"0062.mp3" , "english":"matters"},
{"text":"公司", "lshk":"gung si", "sound":"0063.mp3" , "english":"companies"},
{"text":"幫", "lshk":"bong", "sound":"0064.mp3" , "english":"to help"},
{"text":"開", "lshk":"hoi", "sound":"0065.mp3" , "english":"to open"},
{"text":"唔好", "lshk":"m hou", "sound":"0066.mp3" , "english":"not good; don't"},
{"text":"貴", "lshk":"gwai", "sound":"0067.mp3" , "english":"expensive"},
{"text":"打", "lshk":"daa", "sound":"0068.mp3" , "english":"to hit"},
{"text":"屋企", "lshk":"uk kei", "sound":"0069.mp3" , "english":"home"},
{"text":"英文", "lshk":"jing man", "sound":"0070.mp3" , "english":"English"},
{"text":"賣", "lshk":"maai", "sound":"0071.mp3" , "english":"to sell"},
{"text":"算", "lshk":"syun", "sound":"0072.mp3" , "english":"to calculate"},
{"text":"啱", "lshk":"ngaam", "sound":"0073.mp3" , "english":"correct"},
{"text":"工", "lshk":"gung", "sound":"0074.mp3" , "english":"work, job"},
{"text":"教", "lshk":"gaau", "sound":"0075.mp3" , "english":"to teach"},
{"text":"靚", "lshk":"leng", "sound":"0076.mp3" , "english":"beautiful"},
{"text":"考", "lshk":"haau", "sound":"0077.mp3" , "english":"to exam"},
{"text":"返來", "lshk":"faan lai", "sound":"0078.mp3" , "english":"to return"},
{"text":"寫", "lshk":"se", "sound":"0079.mp3" , "english":"to write"},
{"text":"快", "lshk":"faai", "sound":"0080.mp3" , "english":"quick"},
{"text":"夠", "lshk":"gau", "sound":"0081.mp3" , "english":"enough"},
{"text":"難", "lshk":"naan", "sound":"0082.mp3" , "english":"difficult"},
{"text":"少", "lshk":"siu", "sound":"0083.mp3" , "english":"little"},
{"text":"同學", "lshk":"tung hok", "sound":"0084.mp3" , "english":"classmate"},
{"text":"開心", "lshk":"hoi sam", "sound":"0085.mp3" , "english":"happy"},
{"text":"叫做", "lshk":"giu zou", "sound":"0086.mp3" , "english":"called"},
{"text":"變", "lshk":"bin", "sound":"0087.mp3" , "english":"to change"},
{"text":"樣", "lshk":"joeng", "sound":"0088.mp3" , "english":"face"},
{"text":"知道", "lshk":"zi dou", "sound":"0089.mp3" , "english":"to know"},
{"text":"請", "lshk":"ceng", "sound":"0090.mp3" , "english":"to invite"},
{"text":"時間", "lshk":"si gaan", "sound":"0091.mp3" , "english":"time"},
{"text":"搞", "lshk":"gaau", "sound":"0092.mp3" , "english":"to do"},
{"text":"地方", "lshk":"dei fong", "sound":"0093.mp3" , "english":"place"},
{"text":"高", "lshk":"gou", "sound":"0094.mp3" , "english":"high"},
{"text":"搵", "lshk":"wan", "sound":"0095.mp3" , "english":"to find"},
{"text":"整", "lshk":"zing", "sound":"0096.mp3" , "english":"to make"},
{"text":"月", "lshk":"jyut", "sound":"0097.mp3" , "english":"month; moon"},
{"text":"開始", "lshk":"hoi ci", "sound":"0098.mp3" , "english":"to start"},
{"text":"電話", "lshk":"din waa", "sound":"0099.mp3" , "english":"phone"},
{"text":"入", "lshk":"jap", "sound":"0100.mp3" , "english":"to enter"},
{"text":"揸", "lshk":"zaa", "sound":"0101.mp3" , "english":"to drive"},
{"text":"平", "lshk":"peng", "sound":"0102.mp3" , "english":"flat"},
{"text":"辛苦", "lshk":"san fu", "sound":"0103.mp3" , "english":"tough"},
{"text":"耐", "lshk":"noi", "sound":"0104.mp3" , "english":"long time"},
{"text":"慘", "lshk":"caam", "sound":"0105.mp3" , "english":"miserable"},
{"text":"新", "lshk":"san", "sound":"0106.mp3" , "english":"new"},
{"text":"計", "lshk":"gai", "sound":"0107.mp3" , "english":"to calculate"},
{"text":"機", "lshk":"gei", "sound":"0108.mp3" , "english":"machine"},
{"text":"坐", "lshk":"co", "sound":"0109.mp3" , "english":"to sit"},
{"text":"完", "lshk":"jyun", "sound":"0110.mp3" , "english":"to finish"},
{"text":"落去", "lshk":"lok heoi", "sound":"0111.mp3" , "english":"to go down"},
{"text":"字", "lshk":"zi", "sound":"0112.mp3" , "english":"character"},
{"text":"試", "lshk":"si", "sound":"0113.mp3" , "english":"to try"},
{"text":"等", "lshk":"dang", "sound":"0114.mp3" , "english":"to wait"},
{"text":"戲", "lshk":"hei", "sound":"0115.mp3" , "english":"movie"},
{"text":"學", "lshk":"hok", "sound":"0116.mp3" , "english":"to learn"},
{"text":"冇得", "lshk":"mou dak", "sound":"0117.mp3" , "english":"cannot"},
{"text":"學校", "lshk":"hok haau", "sound":"0118.mp3" , "english":"school"},
{"text":"書", "lshk":"syu", "sound":"0119.mp3" , "english":"book"},
{"text":"收", "lshk":"sau", "sound":"0120.mp3" , "english":"to receive"},
{"text":"帶", "lshk":"daai", "sound":"0121.mp3" , "english":"to take"},
{"text":"魚", "lshk":"jyu", "sound":"0122.mp3" , "english":"fish"},
{"text":"正", "lshk":"zeng", "sound":"0123.mp3" , "english":"awesome"},
{"text":"掂", "lshk":"dim", "sound":"0124.mp3" , "english":"great"},
{"text":"明", "lshk":"ming", "sound":"0125.mp3" , "english":"to understand"},
{"text":"揀", "lshk":"gaan", "sound":"0126.mp3" , "english":"to select"},
{"text":"落", "lshk":"lok", "sound":"0127.mp3" , "english":"to put in"},
{"text":"剪", "lshk":"zin", "sound":"0128.mp3" , "english":"to cut"},
{"text":"大佬", "lshk":"daai lou", "sound":"0129.mp3" , "english":"big bro"},
{"text":"朋友", "lshk":"pang jau", "sound":"0130.mp3" , "english":"friend"},
{"text":"過", "lshk":"gwo", "sound":"0131.mp3" , "english":"to pass"},
{"text":"搭", "lshk":"daap", "sound":"0132.mp3" , "english":"to ride"},
{"text":"禮拜", "lshk":"lai baai", "sound":"0133.mp3" , "english":"week"},
{"text":"上", "lshk":"soeng", "sound":"0134.mp3" , "english":"to go up"},
{"text":"唔記得", "lshk":"m gei dak", "sound":"0135.mp3" , "english":"to forget"},
{"text":"望", "lshk":"mong", "sound":"0136.mp3" , "english":"to look at"},
{"text":"日本", "lshk":"jat bun", "sound":"0137.mp3" , "english":"Japan"},
{"text":"放", "lshk":"fong", "sound":"0138.mp3" , "english":"to release"},
{"text":"一樣", "lshk":"jat joeng", "sound":"0139.mp3" , "english":"same"},
{"text":"女仔", "lshk":"neoi zai", "sound":"0140.mp3" , "english":"girl"},
{"text":"影", "lshk":"jing", "sound":"0141.mp3" , "english":"to take picture"},
{"text":"細", "lshk":"sai", "sound":"0142.mp3" , "english":"small"},
{"text":"犀利", "lshk":"sai lei", "sound":"0143.mp3" , "english":"superb"},
{"text":"名", "lshk":"meng", "sound":"0144.mp3" , "english":"name"},
{"text":"唔同", "lshk":"m tung", "sound":"0145.mp3" , "english":"different"},
{"text":"住", "lshk":"zyu", "sound":"0146.mp3" , "english":"to live"},
{"text":"返工", "lshk":"faan gung", "sound":"0147.mp3" , "english":"to go to work"},
{"text":"信", "lshk":"seon", "sound":"0148.mp3" , "english":"letter"},
{"text":"記得", "lshk":"gei dak", "sound":"0149.mp3" , "english":"to remember"},
{"text":"出去", "lshk":"ceot heoi", "sound":"0150.mp3" , "english":"to go out"},
{"text":"對", "lshk":"deoi", "sound":"0151.mp3" , "english":"to"},
{"text":"衰", "lshk":"seoi", "sound":"0152.mp3" , "english":"bad"},
{"text":"飛機", "lshk":"fei gei", "sound":"0153.mp3" , "english":"aeroplane"},
{"text":"起", "lshk":"hei", "sound":"0154.mp3" , "english":"to go up"},
{"text":"傾", "lshk":"king", "sound":"0155.mp3" , "english":"to chat"},
{"text":"遠", "lshk":"jyun", "sound":"0156.mp3" , "english":"far"},
{"text":"有得", "lshk":"jau dak", "sound":"0157.mp3" , "english":"can"},
{"text":"需要", "lshk":"seoi jiu", "sound":"0158.mp3" , "english":"needs"},
{"text":"喺度", "lshk":"hai dou", "sound":"0159.mp3" , "english":"in here"},
{"text":"緊要", "lshk":"gan jiu", "sound":"0160.mp3" , "english":"important"},
{"text":"方面", "lshk":"fong min", "sound":"0161.mp3" , "english":"aspect"},
{"text":"洗", "lshk":"sai", "sound":"0162.mp3" , "english":"to wash"},
{"text":"情況", "lshk":"cing fong", "sound":"0163.mp3" , "english":"circumstance"},
{"text":"學生", "lshk":"hok saang", "sound":"0164.mp3" , "english":"student"},
{"text":"不如", "lshk":"bat jyu", "sound":"0165.mp3" , "english":"why not"},
{"text":"以為", "lshk":"ji wai", "sound":"0166.mp3" , "english":"thought"},
{"text":"開會", "lshk":"hoi wui", "sound":"0167.mp3" , "english":"meeting"},
{"text":"賺", "lshk":"zaan", "sound":"0168.mp3" , "english":"to earn"},
{"text":"讀書", "lshk":"duk syu", "sound":"0169.mp3" , "english":"to study"},
{"text":"細個", "lshk":"sai go", "sound":"0170.mp3" , "english":"small; young"},
{"text":"大陸", "lshk":"daai luk", "sound":"0171.mp3" , "english":"the Mainland"},
{"text":"手", "lshk":"sau", "sound":"0172.mp3" , "english":"hand"},
{"text":"爭", "lshk":"zaang", "sound":"0173.mp3" , "english":"to fight for"},
{"text":"轉", "lshk":"zyun", "sound":"0174.mp3" , "english":"to change"},
{"text":"中文", "lshk":"zung man", "sound":"0175.mp3" , "english":"Chinese"},
{"text":"旅行", "lshk":"leoi hang", "sound":"0176.mp3" , "english":"trip"},
{"text":"仔", "lshk":"zai", "sound":"0177.mp3" , "english":"son"},
{"text":"翻版", "lshk":"faan baan", "sound":"0178.mp3" , "english":"pirated version"},
{"text":"希望", "lshk":"hei mong", "sound":"0179.mp3" , "english":"hope"},
{"text":"陳", "lshk":"can", "sound":"0180.mp3" , "english":"Chan"},
{"text":"鐘", "lshk":"zung", "sound":"0181.mp3" , "english":"clock"},
{"text":"入去", "lshk":"jap heoi", "sound":"0182.mp3" , "english":"to enter"},
{"text":"繼續", "lshk":"gai zuk", "sound":"0183.mp3" , "english":"to continue"},
{"text":"錯", "lshk":"co", "sound":"0184.mp3" , "english":"wrong"},
{"text":"理由", "lshk":"lei jau", "sound":"0185.mp3" , "english":"reason"},
{"text":"凍", "lshk":"dung", "sound":"0186.mp3" , "english":"cold"},
{"text":"A", "lshk":"ei", "sound":"0187.mp3" , "english":"A"},
{"text":"街", "lshk":"gaai", "sound":"0188.mp3" , "english":"street"},
{"text":"拍", "lshk":"paak", "sound":"0189.mp3" , "english":"to pat"},
{"text":"唔咪", "lshk":"m mai", "sound":"0190.mp3" , "english":"is not"},
{"text":"早", "lshk":"zou", "sound":"0191.mp3" , "english":"early"},
{"text":"長", "lshk":"coeng", "sound":"0192.mp3" , "english":"long"},
{"text":"信心", "lshk":"seon sam", "sound":"0193.mp3" , "english":"confidence"},
{"text":"意思", "lshk":"ji si", "sound":"0194.mp3" , "english":"meaning"},
{"text":"辦法", "lshk":"baan faat", "sound":"0195.mp3" , "english":"method"},
{"text":"起身", "lshk":"hei san", "sound":"0196.mp3" , "english":"to wake up"},
{"text":"水", "lshk":"seoi", "sound":"0197.mp3" , "english":"water"},
{"text":"碟", "lshk":"dip", "sound":"0198.mp3" , "english":"plate"},
{"text":"瞓", "lshk":"fan", "sound":"0199.mp3" , "english":"to sleep"},
{"text":"頭", "lshk":"tau", "sound":"0200.mp3" , "english":"head"}
];

function Question(id){
  var item = BANK[id];
  this.text = item.text;
  this.lshk = item.lshk;
  this.english = item.english;
  this.sound = item.sound;
  this.id = this.sound.substr(0,this.sound.length-4);
}

Question.prototype.check = function(attempt) {
  return this.lshk == attempt;
}

