var MAX_Q = 200;

var BANK = [
{"text":"阿Sir", "lshk":"aa soe", "sound":"cfe0001.mp3" , "english":"Sir"},
{"text":"歡迎", "lshk":"fun jing", "sound":"cfe0002.mp3" , "english":"to welcome"},
{"text":"歡迎光臨", "lshk":"fun jing gwong lam", "sound":"cfe0003.mp3" , "english":"welcome for coming"},
{"text":"噉", "lshk":"gam", "sound":"cfe0004.mp3" , "english":"so, well..."},
{"text":"嘅", "lshk":"ge", "sound":"cfe0005.mp3" , "english":"'s"},
{"text":"叫", "lshk":"giu", "sound":"cfe0006.mp3" , "english":"to be called; to call"},
{"text":"香港", "lshk":"Hoeng Gong", "sound":"cfe0007.mp3" , "english":"Hong Kong"},
{"text":"香港大學", "lshk":"Hoeng Gong Daai Hok", "sound":"cfe0008.mp3" , "english":"HKU"},
{"text":"港大", "lshk":"Gong Daai", "sound":"cfe0009.mp3" , "english":"short for HKU"},
{"text":"係", "lshk":"hai", "sound":"cfe0010.mp3" , "english":"is, am, are, was, were"},
{"text":"學校", "lshk":"hok haau", "sound":"cfe0011.mp3" , "english":"school"},
{"text":"學生", "lshk":"hok saang", "sound":"cfe0012.mp3" , "english":"student"},
{"text":"佢哋", "lshk":"keoi dei", "sound":"cfe0013.mp3" , "english":"they, them"},
{"text":"佢嘅", "lshk":"keoi ge", "sound":"cfe0014.mp3" , "english":"his, her, hers"},
{"text":"啦", "lshk":"laa", "sound":"cfe0015.mp3" , "english":"particle - request"},
{"text":"你哋", "lshk":"nei dei", "sound":"cfe0016.mp3" , "english":"you - plural"},
{"text":"你嘅", "lshk":"nei ge", "sound":"cfe0017.mp3" , "english":"your, yours"},
{"text":"你好", "lshk":"nei hou", "sound":"cfe0018.mp3" , "english":"(formal) Hello"},
{"text":"我嘅", "lshk":"ngo ge", "sound":"cfe0019.mp3" , "english":"my; mine"},
{"text":"先生", "lshk":"sin saang", "sound":"cfe0020.mp3" , "english":"Mr.; sir; husband"},
{"text":"小姐", "lshk":"siu ze", "sound":"cfe0021.mp3" , "english":"Miss, young lady"},
{"text":"太太", "lshk":"taai taai", "sound":"cfe0022.mp3" , "english":"Mrs.; wife"},
{"text":"呀", "lshk":"aa", "sound":"cfe0023.mp3" , "english":"particle - question / soften"},
{"text":"亞洲", "lshk":"Aa Zau", "sound":"cfe0024.mp3" , "english":"Asia"},
{"text":"歐洲", "lshk":"Au Zau", "sound":"cfe0025.mp3" , "english":"Europe"},
{"text":"北美洲", "lshk":"Bak Mei Zau", "sound":"cfe0026.mp3" , "english":"North America"},
{"text":"邊度", "lshk":"bin dou", "sound":"cfe0027.mp3" , "english":"where"},
{"text":"出口", "lshk":"ceot hau", "sound":"cfe0028.mp3" , "english":"exit"},
{"text":"大陸", "lshk":"daai luk", "sound":"cfe0029.mp3" , "english":"Mainland China"},
{"text":"地圖", "lshk":"dei tou", "sound":"cfe0030.mp3" , "english":"map"},
{"text":"的士", "lshk":"dik si", "sound":"cfe0031.mp3" , "english":"taxi"},
{"text":"電話", "lshk":"din waa", "sound":"cfe0032.mp3" , "english":"telephone"},
{"text":"快餐店", "lshk":"faai caan dim", "sound":"cfe0033.mp3" , "english":"fast food shop"},
{"text":"非洲", "lshk":"Fei Zau", "sound":"cfe0034.mp3" , "english":"Africa"},
{"text":"九龍", "lshk":"Gau Lung", "sound":"cfe0035.mp3" , "english":"Kowloon"},
{"text":"機場", "lshk":"gei coeng", "sound":"cfe0036.mp3" , "english":"airport"},
{"text":"嗰度", "lshk":"go dou", "sound":"cfe0037.mp3" , "english":"there; over there"},
{"text":"國家", "lshk":"gwok gaa", "sound":"cfe0038.mp3" , "english":"country"},
{"text":"國際", "lshk":"gwok zai", "sound":"cfe0039.mp3" , "english":"international"},
{"text":"喺", "lshk":"hai", "sound":"cfe0040.mp3" , "english":"at; in; on"},
{"text":"去", "lshk":"heoi", "sound":"cfe0041.mp3" , "english":"go"},
{"text":"香港島", "lshk":"Hoeng Gong Dou", "sound":"cfe0042.mp3" , "english":"Hong Kong Island"},
{"text":"入口", "lshk":"jap hau", "sound":"cfe0043.mp3" , "english":"entrance"},
{"text":"而家", "lshk":"ji gaa", "sound":"cfe0044.mp3" , "english":"now"},
{"text":"老師", "lshk":"lou si", "sound":"cfe0045.mp3" , "english":"teacher"},
{"text":"唔該", "lshk":"m goi", "sound":"cfe0046.mp3" , "english":"please; excuse me"},
{"text":"南美洲", "lshk":"Naam Mei Zau", "sound":"cfe0047.mp3" , "english":"South America"},
{"text":"銀行", "lshk":"ngan hong", "sound":"cfe0048.mp3" , "english":"bank"},
{"text":"我哋", "lshk":"ngo dei", "sound":"cfe0049.mp3" , "english":"we, us"},
{"text":"呢度", "lshk":"ni dou", "sound":"cfe0050.mp3" , "english":"here"},
{"text":"澳洲", "lshk":"Ou Zau", "sound":"cfe0051.mp3" , "english":"Australia"},
{"text":"洗手間", "lshk":"sai sau gaan", "sound":"cfe0052.mp3" , "english":"toilet; washroom"},
{"text":"中東", "lshk":"Zung Dung", "sound":"cfe0053.mp3" , "english":"Middle East"},
{"text":"中國", "lshk":"Zung Gwok", "sound":"cfe0054.mp3" , "english":"China"},
{"text":"中美洲", "lshk":"Zung Mei Zau", "sound":"cfe0055.mp3" , "english":"Middle America"},
{"text":"中環", "lshk":"Zung Waan", "sound":"cfe0056.mp3" , "english":"Central"},
{"text":"停車場", "lshk":"ting ce coeng", "sound":"cfe0057.mp3" , "english":"carpark"},
{"text":"辦公室", "lshk":"baan gung sat", "sound":"cfe0058.mp3" , "english":"office"},
{"text":"啤酒", "lshk":"be zau", "sound":"cfe0059.mp3" , "english":"beer"},
{"text":"叉", "lshk":"caa", "sound":"cfe0060.mp3" , "english":"fork"},
{"text":"厠所", "lshk":"ci so", "sound":"cfe0061.mp3" , "english":"washroom; toilet"},
{"text":"簽名", "lshk":"cim meng", "sound":"cfe0062.mp3" , "english":"to sign"},
{"text":"前面", "lshk":"cin min", "sound":"cfe0063.mp3" , "english":"in front; ahead"},
{"text":"前門", "lshk":"cin mun", "sound":"cfe0064.mp3" , "english":"front door"},
{"text":"坐", "lshk":"co", "sound":"cfe0065.mp3" , "english":"sit"},
{"text":"沖涼房", "lshk":"cung loeng fong", "sound":"cfe0066.mp3" , "english":"bathroom"},
{"text":"廚房", "lshk":"cyu fong", "sound":"cfe0067.mp3" , "english":"kitchen"},
{"text":"大", "lshk":"daai", "sound":"cfe0068.mp3" , "english":"big"},
{"text":"大學", "lshk":"daai hok", "sound":"cfe0069.mp3" , "english":"university"},
{"text":"電梯", "lshk":"din tai", "sound":"cfe0070.mp3" , "english":"escalator;elevator"},
{"text":"電話號碼", "lshk":"din waa hou maa", "sound":"cfe0071.mp3" , "english":"telephone number"},
{"text":"飯廳", "lshk":"faan teng", "sound":"cfe0072.mp3" , "english":"dining room"},
{"text":"房", "lshk":"fong", "sound":"cfe0073.mp3" , "english":"room"},
{"text":"舊", "lshk":"gau", "sound":"cfe0074.mp3" , "english":"old (not new)"},
{"text":"幾多", "lshk":"gei do", "sound":"cfe0075.mp3" , "english":"how many; how much"},
{"text":"幾多號", "lshk":"gei do hou", "sound":"cfe0076.mp3" , "english":"what number"},
{"text":"客廳", "lshk":"haak teng", "sound":"cfe0077.mp3" , "english":"living room"},
{"text":"後門", "lshk":"hau mun", "sound":"cfe0078.mp3" , "english":"back door"},
{"text":"好呃", "lshk":"hou aak", "sound":"cfe0079.mp3" , "english":"fine, okay"},
{"text":"號", "lshk":"hou", "sound":"cfe0080.mp3" , "english":"number; days of month"},
{"text":"飲茶", "lshk":"jam caa", "sound":"cfe0081.mp3" , "english":"to have tea / dim-sum"},
{"text":"入嚟", "lshk":"jap lei", "sound":"cfe0082.mp3" , "english":"come in"},
{"text":"要", "lshk":"jiu", "sound":"cfe0083.mp3" , "english":"want; need; have to"},
{"text":"喇", "lshk":"laa", "sound":"cfe0084.mp3" , "english":"particle - already"},
{"text":"嚟", "lshk":"lai", "sound":"cfe0085.mp3" , "english":"to come"},
{"text":"留學生", "lshk":"lau hok saang", "sound":"cfe0086.mp3" , "english":"foreign student"},
{"text":"樓梯", "lshk":"lau tai", "sound":"cfe0087.mp3" , "english":"staircase"},
{"text":"𨋢", "lshk":"lip", "sound":"cfe0088.mp3" , "english":"lift, elevator"},
{"text":"新嚟嘅", "lshk":"san lei ge", "sound":"cfe0089.mp3" , "english":"just arrived; newcomer"},
{"text":"睡房", "lshk":"seoi fong", "sound":"cfe0090.mp3" , "english":"bedroom"},
{"text":"司機", "lshk":"si gei", "sound":"cfe0091.mp3" , "english":"driver"},
{"text":"鎖匙", "lshk":"so si", "sound":"cfe0092.mp3" , "english":"key"},
{"text":"想", "lshk":"soeng", "sound":"cfe0093.mp3" , "english":"to want to"},
{"text":"想要", "lshk":"soeng jiu", "sound":"cfe0094.mp3" , "english":"to want (something)"},
{"text":"宿舍", "lshk":"suk se", "sound":"cfe0095.mp3" , "english":"hostel; dormitory"},
{"text":"書房", "lshk":"syu fong", "sound":"cfe0096.mp3" , "english":"study room"},
{"text":"停車", "lshk":"ting ce", "sound":"cfe0097.mp3" , "english":"to stop the car"},
{"text":"圖書館", "lshk":"tou syu gun", "sound":"cfe0098.mp3" , "english":"library"},
{"text":"屋企人", "lshk":"uk kei jan", "sound":"cfe0099.mp3" , "english":"family members"},
{"text":"酒店", "lshk":"zau dim", "sound":"cfe0100.mp3" , "english":"hotel"},
{"text":"中學", "lshk":"zung hok", "sound":"cfe0101.mp3" , "english":"secondary school"},
{"text":"住", "lshk":"zyu", "sound":"cfe0102.mp3" , "english":"live"},
{"text":"朋友", "lshk":"pang jau", "sound":"cfe0103.mp3" , "english":"friend"},
{"text":"好", "lshk":"hou", "sound":"cfe0104.mp3" , "english":"good; fine; very"},
{"text":"細", "lshk":"sai", "sound":"cfe0105.mp3" , "english":"small"},
{"text":"新", "lshk":"san", "sound":"cfe0106.mp3" , "english":"new"},
{"text":"靚", "lshk":"leng", "sound":"cfe0107.mp3" , "english":"good-looking; good quality"},
{"text":"爸爸", "lshk":"baa baa", "sound":"cfe0108.mp3" , "english":"father"},
{"text":"八達通咭", "lshk":"baat daat tung kaat", "sound":"cfe0109.mp3" , "english":"Octopus card"},
{"text":"簽證", "lshk":"cim zing", "sound":"cfe0110.mp3" , "english":"visa"},
{"text":"錢", "lshk":"cin", "sound":"cfe0111.mp3" , "english":"money"},
{"text":"幾錢", "lshk":"gei cin", "sound":"cfe0112.mp3" , "english":"how much"},
{"text":"幾多錢", "lshk":"gei do cin", "sound":"cfe0113.mp3" , "english":"howmuch (money)"},
{"text":"幾多歲", "lshk":"gei do seoi", "sound":"cfe0114.mp3" , "english":"how old"},
{"text":"幾多人", "lshk":"gei do jan", "sound":"cfe0115.mp3" , "english":"How many people"},
{"text":"港幣", "lshk":"Gong Bai", "sound":"cfe0116.mp3" , "english":"HK$"},
{"text":"身份證", "lshk":"san fan zing", "sound":"cfe0117.mp3" , "english":"ID card"},
{"text":"一百蚊", "lshk":"jat baak man", "sound":"cfe0118.mp3" , "english":"one hundred dollars"},
{"text":"一千蚊", "lshk":"jat cin man", "sound":"cfe0119.mp3" , "english":"one thousand dollars"},
{"text":"一啲", "lshk":"jat di", "sound":"cfe0120.mp3" , "english":"some"},
{"text":"一毫", "lshk":"jat hou", "sound":"cfe0121.mp3" , "english":"ten cents"},
{"text":"一蚊", "lshk":"jat man", "sound":"cfe0122.mp3" , "english":"one dollar"},
{"text":"有", "lshk":"jau", "sound":"cfe0123.mp3" , "english":"have; possess"},
{"text":"二十蚊", "lshk":"ji sap man", "sound":"cfe0124.mp3" , "english":"twenty dollars"},
{"text":"兩毫", "lshk":"loeng hou", "sound":"cfe0125.mp3" , "english":"twenty cents"},
{"text":"兩蚊", "lshk":"loeng man", "sound":"cfe0126.mp3" , "english":"two dollars"},
{"text":"媽媽", "lshk":"maa maa", "sound":"cfe0127.mp3" , "english":"mother"},
{"text":"蚊", "lshk":"man", "sound":"cfe0128.mp3" , "english":"dollars"},
{"text":"問題", "lshk":"man tai", "sound":"cfe0129.mp3" , "english":"question; problem"},
{"text":"美金", "lshk":"Mei Gam", "sound":"cfe0130.mp3" , "english":"U.S.Dollars"},
{"text":"冇", "lshk":"mou", "sound":"cfe0131.mp3" , "english":"have not, not to have"},
{"text":"冇問題", "lshk":"mou man tai", "sound":"cfe0132.mp3" , "english":"no problem"},
{"text":"嗱", "lshk":"naa", "sound":"cfe0133.mp3" , "english":"Here it is!"},
{"text":"女朋友", "lshk":"neoi pang jau", "sound":"cfe0134.mp3" , "english":"girlfriend"},
{"text":"五百蚊", "lshk":"ng baak man", "sound":"cfe0135.mp3" , "english":"five hundred dollars"},
{"text":"五毫", "lshk":"ng hou", "sound":"cfe0136.mp3" , "english":"fifty cents"},
{"text":"五蚊", "lshk":"ng man", "sound":"cfe0137.mp3" , "english":"five dollars"},
{"text":"五十蚊", "lshk":"ng sap man", "sound":"cfe0138.mp3" , "english":"fifty dollars"},
{"text":"硬幣", "lshk":"ngaang bai", "sound":"cfe0139.mp3" , "english":"coin"},
{"text":"散銀", "lshk":"saan ngan", "sound":"cfe0140.mp3" , "english":"coins"},
{"text":"十蚊", "lshk":"sap man", "sound":"cfe0141.mp3" , "english":"ten dollars"},
{"text":"手提電話", "lshk":"sau tai din waa", "sound":"cfe0142.mp3" , "english":"mobile phone"},
{"text":"信用咭", "lshk":"seon jung kaat", "sound":"cfe0143.mp3" , "english":"credit card"},
{"text":"同", "lshk":"tung", "sound":"cfe0144.mp3" , "english":"and; with"},
{"text":"護照", "lshk":"wu ziu", "sound":"cfe0145.mp3" , "english":"passport"},
{"text":"換", "lshk":"wun", "sound":"cfe0146.mp3" , "english":"change; exchange"},
{"text":"紙幣", "lshk":"zi bai", "sound":"cfe0147.mp3" , "english":"banknotes"},
{"text":"淨係", "lshk":"zing hai", "sound":"cfe0148.mp3" , "english":"only"},
{"text":"巴黎", "lshk":"Baa Lai", "sound":"cfe0149.mp3" , "english":"Paris"},
{"text":"唱歌", "lshk":"coeng go", "sound":"cfe0150.mp3" , "english":"sing"},
{"text":"唱K", "lshk":"coeng kei", "sound":"cfe0151.mp3" , "english":"sing karaoke"},
{"text":"打麻雀", "lshk":"daa maa zoek", "sound":"cfe0152.mp3" , "english":"play mahjong"},
{"text":"大家", "lshk":"daai gaa", "sound":"cfe0153.mp3" , "english":"all, everybody"},
{"text":"弟弟", "lshk":"dai dai", "sound":"cfe0154.mp3" , "english":"younger brother"},
{"text":"多謝", "lshk":"do ze", "sound":"cfe0155.mp3" , "english":"thank you, many thanks"},
{"text":"讀", "lshk":"duk", "sound":"cfe0156.mp3" , "english":"go to school; study"},
{"text":"讀書", "lshk":"duk syu", "sound":"cfe0157.mp3" , "english":"study; read books"},
{"text":"翻譯", "lshk":"faan jik", "sound":"cfe0158.mp3" , "english":"translation"},
{"text":"交換", "lshk":"gaau wun", "sound":"cfe0159.mp3" , "english":"exchange"},
{"text":"教育", "lshk":"gaau juk", "sound":"cfe0160.mp3" , "english":"education"},
{"text":"今年", "lshk":"gam nin", "sound":"cfe0161.mp3" , "english":"this year"},
{"text":"哥哥", "lshk":"go go", "sound":"cfe0162.mp3" , "english":"elder brother"},
{"text":"行街", "lshk":"haang gaai", "sound":"cfe0163.mp3" , "english":"shopping; walking around"},
{"text":"行山", "lshk":"haang saan", "sound":"cfe0164.mp3" , "english":"hiking"},
{"text":"兄弟姊妹", "lshk":"hing dai zi mui", "sound":"cfe0165.mp3" , "english":"brothers and sisters"},
{"text":"興趣", "lshk":"hing ceoi", "sound":"cfe0166.mp3" , "english":"a hobby; an interest"},
{"text":"音樂", "lshk":"jam ngok", "sound":"cfe0167.mp3" , "english":"music"},
{"text":"人", "lshk":"jan", "sound":"cfe0168.mp3" , "english":"people; person"},
{"text":"英文", "lshk":"Jing Man", "sound":"cfe0169.mp3" , "english":"English language"},
{"text":"影相", "lshk":"jing soeng", "sound":"cfe0170.mp3" , "english":"take photographs"},
{"text":"旅行", "lshk":"leoi hang", "sound":"cfe0171.mp3" , "english":"travel (N) traveling"},
{"text":"老闆", "lshk":"lou baan", "sound":"cfe0172.mp3" , "english":"boss"},
{"text":"乜嘢科", "lshk":"mat je fo", "sound":"cfe0173.mp3" , "english":"what subject?"},
{"text":"乜嘢人", "lshk":"mat je jan", "sound":"cfe0174.mp3" , "english":"what people?"},
{"text":"乜嘢名", "lshk":"mat je meng", "sound":"cfe0175.mp3" , "english":"what name?"},
{"text":"美國", "lshk":"Mei Gwok", "sound":"cfe0176.mp3" , "english":"USA"},
{"text":"美國人", "lshk":"Mei Gwok jan", "sound":"cfe0177.mp3" , "english":"Americans"},
{"text":"妹妹", "lshk":"mui mui", "sound":"cfe0178.mp3" , "english":"younger sister"},
{"text":"紐約", "lshk":"Nau Joek", "sound":"cfe0179.mp3" , "english":"New York"},
{"text":"歲", "lshk":"seoi", "sound":"cfe0180.mp3" , "english":"years old"},
{"text":"食煙", "lshk":"sik jin", "sound":"cfe0181.mp3" , "english":"smoke"},
{"text":"上網", "lshk":"soeng mong", "sound":"cfe0182.mp3" , "english":"to surf the internet"},
{"text":"睇戲", "lshk":"tai hei", "sound":"cfe0183.mp3" , "english":"watchmovies"},
{"text":"睇書", "lshk":"tai syu", "sound":"cfe0184.mp3" , "english":"read books"},
{"text":"聽", "lshk":"teng", "sound":"cfe0185.mp3" , "english":"hear; listen"},
{"text":"聽音樂", "lshk":"teng jam ngok", "sound":"cfe0186.mp3" , "english":"listen to music"},
{"text":"跳舞", "lshk":"tiu mou", "sound":"cfe0187.mp3" , "english":"dance"},
{"text":"同事", "lshk":"tung si", "sound":"cfe0188.mp3" , "english":"colleague"},
{"text":"華裔", "lshk":"Waa jeoi", "sound":"cfe0189.mp3" , "english":"Chinese descent"},
{"text":"姐姐", "lshk":"ze ze", "sound":"cfe0190.mp3" , "english":"elder sister"},
{"text":"做嘢", "lshk":"zou je", "sound":"cfe0191.mp3" , "english":"work"},
{"text":"兩", "lshk":"loeng", "sound":"cfe0192.mp3" , "english":"two"},
{"text":"拜拜", "lshk":"baai baai", "sound":"cfe0193.mp3" , "english":"bye-bye"},
{"text":"返學", "lshk":"faan hok", "sound":"cfe0194.mp3" , "english":"to go to school"},
{"text":"㗎", "lshk":"gaa", "sound":"cfe0195.mp3" , "english":"particle - past, factual"},
{"text":"係唔係", "lshk":"hai m hai", "sound":"cfe0196.mp3" , "english":"Is it true?"},
{"text":"係呢", "lshk":"hai ne", "sound":"cfe0197.mp3" , "english":"by the way"},
{"text":"香港人", "lshk":"Hoeng Gong jan", "sound":"cfe0198.mp3" , "english":"Hongkonger"},
{"text":"開會", "lshk":"hoi wui", "sound":"cfe0199.mp3" , "english":"to attend a meeting"},
{"text":"由", "lshk":"jau", "sound":"cfe0200.mp3" , "english":"from"},
{"text":"游水", "lshk":"jau seoi", "sound":"cfe0201.mp3" , "english":"swim"},
{"text":"有事", "lshk":"jau si", "sound":"cfe0202.mp3" , "english":"have something to do"},
{"text":"英國", "lshk":"Jing Gwok", "sound":"cfe0203.mp3" , "english":"United Kingdom"},
{"text":"英國人", "lshk":"Jing Gwok jan", "sound":"cfe0204.mp3" , "english":"British"},
{"text":"英文", "lshk":"Jing Man", "sound":"cfe0205.mp3" , "english":"English language"},
{"text":"唔好意思", "lshk":"m hou ji si", "sound":"cfe0206.mp3" , "english":"Sorry!"},
{"text":"乜嘢", "lshk":"mat je", "sound":"cfe0207.mp3" , "english":"what"},
{"text":"咩嘢名", "lshk":"me je meng", "sound":"cfe0208.mp3" , "english":"what name?"},
{"text":"呢", "lshk":"ne", "sound":"cfe0209.mp3" , "english":"particle - how about"},
{"text":"你貴姓呀", "lshk":"nei gwai sing aa", "sound":"cfe0210.mp3" , "english":"What's your surname?"},
{"text":"你呢", "lshk":"nei ne", "sound":"cfe0211.mp3" , "english":"How about you?"},
{"text":"跑步", "lshk":"paau bou", "sound":"cfe0212.mp3" , "english":"running; jogging"},
{"text":"姓", "lshk":"sing", "sound":"cfe0213.mp3" , "english":"be surnamed"},
{"text":"少少", "lshk":"siu siu", "sound":"cfe0214.mp3" , "english":"a few; a little"},
{"text":"彈琴", "lshk":"taan kam", "sound":"cfe0215.mp3" , "english":"play piano"},
{"text":"揸車", "lshk":"zaa ce", "sound":"cfe0216.mp3" , "english":"drive (a vehicle)"},
{"text":"走", "lshk":"zau", "sound":"cfe0217.mp3" , "english":"leave"},
{"text":"啫", "lshk":"ze", "sound":"cfe0218.mp3" , "english":"particle - just"},
{"text":"再見", "lshk":"zoi gin", "sound":"cfe0219.mp3" , "english":"goodbye"},
{"text":"中文", "lshk":"Zung Man", "sound":"cfe0220.mp3" , "english":"Chinese language"},
{"text":"煮飯", "lshk":"zyu faan", "sound":"cfe0221.mp3" , "english":"cook"},
{"text":"廣東話", "lshk":"Gwong Dung Waa", "sound":"cfe0222.mp3" , "english":"Cantonese"},
{"text":"識", "lshk":"sik", "sound":"cfe0223.mp3" , "english":"to know"},
{"text":"幾點", "lshk":"gei dim", "sound":"cfe0224.mp3" , "english":"what time"},
{"text":"幾點鐘", "lshk":"gei dim zung", "sound":"cfe0225.mp3" , "english":"what time"},
{"text":"阿", "lshk":"aa", "sound":"cfe0226.mp3" , "english":"name prefix"},
{"text":"百貨公司", "lshk":"baak fo gung si", "sound":"cfe0227.mp3" , "english":"department store"},
{"text":"不過", "lshk":"bat gwo", "sound":"cfe0228.mp3" , "english":"but, however"},
{"text":"餐廳", "lshk":"caan teng", "sound":"cfe0229.mp3" , "english":"restaurant"},
{"text":"診所", "lshk":"can so", "sound":"cfe0230.mp3" , "english":"clinic"},
{"text":"從來唔", "lshk":"cung loi m", "sound":"cfe0231.mp3" , "english":"never"},
{"text":"廚師", "lshk":"cyu si", "sound":"cfe0232.mp3" , "english":"cook; a chef"},
{"text":"家庭主婦", "lshk":"gaa ting zyu fu", "sound":"cfe0233.mp3" , "english":"housewife"},
{"text":"間中", "lshk":"gaan zung", "sound":"cfe0234.mp3" , "english":"occasionally"},
{"text":"教", "lshk":"gaau", "sound":"cfe0235.mp3" , "english":"teach"},
{"text":"教練", "lshk":"gaau lin", "sound":"cfe0236.mp3" , "english":"coach; instructor"},
{"text":"教授", "lshk":"gaau sau", "sound":"cfe0237.mp3" , "english":"professor"},
{"text":"經理", "lshk":"ging lei", "sound":"cfe0238.mp3" , "english":"manager"},
{"text":"經常", "lshk":"ging soeng", "sound":"cfe0239.mp3" , "english":"always; often"},
{"text":"警察", "lshk":"ging caat", "sound":"cfe0240.mp3" , "english":"police"},
{"text":"歌手", "lshk":"go sau", "sound":"cfe0241.mp3" , "english":"singer"},
{"text":"講", "lshk":"gong", "sound":"cfe0242.mp3" , "english":"speak; talk"},
{"text":"工廠", "lshk":"gung cong", "sound":"cfe0243.mp3" , "english":"factory"},
{"text":"工人", "lshk":"gung jan", "sound":"cfe0244.mp3" , "english":"worker; servant"},
{"text":"公務員", "lshk":"gung mou jyun", "sound":"cfe0245.mp3" , "english":"civil servant"},
{"text":"公司", "lshk":"gung si", "sound":"cfe0246.mp3" , "english":"company; firm"},
{"text":"廣東人", "lshk":"Gwong Dung jan", "sound":"cfe0247.mp3" , "english":"Cantonese people"},
{"text":"學", "lshk":"hok", "sound":"cfe0248.mp3" , "english":"learn; study"},
{"text":"學院", "lshk":"hok jyun", "sound":"cfe0249.mp3" , "english":"college; faculty"},
{"text":"好少", "lshk":"hou siu", "sound":"cfe0250.mp3" , "english":"rarely;seldom"},
{"text":"一齊", "lshk":"jat cai", "sound":"cfe0251.mp3" , "english":"together"},
{"text":"有時", "lshk":"jau si", "sound":"cfe0252.mp3" , "english":"sometimes"},
{"text":"醫院", "lshk":"ji jyun", "sound":"cfe0253.mp3" , "english":"hospital"},
{"text":"醫生", "lshk":"ji sang", "sound":"cfe0254.mp3" , "english":"medical doctor"},
{"text":"演員", "lshk":"jin jyun", "sound":"cfe0255.mp3" , "english":"actor"},
{"text":"律師", "lshk":"leot si", "sound":"cfe0256.mp3" , "english":"lawyer"},
{"text":"練習", "lshk":"lin zaap", "sound":"cfe0257.mp3" , "english":"to practice"},
{"text":"男朋友", "lshk":"naam pang jau", "sound":"cfe0258.mp3" , "english":"boyfriend"},
{"text":"女演員", "lshk":"neoi jin jyun", "sound":"cfe0259.mp3" , "english":"actress"},
{"text":"社工", "lshk":"se gung", "sound":"cfe0260.mp3" , "english":"social worker"},
{"text":"時時", "lshk":"si si", "sound":"cfe0261.mp3" , "english":"always; often"},
{"text":"侍應", "lshk":"si jing", "sound":"cfe0262.mp3" , "english":"waiter; waitress"},
{"text":"消防員", "lshk":"siu fong jyun", "sound":"cfe0263.mp3" , "english":"fireman"},
{"text":"位", "lshk":"wai", "sound":"cfe0264.mp3" , "english":"MW - person"},
{"text":"護士", "lshk":"wu si", "sound":"cfe0265.mp3" , "english":"nurse"},
{"text":"會計師", "lshk":"wui gai si", "sound":"cfe0266.mp3" , "english":"accountant"},
{"text":"酒樓", "lshk":"zau lau", "sound":"cfe0267.mp3" , "english":"Chinese restaurant"},
{"text":"政府部門", "lshk":"zing fu bou mun", "sound":"cfe0268.mp3" , "english":"government departments"},
{"text":"中醫", "lshk":"zung ji", "sound":"cfe0269.mp3" , "english":"Chinese med doctor"},
{"text":"鍾意", "lshk":"zung ji", "sound":"cfe0270.mp3" , "english":"to like, be fond of"},
{"text":"八月", "lshk":"baat jyut", "sound":"cfe0271.mp3" , "english":"August"},
{"text":"報紙", "lshk":"bou zi", "sound":"cfe0272.mp3" , "english":"newpapers"},
{"text":"噚日", "lshk":"cam jat", "sound":"cfe0273.mp3" , "english":"yesterday"},
{"text":"七月", "lshk":"cat jyut", "sound":"cfe0274.mp3" , "english":"July"},
{"text":"出年", "lshk":"ceot nin", "sound":"cfe0275.mp3" , "english":"next year"},
{"text":"前年", "lshk":"cin nin", "sound":"cfe0276.mp3" , "english":"the year before last"},
{"text":"前日", "lshk":"cin jat", "sound":"cfe0277.mp3" , "english":"the day before yesterday"},
{"text":"沖涼", "lshk":"cung loeng", "sound":"cfe0278.mp3" , "english":"take a bath or shower"},
{"text":"打波", "lshk":"daa bo", "sound":"cfe0279.mp3" , "english":"play ball games"},
{"text":"得閒", "lshk":"dak haan", "sound":"cfe0280.mp3" , "english":"have free time; not busy"},
{"text":"都", "lshk":"dou", "sound":"cfe0281.mp3" , "english":"also; too; all"},
{"text":"到", "lshk":"dou", "sound":"cfe0282.mp3" , "english":"until; to"},
{"text":"讀大學", "lshk":"duk daai hok", "sound":"cfe0283.mp3" , "english":"go to university"},
{"text":"返工", "lshk":"faan gung", "sound":"cfe0284.mp3" , "english":"go to work"},
{"text":"瞓覺", "lshk":"fan gaau", "sound":"cfe0285.mp3" , "english":"sleep"},
{"text":"今個星期", "lshk":"gam go sing kei", "sound":"cfe0286.mp3" , "english":"this week"},
{"text":"今個月", "lshk":"gam go jyut", "sound":"cfe0287.mp3" , "english":"this month"},
{"text":"今日", "lshk":"gam jat", "sound":"cfe0288.mp3" , "english":"today"},
{"text":"今晚", "lshk":"gam maan", "sound":"cfe0289.mp3" , "english":"tonight"},
{"text":"緊", "lshk":"gan", "sound":"cfe0290.mp3" , "english":"-ing as in doing"},
{"text":"九月", "lshk":"gau jyut", "sound":"cfe0291.mp3" , "english":"September"},
{"text":"舊年", "lshk":"gau nin", "sound":"cfe0292.mp3" , "english":"last year"},
{"text":"幾", "lshk":"gei", "sound":"cfe0293.mp3" , "english":"quite; fairly"},
{"text":"幾時", "lshk":"gei si", "sound":"cfe0294.mp3" , "english":"when; at what time"},
{"text":"過獎", "lshk":"gwo zoeng", "sound":"cfe0295.mp3" , "english":"you flatter me"},
{"text":"下個月", "lshk":"haa go jyut", "sound":"cfe0296.mp3" , "english":"next month"},
{"text":"下個星期", "lshk":"haa go sing kei", "sound":"cfe0297.mp3" , "english":"next week"},
{"text":"後日", "lshk":"hau jat", "sound":"cfe0298.mp3" , "english":"the day after tomorrow"},
{"text":"後年", "lshk":"hau nin", "sound":"cfe0299.mp3" , "english":"the year after next"},
{"text":"起身", "lshk":"hei san", "sound":"cfe0300.mp3" , "english":"get up"},
{"text":"一月", "lshk":"jat jyut", "sound":"cfe0301.mp3" , "english":"January"},
{"text":"二月", "lshk":"ji jyut", "sound":"cfe0302.mp3" , "english":"February"},
{"text":"傾電話", "lshk":"king din waa", "sound":"cfe0303.mp3" , "english":"chat on the phone"},
{"text":"傾偈", "lshk":"king gai", "sound":"cfe0304.mp3" , "english":"chat"},
{"text":"律師樓", "lshk":"leot si lau", "sound":"cfe0305.mp3" , "english":"law firm"},
{"text":"六月", "lshk":"luk jyut", "sound":"cfe0306.mp3" , "english":"June"},
{"text":"唔係幾", "lshk":"m hai gei", "sound":"cfe0307.mp3" , "english":"not quite"},
{"text":"唔使", "lshk":"m sai", "sound":"cfe0308.mp3" , "english":"no need"},
{"text":"麻麻哋", "lshk":"maa maa dei", "sound":"cfe0309.mp3" , "english":"so-so"},
{"text":"買嘢", "lshk":"maai je", "sound":"cfe0310.mp3" , "english":"do shopping; buy sth"},
{"text":"乜嘢公司", "lshk":"mat je gung si", "sound":"cfe0311.mp3" , "english":"what kind of company"},
{"text":"忙", "lshk":"mong", "sound":"cfe0312.mp3" , "english":"busy"},
{"text":"五月", "lshk":"ng jyut", "sound":"cfe0313.mp3" , "english":"May"},
{"text":"呢個月", "lshk":"ni go jyut", "sound":"cfe0314.mp3" , "english":"this month"},
{"text":"呢個星期", "lshk":"ni go sing kei", "sound":"cfe0315.mp3" , "english":"this week"},
{"text":"年", "lshk":"nin", "sound":"cfe0316.mp3" , "english":"year"},
{"text":"三月", "lshk":"saam jyut", "sound":"cfe0317.mp3" , "english":"March"},
{"text":"散步", "lshk":"saan bou", "sound":"cfe0318.mp3" , "english":"stroll"},
{"text":"十一月", "lshk":"sap jat jyut", "sound":"cfe0319.mp3" , "english":"November"},
{"text":"十二月", "lshk":"sap ji jyut", "sound":"cfe0320.mp3" , "english":"December"},
{"text":"十月", "lshk":"sap jyut", "sound":"cfe0321.mp3" , "english":"October"},
{"text":"四月", "lshk":"sei jyut", "sound":"cfe0322.mp3" , "english":"April"},
{"text":"食嘢", "lshk":"sik je", "sound":"cfe0323.mp3" , "english":"eat something"},
{"text":"星期", "lshk":"sing kei", "sound":"cfe0324.mp3" , "english":"week; day of a week"},
{"text":"星期一", "lshk":"sing kei jat", "sound":"cfe0325.mp3" , "english":"Monday"},
{"text":"星期日", "lshk":"sing kei jat", "sound":"cfe0326.mp3" , "english":"Sunday"},
{"text":"星期二", "lshk":"sing kei ji", "sound":"cfe0327.mp3" , "english":"Tuesday"},
{"text":"星期六", "lshk":"sing kei luk", "sound":"cfe0328.mp3" , "english":"Saturday"},
{"text":"星期五", "lshk":"sing kei ng", "sound":"cfe0329.mp3" , "english":"Friday"},
{"text":"星期三", "lshk":"sing kei saam", "sound":"cfe0330.mp3" , "english":"Wednesday"},
{"text":"星期四", "lshk":"sing kei sei", "sound":"cfe0331.mp3" , "english":"Thursday"},
{"text":"上堂", "lshk":"soeng tong", "sound":"cfe0332.mp3" , "english":"to attend class"},
{"text":"上個月", "lshk":"soeng go jyut", "sound":"cfe0333.mp3" , "english":"last month"},
{"text":"上個星期", "lshk":"soeng go sing kei", "sound":"cfe0334.mp3" , "english":"last week"},
{"text":"探朋友", "lshk":"taam pang jau", "sound":"cfe0335.mp3" , "english":"visit a friend"},
{"text":"睇報紙", "lshk":"tai bou zi", "sound":"cfe0336.mp3" , "english":"read newspaper"},
{"text":"踢波", "lshk":"tek bo", "sound":"cfe0337.mp3" , "english":"play soccer"},
{"text":"聽日", "lshk":"ting jat", "sound":"cfe0338.mp3" , "english":"tomorrow"},
{"text":"運動", "lshk":"wan dung", "sound":"cfe0339.mp3" , "english":"workout"},
{"text":"喎", "lshk":"wo", "sound":"cfe0340.mp3" , "english":"particle - realization"},
{"text":"周末", "lshk":"zau mut", "sound":"cfe0341.mp3" , "english":"weekend"},
{"text":"最", "lshk":"zeoi", "sound":"cfe0342.mp3" , "english":"the most"},
{"text":"至", "lshk":"zi", "sound":"cfe0343.mp3" , "english":"until; to"},
{"text":"做", "lshk":"zou", "sound":"cfe0344.mp3" , "english":"do; work; engage in"},
{"text":"做乜嘢", "lshk":"zou mat je", "sound":"cfe0345.mp3" , "english":"what's the matter?"},
{"text":"做事", "lshk":"zou si", "sound":"cfe0346.mp3" , "english":"work"},
{"text":"做運動", "lshk":"zou wan dung", "sound":"cfe0347.mp3" , "english":"to workout"},
{"text":"月", "lshk":"jyut", "sound":"cfe0348.mp3" , "english":"moon; months"},
{"text":"便利店", "lshk":"bin lei dim", "sound":"cfe0349.mp3" , "english":"convenience store"},
{"text":"茶餐廳", "lshk":"caa caan teng", "sound":"cfe0350.mp3" , "english":"Hong Kong style cafe"},
{"text":"請問", "lshk":"ceng man", "sound":"cfe0351.mp3" , "english":"may I ask"},
{"text":"出面", "lshk":"ceot min", "sound":"cfe0352.mp3" , "english":"outside"},
{"text":"超級市場", "lshk":"ciu kap si coeng", "sound":"cfe0353.mp3" , "english":"supermarket"},
{"text":"地下", "lshk":"dei haa", "sound":"cfe0354.mp3" , "english":"ground floor"},
{"text":"地下", "lshk":"dei haa", "sound":"cfe0355.mp3" , "english":"underground"},
{"text":"地鐵", "lshk":"dei tit", "sound":"cfe0356.mp3" , "english":"underground railway"},
{"text":"地鐵站", "lshk":"dei tit zaam", "sound":"cfe0357.mp3" , "english":"MTR station"},
{"text":"對面", "lshk":"deoi min", "sound":"cfe0358.mp3" , "english":"opposite (side)"},
{"text":"賭場", "lshk":"dou coeng", "sound":"cfe0359.mp3" , "english":"casino"},
{"text":"返", "lshk":"faan", "sound":"cfe0360.mp3" , "english":"return; go/come back"},
{"text":"附近", "lshk":"fu gan", "sound":"cfe0361.mp3" , "english":"vicinity; nearby"},
{"text":"街市", "lshk":"gaai si", "sound":"cfe0362.mp3" , "english":"market"},
{"text":"隔離", "lshk":"gaak lei", "sound":"cfe0363.mp3" , "english":"neighboring; next to"},
{"text":"間", "lshk":"gaan", "sound":"cfe0364.mp3" , "english":"MW for buildings etc."},
{"text":"警局", "lshk":"ging guk", "sound":"cfe0365.mp3" , "english":"police station"},
{"text":"公園", "lshk":"gung jyun", "sound":"cfe0366.mp3" , "english":"park"},
{"text":"櫃員機", "lshk":"gwai jyun gei", "sound":"cfe0367.mp3" , "english":"teller machine"},
{"text":"下面", "lshk":"haa min", "sound":"cfe0368.mp3" , "english":"below; under"},
{"text":"後面", "lshk":"hau min", "sound":"cfe0369.mp3" , "english":"at the back"},
{"text":"戲院", "lshk":"hei jyun", "sound":"cfe0370.mp3" , "english":"cinema"},
{"text":"入面", "lshk":"jap min", "sound":"cfe0371.mp3" , "english":"inside; in"},
{"text":"郵局", "lshk":"jau guk", "sound":"cfe0372.mp3" , "english":"post office"},
{"text":"右面", "lshk":"jau min", "sound":"cfe0373.mp3" , "english":"the right side"},
{"text":"二樓", "lshk":"ji lau", "sound":"cfe0374.mp3" , "english":"second floor"},
{"text":"藥房", "lshk":"joek fong", "sound":"cfe0375.mp3" , "english":"pharmacy"},
{"text":"樓", "lshk":"lau", "sound":"cfe0376.mp3" , "english":"floor"},
{"text":"樓下", "lshk":"lau haa", "sound":"cfe0377.mp3" , "english":"downstairs"},
{"text":"樓上", "lshk":"lau soeng", "sound":"cfe0378.mp3" , "english":"upstairs"},
{"text":"裏面", "lshk":"leoi min", "sound":"cfe0379.mp3" , "english":"in; inside"},
{"text":"攞", "lshk":"lo", "sound":"cfe0380.mp3" , "english":"take; get; fetch"},
{"text":"攞錢", "lshk":"lo cin", "sound":"cfe0381.mp3" , "english":"withdraw money"},
{"text":"唔使多謝", "lshk":"m sai do ze", "sound":"cfe0382.mp3" , "english":"You're welcome."},
{"text":"唔使客氣", "lshk":"m sai haak hei", "sound":"cfe0383.mp3" , "english":"Don't mention it."},
{"text":"唔使唔該", "lshk":"m sai m goi", "sound":"cfe0384.mp3" , "english":"not at all; you're welcome"},
{"text":"馬場", "lshk":"maa coeng", "sound":"cfe0385.mp3" , "english":"horse racing track"},
{"text":"外面", "lshk":"ngoi min", "sound":"cfe0386.mp3" , "english":"outside"},
{"text":"澳門", "lshk":"Ou Mun", "sound":"cfe0387.mp3" , "english":"Macau"},
{"text":"旁邊", "lshk":"pong bin", "sound":"cfe0388.mp3" , "english":"beside; by the side of"},
{"text":"食", "lshk":"sik", "sound":"cfe0389.mp3" , "english":"eat"},
{"text":"消防局", "lshk":"siu fong guk", "sound":"cfe0390.mp3" , "english":"fire station"},
{"text":"上面", "lshk":"soeng min", "sound":"cfe0391.mp3" , "english":"above; on-top"},
{"text":"書局", "lshk":"syu guk", "sound":"cfe0392.mp3" , "english":"bookshop"},
{"text":"站", "lshk":"zaam", "sound":"cfe0393.mp3" , "english":"station; a stop"},
{"text":"側邊", "lshk":"zak bin", "sound":"cfe0394.mp3" , "english":"beside; by the side of"},
{"text":"周圍", "lshk":"zau wai", "sound":"cfe0395.mp3" , "english":"around; surroundings"},
{"text":"知", "lshk":"zi", "sound":"cfe0396.mp3" , "english":"to know about"},
{"text":"知道", "lshk":"zi dou", "sound":"cfe0397.mp3" , "english":"to know about"},
{"text":"自動", "lshk":"zi dung", "sound":"cfe0398.mp3" , "english":"automatic"},
{"text":"櫃員機", "lshk":"gwai jyun gei", "sound":"cfe0399.mp3" , "english":"ATM"},
{"text":"左面", "lshk":"zo min", "sound":"cfe0400.mp3" , "english":"the left side"},
{"text":"早餐", "lshk":"zou caan", "sound":"cfe0401.mp3" , "english":"breakfast"},
{"text":"早晨", "lshk":"zou san", "sound":"cfe0402.mp3" , "english":"good morning"},
{"text":"做功課", "lshk":"zou gung fo", "sound":"cfe0403.mp3" , "english":"do homework"},
{"text":"中間", "lshk":"zung gaan", "sound":"cfe0404.mp3" , "english":"in the middle of"},
{"text":"白粥", "lshk":"baak zuk", "sound":"cfe0405.mp3" , "english":"plain rice congee"},
{"text":"飽", "lshk":"baau", "sound":"cfe0406.mp3" , "english":"full (opp. hungry)"},
{"text":"邊啲", "lshk":"bin di", "sound":"cfe0407.mp3" , "english":"which"},
{"text":"邊間", "lshk":"bin gaan", "sound":"cfe0408.mp3" , "english":"whichbuilding"},
{"text":"菠蘿包", "lshk":"bo lo baau", "sound":"cfe0409.mp3" , "english":"pineapple bun"},
{"text":"出街", "lshk":"ceot gaai", "sound":"cfe0410.mp3" , "english":"go out"},
{"text":"腸仔", "lshk":"coeng zai", "sound":"cfe0411.mp3" , "english":"sausage"},
{"text":"蛋撻", "lshk":"daan taat", "sound":"cfe0412.mp3" , "english":"egg tart"},
{"text":"多士", "lshk":"do si", "sound":"cfe0413.mp3" , "english":"toast"},
{"text":"火腿", "lshk":"fo teoi", "sound":"cfe0414.mp3" , "english":"ham"},
{"text":"叫做", "lshk":"giu zou", "sound":"cfe0415.mp3" , "english":"named; known as"},
{"text":"嗰啲", "lshk":"go di", "sound":"cfe0416.mp3" , "english":"that; those"},
{"text":"嗰個", "lshk":"go wai", "sound":"cfe0417.mp3" , "english":"that person"},
{"text":"覺得", "lshk":"gok dak", "sound":"cfe0418.mp3" , "english":"to think; to feel"},
{"text":"港式", "lshk":"Gong sik", "sound":"cfe0419.mp3" , "english":"HK style"},
{"text":"香腸", "lshk":"hoeng coeng", "sound":"cfe0420.mp3" , "english":"sausage"},
{"text":"香港式", "lshk":"Hoeng Gong sik", "sound":"cfe0421.mp3" , "english":"Hong Kong style"},
{"text":"好好食", "lshk":"hou hou sik", "sound":"cfe0422.mp3" , "english":"very tasty"},
{"text":"好味", "lshk":"hou mei", "sound":"cfe0423.mp3" , "english":"tasty"},
{"text":"好食", "lshk":"hou sik", "sound":"cfe0424.mp3" , "english":"good to eat; tasty"},
{"text":"嚟嘅", "lshk":"lai ge", "sound":"cfe0425.mp3" , "english":"particle - explanation"},
{"text":"乜嘢嚟㗎", "lshk":"mat je lai gaa", "sound":"cfe0426.mp3" , "english":"What on earth is this/that?"},
{"text":"麵", "lshk":"min", "sound":"cfe0427.mp3" , "english":"noodles"},
{"text":"麵包", "lshk":"min baau", "sound":"cfe0428.mp3" , "english":"bread"},
{"text":"呢對鞋", "lshk":"ni deoi haai", "sound":"cfe0429.mp3" , "english":"this pair of shoes"},
{"text":"呢啲", "lshk":"ni di", "sound":"cfe0430.mp3" , "english":"this; these"},
{"text":"呢個", "lshk":"ni go", "sound":"cfe0431.mp3" , "english":"this one"},
{"text":"呢件衫", "lshk":"ni gin saam", "sound":"cfe0432.mp3" , "english":"this piece of clothing; this clothes"},
{"text":"皮蛋", "lshk":"pei daan", "sound":"cfe0433.mp3" , "english":"preserved egg"},
{"text":"瘦肉粥", "lshk":"sau juk zuk", "sound":"cfe0434.mp3" , "english":"congee with lean pork"},
{"text":"三文治", "lshk":"saam man zi", "sound":"cfe0435.mp3" , "english":"sandwiches"},
{"text":"西式", "lshk":"sai sik", "sound":"cfe0436.mp3" , "english":"Western style"},
{"text":"瘦肉", "lshk":"sau juk", "sound":"cfe0437.mp3" , "english":"lean pork; lean meat"},
{"text":"試吓", "lshk":"si haa", "sound":"cfe0438.mp3" , "english":"have a try"},
{"text":"肚餓", "lshk":"tou ngo", "sound":"cfe0439.mp3" , "english":"hungry"},
{"text":"粥", "lshk":"zuk", "sound":"cfe0440.mp3" , "english":"rice congee"},
{"text":"中式", "lshk":"Zung sik", "sound":"cfe0441.mp3" , "english":"Chinese style"},
{"text":"啱", "lshk":"aam", "sound":"cfe0442.mp3" , "english":"correct"},
{"text":"杯", "lshk":"bui", "sound":"cfe0443.mp3" , "english":"glass, cup, mug"},
{"text":"差", "lshk":"caa", "sound":"cfe0444.mp3" , "english":"bad; below standard"},
{"text":"橙汁", "lshk":"caang zap", "sound":"cfe0445.mp3" , "english":"orange juice"},
{"text":"醜樣", "lshk":"cau joeng", "sound":"cfe0446.mp3" , "english":"ugly"},
{"text":"臭", "lshk":"cau", "sound":"cfe0447.mp3" , "english":"smelly, stench"},
{"text":"請", "lshk":"ceng", "sound":"cfe0448.mp3" , "english":"please; invite, treat"},
{"text":"蠢", "lshk":"ceon", "sound":"cfe0449.mp3" , "english":"stupid"},
{"text":"黐線", "lshk":"ci sin", "sound":"cfe0450.mp3" , "english":"crazy"},
{"text":"錯", "lshk":"co", "sound":"cfe0451.mp3" , "english":"wrong"},
{"text":"長", "lshk":"coeng", "sound":"cfe0452.mp3" , "english":"long"},
{"text":"嘈", "lshk":"cou", "sound":"cfe0453.mp3" , "english":"noisy"},
{"text":"聰明", "lshk":"cung ming", "sound":"cfe0454.mp3" , "english":"smart, intelligent"},
{"text":"蛋", "lshk":"daan", "sound":"cfe0455.mp3" , "english":"egg"},
{"text":"低", "lshk":"dai", "sound":"cfe0456.mp3" , "english":"low"},
{"text":"定係", "lshk":"ding hai", "sound":"cfe0457.mp3" , "english":"or (in questions)"},
{"text":"碟", "lshk":"dip", "sound":"cfe0458.mp3" , "english":"a plate of"},
{"text":"短", "lshk":"dyun", "sound":"cfe0459.mp3" , "english":"short (in length)"},
{"text":"肥", "lshk":"fei", "sound":"cfe0460.mp3" , "english":"fat"},
{"text":"方便", "lshk":"fong bin", "sound":"cfe0461.mp3" , "english":"convenient"},
{"text":"父母", "lshk":"fu mou", "sound":"cfe0462.mp3" , "english":"parents"},
{"text":"加", "lshk":"gaa", "sound":"cfe0463.mp3" , "english":"add"},
{"text":"咖啡", "lshk":"gaa fe", "sound":"cfe0464.mp3" , "english":"coffee"},
{"text":"雞蛋", "lshk":"gai daan", "sound":"cfe0465.mp3" , "english":"egg"},
{"text":"緊張", "lshk":"gan zoeng", "sound":"cfe0466.mp3" , "english":"nervous"},
{"text":"頸渴", "lshk":"geng hot", "sound":"cfe0467.mp3" , "english":"thirsty"},
{"text":"高", "lshk":"gou", "sound":"cfe0468.mp3" , "english":"tall; high"},
{"text":"乖", "lshk":"gwaai", "sound":"cfe0469.mp3" , "english":"good; obedient"},
{"text":"喺度食", "lshk":"hai dou sik", "sound":"cfe0470.mp3" , "english":"eat here"},
{"text":"冚唪唥", "lshk":"ham baang laang", "sound":"cfe0471.mp3" , "english":"all; whole"},
{"text":"後生", "lshk":"hau saang", "sound":"cfe0472.mp3" , "english":"young"},
{"text":"汽水", "lshk":"hei seoi", "sound":"cfe0473.mp3" , "english":"soft drinks"},
{"text":"兄弟", "lshk":"hing dai", "sound":"cfe0474.mp3" , "english":"brothers"},
{"text":"可樂", "lshk":"ho lok", "sound":"cfe0475.mp3" , "english":"coke"},
{"text":"開心", "lshk":"hoi sam", "sound":"cfe0476.mp3" , "english":"happy"},
{"text":"好飲", "lshk":"hou jam", "sound":"cfe0477.mp3" , "english":"tasty (for drinks)"},
{"text":"好人", "lshk":"hou jan", "sound":"cfe0478.mp3" , "english":"kind; nice person"},
{"text":"好玩", "lshk":"hou waan", "sound":"cfe0479.mp3" , "english":"fun, interesting"},
{"text":"曳", "lshk":"jai", "sound":"cfe0480.mp3" , "english":"naughty"},
{"text":"飲", "lshk":"jam", "sound":"cfe0481.mp3" , "english":"drink"},
{"text":"一共", "lshk":"jat gung", "sound":"cfe0482.mp3" , "english":"total, altogether"},
{"text":"一陣", "lshk":"jat zan", "sound":"cfe0483.mp3" , "english":"a little while"},
{"text":"鴛鴦", "lshk":"jin joeng", "sound":"cfe0484.mp3" , "english":"milktea + coffee"},
{"text":"容易", "lshk":"jung ji", "sound":"cfe0485.mp3" , "english":"easy"},
{"text":"遠", "lshk":"jyun", "sound":"cfe0486.mp3" , "english":"far"},
{"text":"勤力", "lshk":"kan lik", "sound":"cfe0487.mp3" , "english":"hardworking"},
{"text":"懶", "lshk":"laan", "sound":"cfe0488.mp3" , "english":"lazy"},
{"text":"老", "lshk":"lou", "sound":"cfe0489.mp3" , "english":"old (not young)"},
{"text":"慢", "lshk":"maan", "sound":"cfe0490.mp3" , "english":"slow"},
{"text":"奶", "lshk":"naai", "sound":"cfe0491.mp3" , "english":"milk"},
{"text":"奶茶", "lshk":"naai caa", "sound":"cfe0492.mp3" , "english":"milk tea"},
{"text":"危險", "lshk":"ngai him", "sound":"cfe0493.mp3" , "english":"dangerous"},
{"text":"牛奶", "lshk":"ngau naai", "sound":"cfe0494.mp3" , "english":"milk"},
{"text":"餓", "lshk":"ngo", "sound":"cfe0495.mp3" , "english":"hungry"},
{"text":"拎走", "lshk":"ning zau", "sound":"cfe0496.mp3" , "english":"take away"},
{"text":"檸檬茶", "lshk":"ning mung caa", "sound":"cfe0497.mp3" , "english":"lemon tea"},
{"text":"檸檬水", "lshk":"ning mung seoi", "sound":"cfe0498.mp3" , "english":"lemonade"},
{"text":"安全", "lshk":"on cyun", "sound":"cfe0499.mp3" , "english":"safe"},
{"text":"犀利", "lshk":"sai lei", "sound":"cfe0500.mp3" , "english":"terrific, extreme"},
{"text":"辛苦", "lshk":"san fu", "sound":"cfe0501.mp3" , "english":"hard;tough"},
{"text":"新嘢", "lshk":"san je", "sound":"cfe0502.mp3" , "english":"new stuff"},
{"text":"瘦", "lshk":"sau", "sound":"cfe0503.mp3" , "english":"thin; slim; not fat"},
{"text":"衰", "lshk":"seoi", "sound":"cfe0504.mp3" , "english":"bad; evil minded"},
{"text":"水皮", "lshk":"seoi pei", "sound":"cfe0505.mp3" , "english":"not up to standard"},
{"text":"鮮奶", "lshk":"sin naai", "sound":"cfe0506.mp3" , "english":"fresh milk"},
{"text":"傻", "lshk":"so", "sound":"cfe0507.mp3" , "english":"silly"},
{"text":"舒服", "lshk":"syu fuk", "sound":"cfe0508.mp3" , "english":"comfortable"},
{"text":"糖", "lshk":"tong", "sound":"cfe0509.mp3" , "english":"sugar"},
{"text":"齋啡", "lshk":"zaai fe", "sound":"cfe0510.mp3" , "english":"black coffee"},
{"text":"正", "lshk":"zeng", "sound":"cfe0511.mp3" , "english":"exact; cool"},
{"text":"姐妹", "lshk":"zi mui", "sound":"cfe0512.mp3" , "english":"sisters"},
{"text":"即係", "lshk":"zik hai", "sound":"cfe0513.mp3" , "english":"it means..."},
{"text":"靜", "lshk":"zing", "sound":"cfe0514.mp3" , "english":"quiet"},
{"text":"朱古力", "lshk":"zyu gu lik", "sound":"cfe0515.mp3" , "english":"chocolate"},
{"text":"吖", "lshk":"aa", "sound":"cfe0516.mp3" , "english":"particle - suggestion"},
{"text":"叉燒包", "lshk":"caa siu baau", "sound":"cfe0517.mp3" , "english":"BBQ pork buns"},
{"text":"炒飯", "lshk":"caau faan", "sound":"cfe0518.mp3" , "english":"fried rice"},
{"text":"春卷", "lshk":"ceon gyun", "sound":"cfe0519.mp3" , "english":"spring rolls"},
{"text":"豆腐花", "lshk":"dau fu faa", "sound":"cfe0520.mp3" , "english":"bean curd dessert"},
{"text":"點心", "lshk":"dim sam", "sound":"cfe0521.mp3" , "english":"dim-sum"},
{"text":"多謝先", "lshk":"do ze sin", "sound":"cfe0522.mp3" , "english":"thank you in advance"},
{"text":"AA制", "lshk":"ei ei zai", "sound":"cfe0523.mp3" , "english":"go Dutch"},
{"text":"返屋企", "lshk":"faan uk kei", "sound":"cfe0524.mp3" , "english":"go/come home"},
{"text":"飯", "lshk":"faan", "sound":"cfe0525.mp3" , "english":"cooked rice"},
{"text":"交功課", "lshk":"gaau gung fo", "sound":"cfe0526.mp3" , "english":"submit homework"},
{"text":"結婚", "lshk":"git fan", "sound":"cfe0527.mp3" , "english":"get married"},
{"text":"焗", "lshk":"guk", "sound":"cfe0528.mp3" , "english":"baked"},
{"text":"滾水", "lshk":"gwan seoi", "sound":"cfe0529.mp3" , "english":"boiling water"},
{"text":"行喇", "lshk":"haang laa", "sound":"cfe0530.mp3" , "english":"let's go"},
{"text":"去街", "lshk":"heoi gaai", "sound":"cfe0531.mp3" , "english":"go out"},
{"text":"好唔好呀", "lshk":"hou m hou aa", "sound":"cfe0532.mp3" , "english":"Is that good? Is it okay?"},
{"text":"紅豆沙", "lshk":"hung dau saa", "sound":"cfe0533.mp3" , "english":"red bean sweet soup"},
{"text":"飲嘢", "lshk":"jam je", "sound":"cfe0534.mp3" , "english":"have a drink"},
{"text":"飲酒", "lshk":"jam zau", "sound":"cfe0535.mp3" , "english":"have a alcohol drink"},
{"text":"肉", "lshk":"juk", "sound":"cfe0536.mp3" , "english":"meat"},
{"text":"埋單", "lshk":"maai daan", "sound":"cfe0537.mp3" , "english":"add up the bill; pay"},
{"text":"晚飯", "lshk":"maan faan", "sound":"cfe0538.mp3" , "english":"dinner"},
{"text":"未", "lshk":"mei", "sound":"cfe0539.mp3" , "english":"not yet"},
{"text":"女", "lshk":"neoi", "sound":"cfe0540.mp3" , "english":"daughter"},
{"text":"普洱", "lshk":"Pou Lei", "sound":"cfe0541.mp3" , "english":"Pu'er tea (black tea)"},
{"text":"食晏晝", "lshk":"sik aan zau", "sound":"cfe0542.mp3" , "english":"have a lunch"},
{"text":"先", "lshk":"sin", "sound":"cfe0543.mp3" , "english":"first; in advance"},
{"text":"添", "lshk":"tim", "sound":"cfe0544.mp3" , "english":"particle - even"},
{"text":"甜品", "lshk":"tim ban", "sound":"cfe0545.mp3" , "english":"dessert"},
{"text":"或者", "lshk":"waak ze", "sound":"cfe0546.mp3" , "english":"or (in statements)"},
{"text":"喂", "lshk":"wai", "sound":"cfe0547.mp3" , "english":"hello; hey"},
{"text":"壺", "lshk":"wu", "sound":"cfe0548.mp3" , "english":"a pot of"},
{"text":"炸", "lshk":"zaa", "sound":"cfe0549.mp3" , "english":"deep fry"},
{"text":"齋", "lshk":"zaai", "sound":"cfe0550.mp3" , "english":"vegetarian food"},
{"text":"仔", "lshk":"zai", "sound":"cfe0551.mp3" , "english":"son"},
{"text":"真係", "lshk":"zan hai", "sound":"cfe0552.mp3" , "english":"really; indeed"},
{"text":"蒸", "lshk":"zing", "sound":"cfe0553.mp3" , "english":"steam"},
{"text":"咗", "lshk":"zo", "sound":"cfe0554.mp3" , "english":"(perfective form)"},
{"text":"中國菜", "lshk":"Zung Gwok coi", "sound":"cfe0555.mp3" , "english":"Chinese cuisine"},
{"text":"仲", "lshk":"zung", "sound":"cfe0556.mp3" , "english":"still; also"},
{"text":"放工", "lshk":"fong gung", "sound":"cfe0557.mp3" , "english":"finish work; off duty"}
];

function Question(id){
  var item = BANK[id];
  this.text = item.text;
  this.lshk = item.lshk;
  this.english = item.english;
  this.sound = item.sound;
  this.id = this.sound.substr(0,this.sound.length-4);
}

Question.prototype.check = function(attempt) {
  return this.lshk == attempt;
}

